#!/usr/bin/env bash
# gen-aliases.sh: writes migrations/000010_binance_source.up.sql, the source binance and the identity alias rows of its
# assets (SRS - Binance §2.4 Seed data, §3.1; X1 D-5, X1 D-22). Run by the owner through make binance-aliases
# (X1 D-23), never in a test run or in CI.
#
# What it does:
#   1. reads GET https://api.binance.com/api/v3/exchangeInfo: a public call, no key;
#   2. takes baseAsset and quoteAsset of every symbol, unique and sorted;
#   3. writes the complete up migration: the source row with the X1 values of SRS - Binance §3.1 (base_url,
#      budget_share, recv_window_ms, time_sync_interval, sync_interval.balances; the keys of X2 and W1 come with
#      their migrations), then one identity row
#      (native_asset = asset, decimals NULL) per asset, with a header comment that states the generation date and the
#      count of assets;
#   4. prints the count and every code that starts with LD, for the owner to review: a real asset such as LDO gets a
#      row, a wrapper code of Earn never does.
# Needs: curl, jq. Refuses to run without them.
# Options, for the offline test of the script only: --from FILE reads exchangeInfo from FILE instead of Binance;
#   --out FILE writes there instead of the migration.

set -euo pipefail

readonly EXCHANGE_INFO_URL=https://api.binance.com/api/v3/exchangeInfo
SCRIPT_NAME=$(basename "$0")
readonly SCRIPT_NAME
REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)
readonly REPO_ROOT

die() {
	printf '%s: %s\n' "$SCRIPT_NAME" "$*" >&2
	exit 1
}

for tool in curl jq; do
	command -v "$tool" >/dev/null 2>&1 || die "$tool is not on PATH"
done

from=""
out="$REPO_ROOT/migrations/000010_binance_source.up.sql"
while [ $# -gt 0 ]; do
	case "$1" in
	--from)
		[ $# -ge 2 ] || die "--from needs a file"
		from=$2
		shift 2
		;;
	--out)
		[ $# -ge 2 ] || die "--out needs a file"
		out=$2
		shift 2
		;;
	*) die "unknown argument: $1" ;;
	esac
done

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

if [ -n "$from" ]; then
	[ -f "$from" ] || die "no file $from"
	cp "$from" "$tmp/exchange_info.json"
	origin="a local copy of exchangeInfo"
else
	curl -fsS --max-time 60 -o "$tmp/exchange_info.json" "$EXCHANGE_INFO_URL" || die "GET $EXCHANGE_INFO_URL failed"
	origin="GET $EXCHANGE_INFO_URL"
fi

# Base and quote assets of every symbol, unique and sorted by code point. An asset code is a non-empty string; a
# quote in it is doubled for SQL.
jq -r '
	if (.symbols | type) != "array" or (.symbols | length) == 0 then error("no symbols") else . end
	| [.symbols[] | .baseAsset, .quoteAsset]
	| if any(.[]; type != "string" or . == "" or test("[[:cntrl:]]")) then error("an asset code is not a non-empty string") else . end
	| unique[]' "$tmp/exchange_info.json" >"$tmp/assets" 2>"$tmp/jq.err" ||
	die "exchangeInfo is not as expected: $(head -c 200 "$tmp/jq.err")"

count=$(wc -l <"$tmp/assets" | tr -d ' ')
[ "$count" -gt 0 ] || die "no assets in exchangeInfo"
generated=$(date -u +%Y-%m-%d)

{
	printf -- '-- Source binance and the identity alias rows of its assets (SRS - Binance §2.4 Seed data, §3.1; X1 D-5, X1 D-22).\n'
	printf -- '-- Generated by scripts/binance/gen-aliases.sh on %s from %s: %s assets,\n' "$generated" "$origin" "$count"
	printf -- '-- the base and quote assets of every symbol. Do not edit by hand: run make binance-aliases. A new listing is\n'
	printf -- '-- added by a later migration.\n'
	printf '\n'
	printf "INSERT INTO sources (code, kind, enabled, config) VALUES\n"
	printf "    ('binance', 'EXCHANGE', true, '{\"base_url\": \"https://api.binance.com\", \"budget_share\": 0.5, \"recv_window_ms\": 5000, \"time_sync_interval\": \"1h\", \"sync_interval\": {\"balances\": \"15m\"}}');\n"
	printf '\n'
	printf 'INSERT INTO asset_aliases (source_id, native_asset, asset, decimals)\n'
	printf 'SELECT s.id, a.code, a.code, NULL FROM sources s CROSS JOIN (VALUES\n'
	awk -v n="$count" '{ gsub(/\047/, "\047\047"); printf "    (\047%s\047)%s\n", $0, (NR < n ? "," : "") }' "$tmp/assets"
	printf ') AS a (code)\n'
	printf "WHERE s.code = 'binance';\n"
} >"$tmp/up.sql"
mv "$tmp/up.sql" "$out"

echo "Assets: $count"
echo "Codes starting with LD (each must be a real asset, never an Earn wrapper):"
grep '^LD' "$tmp/assets" | sed 's/^/  /' || echo "  none"
echo "Written: ${out#"$REPO_ROOT"/}"
