-- Core tables of SRS - Core §2.4.1. cards and reconciliation_runs come with S2 and S3.

CREATE TABLE tenants (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name       TEXT        NOT NULL,
    status     TEXT        NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT tenants_name_key UNIQUE (name),
    CONSTRAINT tenants_status_check CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE api_credentials (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID        NOT NULL REFERENCES tenants (id),
    kind        TEXT        NOT NULL,
    key_id      TEXT        NOT NULL,
    secret_hash BYTEA       NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at  TIMESTAMPTZ,
    CONSTRAINT api_credentials_key_id_key UNIQUE (key_id),
    CONSTRAINT api_credentials_kind_check CHECK (kind IN ('SERVICE_TOKEN', 'PROCESSOR_BASIC'))
);

CREATE INDEX api_credentials_tenant_id_idx ON api_credentials (tenant_id);

CREATE TABLE sources (
    id      SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    TEXT     NOT NULL,
    kind    TEXT     NOT NULL,
    enabled BOOLEAN  NOT NULL DEFAULT false,
    config  JSONB    NOT NULL DEFAULT '{}',
    CONSTRAINT sources_code_key UNIQUE (code),
    CONSTRAINT sources_kind_check CHECK (kind IN ('EXCHANGE', 'EVM'))
);

CREATE TABLE connections (
    id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id              UUID        NOT NULL REFERENCES tenants (id),
    owner_ref              TEXT        NOT NULL,
    source_id              SMALLINT    NOT NULL REFERENCES sources (id),
    external_account       TEXT        NOT NULL,
    label                  TEXT,
    status                 TEXT        NOT NULL DEFAULT 'ACTIVE',
    credentials_enc        BYTEA,
    kek_version            SMALLINT,
    key_fingerprint        TEXT,
    permissions            TEXT[],
    permissions_checked_at TIMESTAMPTZ,
    last_manual_sync_at    TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT connections_account_key UNIQUE (tenant_id, source_id, external_account),
    CONSTRAINT connections_status_check CHECK (status IN ('ACTIVE', 'DEGRADED', 'CREDENTIALS_INVALID')),
    CONSTRAINT connections_credentials_check CHECK ((credentials_enc IS NULL) = (kek_version IS NULL))
);

CREATE INDEX connections_tenant_owner_idx ON connections (tenant_id, owner_ref);
CREATE INDEX connections_tenant_created_idx ON connections (tenant_id, created_at, id);

CREATE TABLE asset_aliases (
    source_id    SMALLINT NOT NULL REFERENCES sources (id),
    native_asset TEXT     NOT NULL,
    asset        TEXT     NOT NULL,
    decimals     SMALLINT,
    PRIMARY KEY (source_id, native_asset)
);

CREATE TABLE sync_cursors (
    connection_id        UUID        NOT NULL REFERENCES connections (id) ON DELETE CASCADE,
    stream               TEXT        NOT NULL,
    mode                 TEXT        NOT NULL,
    cursor               JSONB       NOT NULL DEFAULT '{}',
    next_run_at          TIMESTAMPTZ NOT NULL,
    last_success_at      TIMESTAMPTZ,
    last_error           TEXT,
    consecutive_failures INTEGER     NOT NULL DEFAULT 0,
    PRIMARY KEY (connection_id, stream),
    CONSTRAINT sync_cursors_mode_check CHECK (mode IN ('BACKFILL', 'INCREMENTAL')),
    CONSTRAINT sync_cursors_failures_check CHECK (consecutive_failures >= 0)
);

CREATE INDEX sync_cursors_next_run_at_idx ON sync_cursors (next_run_at);

CREATE TABLE balance_snapshots (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    connection_id UUID        NOT NULL REFERENCES connections (id) ON DELETE CASCADE,
    taken_at      TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX balance_snapshots_connection_created_idx ON balance_snapshots (connection_id, created_at DESC);

CREATE TABLE snapshot_balances (
    snapshot_id  UUID           NOT NULL REFERENCES balance_snapshots (id) ON DELETE CASCADE,
    account_type TEXT           NOT NULL,
    native_asset TEXT           NOT NULL,
    asset        TEXT           NOT NULL,
    free         NUMERIC(38, 18) NOT NULL,
    locked       NUMERIC(38, 18) NOT NULL,
    PRIMARY KEY (snapshot_id, account_type, native_asset),
    CONSTRAINT snapshot_balances_account_type_check
        CHECK (account_type IN ('SPOT', 'FUNDING', 'EARN_FLEXIBLE', 'EARN_LOCKED', 'WALLET')),
    CONSTRAINT snapshot_balances_free_check CHECK (free >= 0),
    CONSTRAINT snapshot_balances_locked_check CHECK (locked >= 0)
);

CREATE TABLE ledger_entries (
    seq           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_id     UUID            NOT NULL REFERENCES tenants (id),
    connection_id UUID            NOT NULL REFERENCES connections (id) ON DELETE CASCADE,
    stream        TEXT            NOT NULL,
    external_id   TEXT            NOT NULL,
    leg           TEXT            NOT NULL,
    group_id      TEXT            NOT NULL,
    type          TEXT            NOT NULL,
    direction     TEXT            NOT NULL,
    asset         TEXT            NOT NULL,
    native_asset  TEXT            NOT NULL,
    amount        NUMERIC(38, 18) NOT NULL,
    occurred_at   TIMESTAMPTZ     NOT NULL,
    raw           JSONB           NOT NULL,
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT ledger_entries_idempotency_key UNIQUE (connection_id, stream, external_id, leg),
    CONSTRAINT ledger_entries_leg_check CHECK (leg IN ('SINGLE', 'BASE', 'QUOTE', 'FEE')),
    CONSTRAINT ledger_entries_type_check CHECK (type IN (
        'DEPOSIT', 'WITHDRAWAL', 'TRADE', 'FEE', 'CONVERT', 'REWARD', 'CARD_DEBIT', 'CARD_REFUND'
    )),
    CONSTRAINT ledger_entries_direction_check CHECK (direction IN ('IN', 'OUT')),
    CONSTRAINT ledger_entries_amount_check CHECK (amount > 0)
);

CREATE INDEX ledger_entries_tenant_seq_idx ON ledger_entries (tenant_id, seq);
CREATE INDEX ledger_entries_connection_seq_idx ON ledger_entries (connection_id, seq);

-- No foreign key to connections: rows outlive a deleted connection.
CREATE TABLE audit_log (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_id     UUID        NOT NULL REFERENCES tenants (id),
    credential_id UUID        REFERENCES api_credentials (id),
    action        TEXT        NOT NULL,
    object_id     TEXT        NOT NULL,
    details       JSONB,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT audit_log_action_check CHECK (action IN (
        'CONNECTION_CREATED', 'CONNECTION_DELETED', 'CONNECTION_DEGRADED', 'CONNECTION_RECOVERED',
        'CREDENTIALS_INVALID',
        'TENANT_CREATED', 'TENANT_DISABLED', 'TENANT_ENABLED', 'CREDENTIAL_ISSUED', 'CREDENTIAL_REVOKED',
        'CARD_REGISTERED', 'CARD_UPDATED'
    ))
);

CREATE INDEX audit_log_tenant_created_idx ON audit_log (tenant_id, created_at);
