// Phase 1 of docs/test-plan-x1.md: the migration of the source binance and its generator. The names carry the X1
// row and differ from the rows of the other files.
package migrations_test

import (
	"bytes"
	"encoding/json"
	"io/fs"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/DigitLock/crypto-account-service/internal/connector"
	"github.com/DigitLock/crypto-account-service/internal/connector/binance"
	"github.com/DigitLock/crypto-account-service/internal/testdb"
	"github.com/DigitLock/crypto-account-service/migrations"
)

// binanceVersion is the migration of the source binance (X1 st2).
const binanceVersion = 10

const binanceUp = "000010_binance_source.up.sql"

// wrapperCodes are Earn wrapper codes of SRS — Binance §1: none gets an alias row (X1 D-5).
var wrapperCodes = []string{"LDBTC", "LDETH", "LDBNB", "LDUSDT", "LDUSDC"}

// headerCount is the count of assets the header comment of the generated migration states.
var headerCount = regexp.MustCompile(`(?m)^-- Generated by scripts/binance/gen-aliases\.sh on (\d{4}-\d{2}-\d{2}) from (.+): (\d+) assets,$`)

// aliasCounts returns the count of alias rows of binance, of identity rows without decimals among them, and of
// distinct native assets.
func aliasCounts(t *testing.T, pool *pgxpool.Pool) (rows, identity, distinct int) {
	t.Helper()
	if err := pool.QueryRow(ctx, `SELECT count(*), count(*) FILTER (WHERE a.native_asset = a.asset AND a.decimals IS NULL),
			count(DISTINCT a.native_asset)
		FROM asset_aliases a JOIN sources s ON s.id = a.source_id WHERE s.code = 'binance'`).Scan(&rows, &identity, &distinct); err != nil {
		t.Fatal(err)
	}
	return rows, identity, distinct
}

// X1-T101 — Req: SRS — Binance §2.4 Seed data, §3.1; X1 D-5, X1 D-22. The row binance, kind EXCHANGE, enabled,
// config with the values of §3.1; identity alias rows, unique, as many as the header of the generated migration
// states; no row for a wrapper code; down restores version 9.
func TestT101_BinanceSource(t *testing.T) {
	owner := testdb.Open(t)
	testdb.Clean(t)
	m := testdb.Migrator(t)
	t.Cleanup(func() { migrateTo(t, m, migrations.Latest()) })

	up, err := fs.ReadFile(migrations.FS, binanceUp)
	if err != nil {
		t.Fatal(err)
	}
	header := headerCount.FindSubmatch(up)
	if header == nil || string(header[2]) != "GET https://api.binance.com/api/v3/exchangeInfo" {
		t.Fatalf("%s has no header of the generator run on exchangeInfo of Binance: run make binance-aliases", binanceUp)
	}
	want, _ := strconv.Atoi(string(header[3]))

	var kind string
	var enabled bool
	var raw []byte
	if err := owner.QueryRow(ctx, `SELECT kind, enabled, config FROM sources WHERE code = 'binance'`).Scan(&kind, &enabled, &raw); err != nil {
		t.Fatalf("source binance: %v", err)
	}
	if kind != "EXCHANGE" || !enabled {
		t.Errorf("binance: kind %s, enabled %v; want EXCHANGE, enabled", kind, enabled)
	}
	var config map[string]any
	if err := json.Unmarshal(raw, &config); err != nil {
		t.Fatal(err)
	}
	wantConfig := map[string]any{
		"base_url": "https://api.binance.com", "budget_share": 0.5, "recv_window_ms": 5000.0, "time_sync_interval": "1h",
	}
	interval, _ := config["sync_interval"].(map[string]any)
	delete(config, "sync_interval")
	if !maps.Equal(config, wantConfig) || len(interval) != 1 || interval["balances"] != "15m" {
		t.Errorf("binance config = %s, want the values of SRS — Binance §3.1", raw)
	}
	parsed := binance.ParseConfig(connector.Source{Code: "binance", Kind: kind, Enabled: enabled, Config: raw})
	if parsed != (binance.Config{BaseURL: binance.DefaultBaseURL, BudgetShare: binance.DefaultBudgetShare,
		RecvWindowMS: binance.DefaultRecvWindowMS, TimeSyncInterval: binance.DefaultTimeSyncInterval,
		BalancesInterval: 15 * time.Minute}) {
		t.Errorf("the connector reads %+v from the migrated config", parsed)
	}

	rows, identity, distinct := aliasCounts(t, owner)
	if rows == 0 || rows != want || identity != rows || distinct != rows {
		t.Errorf("alias rows of binance: %d, identity %d, distinct %d; want %d identity rows (header of %s)",
			rows, identity, distinct, want, binanceUp)
	}
	var found []string
	if err := owner.QueryRow(ctx, `SELECT coalesce(array_agg(a.native_asset ORDER BY 1), '{}')
		FROM asset_aliases a JOIN sources s ON s.id = a.source_id
		WHERE s.code = 'binance' AND a.native_asset = ANY($1)`, append(wrapperCodes, "BTC", "USDT")).Scan(&found); err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(found, []string{"BTC", "USDT"}) {
		t.Errorf("aliases among %v and BTC, USDT: %v; want BTC and USDT only", wrapperCodes, found)
	}

	// Down restores version 9: no source binance, no alias of it; the EVM sources and aliases unchanged.
	beforeSchema, beforeEVM := schema(t, owner), aliases(t, owner)
	migrateTo(t, m, binanceVersion-1)
	var n int
	mustQueryRow(t, owner, &n, `SELECT count(*) FROM sources WHERE code = 'binance'`)
	if n != 0 {
		t.Errorf("source binance after down to %d", binanceVersion-1)
	}
	mustQueryRow(t, owner, &n, `SELECT count(*) FROM asset_aliases a LEFT JOIN sources s ON s.id = a.source_id
		WHERE s.kind IS DISTINCT FROM 'EVM'`)
	if n != 0 {
		t.Errorf("%d alias rows of no EVM source after down to %d", n, binanceVersion-1)
	}
	if got := aliases(t, owner); !slices.Equal(got, beforeEVM) {
		t.Errorf("EVM aliases after down = %v, want %v", got, beforeEVM)
	}
	migrateTo(t, m, migrations.Latest())
	if got, _, _ := aliasCounts(t, owner); got != want {
		t.Errorf("alias rows after up again = %d, want %d", got, want)
	}
	if got := schema(t, owner); !slices.Equal(got, beforeSchema) {
		t.Error("the schema after down and up differs")
	}
}

// exchangeInfo is a small fictitious exchangeInfo: duplicates, a real asset that starts with LD, a code with a quote
// and one outside ASCII. Only the members the generator reads, and some it ignores.
const exchangeInfo = `{"timezone": "UTC", "serverTime": 1790000000000, "rateLimits": [], "symbols": [
	{"symbol": "AAABBB", "status": "TRADING", "baseAsset": "AAA", "quoteAsset": "BBB"},
	{"symbol": "LDOBBB", "status": "TRADING", "baseAsset": "LDO", "quoteAsset": "BBB"},
	{"symbol": "CCCAAA", "status": "BREAK", "baseAsset": "CCC", "quoteAsset": "AAA"},
	{"symbol": "QQAAA", "status": "TRADING", "baseAsset": "Q'Q", "quoteAsset": "AAA"},
	{"symbol": "1KZZZBBB", "status": "TRADING", "baseAsset": "1KZZZ", "quoteAsset": "BBB"},
	{"symbol": "ÄÖBBB", "status": "TRADING", "baseAsset": "ÄÖ", "quoteAsset": "BBB"}
]}`

const generatedBody = `INSERT INTO sources (code, kind, enabled, config) VALUES
    ('binance', 'EXCHANGE', true, '{"base_url": "https://api.binance.com", "budget_share": 0.5, "recv_window_ms": 5000, "time_sync_interval": "1h", "sync_interval": {"balances": "15m"}}');

INSERT INTO asset_aliases (source_id, native_asset, asset, decimals)
SELECT s.id, a.code, a.code, NULL FROM sources s CROSS JOIN (VALUES
    ('1KZZZ'),
    ('AAA'),
    ('BBB'),
    ('CCC'),
    ('LDO'),
    ('Q''Q'),
    ('ÄÖ')
) AS a (code)
WHERE s.code = 'binance';
`

// generator returns the path of scripts/binance/gen-aliases.sh, or skips locally when bash, curl or jq is not on
// PATH; in CI it fails.
func generator(t *testing.T) string {
	t.Helper()
	for _, tool := range []string{"bash", "curl", "jq"} {
		if _, err := exec.LookPath(tool); err != nil {
			if os.Getenv("CI") != "" {
				t.Fatalf("%s is not on PATH; it is required in CI", tool)
			}
			t.Skipf("%s is not on PATH", tool)
		}
	}
	path, err := filepath.Abs(filepath.Join("..", "scripts", "binance", "gen-aliases.sh"))
	if err != nil {
		t.Fatal(err)
	}
	return path
}

func runGenerator(t *testing.T, path string, env []string, args ...string) (stdout, stderr string, err error) {
	t.Helper()
	cmd := exec.Command(path, args...)
	if env != nil {
		cmd.Env = env
	}
	var out, errOut bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errOut
	err = cmd.Run()
	return out.String(), errOut.String(), err
}

// X1-T101 — Req: SRS — Binance §2.4 Seed data; X1 D-5, X1 D-22. The generator, offline on a fictitious
// exchangeInfo (--from): base and quote assets unique and sorted, one identity row each, the source row, a header
// with the date and the count; the count and the LD codes printed; it refuses to run without curl or jq and on a
// malformed exchangeInfo. With a test database the output is applied in a transaction that is rolled back.
func TestT101_AliasGenerator(t *testing.T) {
	script := generator(t)
	dir := t.TempDir()
	in, out := filepath.Join(dir, "exchange_info.json"), filepath.Join(dir, "up.sql")
	if err := os.WriteFile(in, []byte(exchangeInfo), 0o644); err != nil {
		t.Fatal(err)
	}
	stdout, stderr, err := runGenerator(t, script, nil, "--from", in, "--out", out)
	if err != nil {
		t.Fatalf("generator: %v\n%s", err, stderr)
	}
	if !strings.HasPrefix(stdout, "Assets: 7\nCodes starting with LD (each must be a real asset, never an Earn wrapper):\n  LDO\n") {
		t.Errorf("stdout = %q", stdout)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	header := headerCount.FindSubmatch(data)
	if header == nil || string(header[2]) != "a local copy of exchangeInfo" || string(header[3]) != "7" {
		t.Fatalf("no header with the date and the count:\n%s", data)
	}
	if day, err := time.Parse("2006-01-02", string(header[1])); err != nil || time.Since(day) < 0 || time.Since(day) > 48*time.Hour {
		t.Errorf("generation date %s, want today (UTC)", header[1])
	}
	if _, body, _ := strings.Cut(string(data), "\n\n"); body != generatedBody {
		t.Errorf("generated SQL:\n%s\nwant:\n%s", body, generatedBody)
	}

	t.Run("refuses without curl or jq", func(t *testing.T) {
		for _, missing := range []string{"curl", "jq"} {
			bin := t.TempDir()
			for _, tool := range []string{"bash", "basename", "dirname", "curl", "jq"} {
				if tool == missing {
					continue
				}
				p, err := exec.LookPath(tool)
				if err != nil {
					t.Fatal(err)
				}
				if err := os.Symlink(p, filepath.Join(bin, tool)); err != nil {
					t.Fatal(err)
				}
			}
			target := filepath.Join(t.TempDir(), "up.sql")
			_, stderr, err := runGenerator(t, script, []string{"PATH=" + bin}, "--from", in, "--out", target)
			if err == nil || !strings.Contains(stderr, missing+" is not on PATH") {
				t.Errorf("without %s: %v, %q", missing, err, stderr)
			}
			if _, err := os.Stat(target); err == nil {
				t.Errorf("without %s a file was written", missing)
			}
		}
	})

	t.Run("refuses a malformed exchangeInfo", func(t *testing.T) {
		for name, doc := range map[string]string{
			"no symbols":      `{"symbols": []}`,
			"not JSON":        `{"symbols": [`,
			"empty code":      `{"symbols": [{"baseAsset": "", "quoteAsset": "AAA"}]}`,
			"code not string": `{"symbols": [{"baseAsset": 1, "quoteAsset": "AAA"}]}`,
			"control code":    `{"symbols": [{"baseAsset": "A\u0001", "quoteAsset": "AAA"}]}`,
		} {
			bad, target := filepath.Join(t.TempDir(), "bad.json"), filepath.Join(t.TempDir(), "up.sql")
			if err := os.WriteFile(bad, []byte(doc), 0o644); err != nil {
				t.Fatal(err)
			}
			if _, _, err := runGenerator(t, script, nil, "--from", bad, "--out", target); err == nil {
				t.Errorf("%s: accepted", name)
			}
			if _, err := os.Stat(target); err == nil {
				t.Errorf("%s: a file was written", name)
			}
		}
	})

	t.Run("applies to the database", func(t *testing.T) {
		owner := testdb.Open(t)
		testdb.Clean(t)
		tx, err := owner.Begin(ctx)
		if err != nil {
			t.Fatal(err)
		}
		defer func() { _ = tx.Rollback(ctx) }()
		if _, err := tx.Exec(ctx, `DELETE FROM asset_aliases WHERE source_id = (SELECT id FROM sources WHERE code = 'binance');
			DELETE FROM sources WHERE code = 'binance'`); err != nil {
			t.Fatal(err)
		}
		if _, err := tx.Exec(ctx, string(data)); err != nil {
			t.Fatalf("the generated SQL does not apply: %v", err)
		}
		var codes []string
		var decimals int
		if err := tx.QueryRow(ctx, `SELECT array_agg(a.native_asset ORDER BY a.native_asset COLLATE "C"),
				count(a.decimals) FROM asset_aliases a JOIN sources s ON s.id = a.source_id
			WHERE s.code = 'binance' AND a.native_asset = a.asset`).Scan(&codes, &decimals); err != nil {
			t.Fatal(err)
		}
		if want := []string{"1KZZZ", "AAA", "BBB", "CCC", "LDO", "Q'Q", "ÄÖ"}; !slices.Equal(codes, want) || decimals != 0 {
			t.Errorf("identity rows %v with %d decimals, want %v without", codes, decimals, want)
		}
	})
}
