// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_credentials.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO api_credentials (tenant_id, kind, key_id, secret_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, key_id, created_at
`

type CreateCredentialParams struct {
	TenantID   uuid.UUID
	Kind       string
	KeyID      string
	SecretHash []byte
}

type CreateCredentialRow struct {
	ID        uuid.UUID
	KeyID     string
	CreatedAt time.Time
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (CreateCredentialRow, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.TenantID,
		arg.Kind,
		arg.KeyID,
		arg.SecretHash,
	)
	var i CreateCredentialRow
	err := row.Scan(&i.ID, &i.KeyID, &i.CreatedAt)
	return i, err
}

const getProcessorCredentialByKeyID = `-- name: GetProcessorCredentialByKeyID :one
SELECT c.id, c.tenant_id, c.secret_hash, c.revoked_at, t.status AS tenant_status
FROM api_credentials c
JOIN tenants t ON t.id = c.tenant_id
WHERE c.key_id = $1 AND c.kind = 'PROCESSOR_BASIC'
`

type GetProcessorCredentialByKeyIDRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SecretHash   []byte
	RevokedAt    *time.Time
	TenantStatus string
}

// Lookup of a Basic username.
func (q *Queries) GetProcessorCredentialByKeyID(ctx context.Context, keyID string) (GetProcessorCredentialByKeyIDRow, error) {
	row := q.db.QueryRow(ctx, getProcessorCredentialByKeyID, keyID)
	var i GetProcessorCredentialByKeyIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SecretHash,
		&i.RevokedAt,
		&i.TenantStatus,
	)
	return i, err
}

const getServiceTokenByKeyID = `-- name: GetServiceTokenByKeyID :one
SELECT c.id, c.tenant_id, c.secret_hash, c.revoked_at, t.status AS tenant_status
FROM api_credentials c
JOIN tenants t ON t.id = c.tenant_id
WHERE c.key_id = $1 AND c.kind = 'SERVICE_TOKEN'
`

type GetServiceTokenByKeyIDRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SecretHash   []byte
	RevokedAt    *time.Time
	TenantStatus string
}

// Lookup for authentication: one query per request.
func (q *Queries) GetServiceTokenByKeyID(ctx context.Context, keyID string) (GetServiceTokenByKeyIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceTokenByKeyID, keyID)
	var i GetServiceTokenByKeyIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SecretHash,
		&i.RevokedAt,
		&i.TenantStatus,
	)
	return i, err
}

const listProcessorCredentials = `-- name: ListProcessorCredentials :many
SELECT c.id, c.key_id, t.name AS tenant_name, c.created_at, c.revoked_at
FROM api_credentials c
JOIN tenants t ON t.id = c.tenant_id
WHERE c.kind = 'PROCESSOR_BASIC'
  AND ($1::uuid IS NULL OR c.tenant_id = $1::uuid)
ORDER BY t.name, c.created_at, c.key_id
`

type ListProcessorCredentialsRow struct {
	ID         uuid.UUID
	KeyID      string
	TenantName string
	CreatedAt  time.Time
	RevokedAt  *time.Time
}

// No secret hash. All tenants when tenant_id is null.
func (q *Queries) ListProcessorCredentials(ctx context.Context, tenantID *uuid.UUID) ([]ListProcessorCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listProcessorCredentials, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProcessorCredentialsRow{}
	for rows.Next() {
		var i ListProcessorCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.TenantName,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceTokens = `-- name: ListServiceTokens :many
SELECT c.id, c.key_id, t.name AS tenant_name, c.created_at, c.revoked_at
FROM api_credentials c
JOIN tenants t ON t.id = c.tenant_id
WHERE c.kind = 'SERVICE_TOKEN'
  AND ($1::uuid IS NULL OR c.tenant_id = $1::uuid)
ORDER BY t.name, c.created_at, c.key_id
`

type ListServiceTokensRow struct {
	ID         uuid.UUID
	KeyID      string
	TenantName string
	CreatedAt  time.Time
	RevokedAt  *time.Time
}

// No secret hash. All tenants when tenant_id is null.
func (q *Queries) ListServiceTokens(ctx context.Context, tenantID *uuid.UUID) ([]ListServiceTokensRow, error) {
	rows, err := q.db.Query(ctx, listServiceTokens, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceTokensRow{}
	for rows.Next() {
		var i ListServiceTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.TenantName,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeProcessorCredential = `-- name: RevokeProcessorCredential :one
UPDATE api_credentials
SET revoked_at = now()
WHERE key_id = $1 AND kind = 'PROCESSOR_BASIC' AND revoked_at IS NULL
RETURNING id, tenant_id
`

type RevokeProcessorCredentialRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

// Revokes a processor credential that is not revoked yet: no row means unknown or already revoked.
func (q *Queries) RevokeProcessorCredential(ctx context.Context, keyID string) (RevokeProcessorCredentialRow, error) {
	row := q.db.QueryRow(ctx, revokeProcessorCredential, keyID)
	var i RevokeProcessorCredentialRow
	err := row.Scan(&i.ID, &i.TenantID)
	return i, err
}

const revokeServiceToken = `-- name: RevokeServiceToken :one
UPDATE api_credentials
SET revoked_at = now()
WHERE key_id = $1 AND kind = 'SERVICE_TOKEN' AND revoked_at IS NULL
RETURNING id, tenant_id
`

type RevokeServiceTokenRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

// Revokes a service token that is not revoked yet: no row means unknown or already revoked.
func (q *Queries) RevokeServiceToken(ctx context.Context, keyID string) (RevokeServiceTokenRow, error) {
	row := q.db.QueryRow(ctx, revokeServiceToken, keyID)
	var i RevokeServiceTokenRow
	err := row.Scan(&i.ID, &i.TenantID)
	return i, err
}
