// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (tenant_id, credential_id, action, object_id, details)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	TenantID     uuid.UUID
	CredentialID *uuid.UUID
	Action       string
	ObjectID     string
	Details      []byte
}

// No RETURNING: cas_server has no SELECT on audit_log.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.TenantID,
		arg.CredentialID,
		arg.Action,
		arg.ObjectID,
		arg.Details,
	)
	return err
}
