// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorizations.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAuthorization = `-- name: GetAuthorization :one

SELECT a.id, a.auth_id, a.status, a.decline_reason, COALESCE(trim_scale(a.fiat_amount)::text, '')::text AS amount, a.fiat_currency,
       a.token, COALESCE(a.token_amount::text, '')::text AS token_amount, COALESCE(trim_scale(a.rate)::text, '')::text AS rate, a.buffer_bps,
       a.debited_amount::text AS debited_amount, a.returned_amount::text AS returned_amount,
       k.card_ref, a.received_at, a.decided_at, COALESCE('0x' || encode(d.tx_hash, 'hex'), '')::text AS tx_hash
FROM authorizations a
LEFT JOIN cards k ON k.id = a.card_id
LEFT JOIN LATERAL (
    SELECT t.tx_hash FROM operator_txs t
    WHERE t.authorization_id = a.id AND t.purpose = 'DEBIT' AND t.tx_hash IS NOT NULL
    ORDER BY t.status IN ('INCLUDED', 'CONFIRMED') DESC, t.created_at DESC
    LIMIT 1
) d ON true
WHERE a.tenant_id = $1 AND a.auth_id = $2
`

type GetAuthorizationParams struct {
	TenantID uuid.UUID
	AuthID   string
}

type GetAuthorizationRow struct {
	ID             uuid.UUID
	AuthID         string
	Status         string
	DeclineReason  *string
	Amount         string
	FiatCurrency   *string
	Token          *string
	TokenAmount    string
	Rate           string
	BufferBps      *int32
	DebitedAmount  string
	ReturnedAmount string
	CardRef        *string
	ReceivedAt     time.Time
	DecidedAt      *time.Time
	TxHash         string
}

// Reads of the authorizations by server (SRS - Core §2.1.1): read-only, role cas_server.
// Decimals without trailing zeros; base units as integer strings; an absent value is the empty string.
// tx_hash (SRS - Card Spend §2.1.4): of the DEBIT row, or of the REFUND rows of a return, that is INCLUDED or
// CONFIRMED; else of the newest such row with a hash; else empty. Read in the same statement, never per row.
func (q *Queries) GetAuthorization(ctx context.Context, arg GetAuthorizationParams) (GetAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, getAuthorization, arg.TenantID, arg.AuthID)
	var i GetAuthorizationRow
	err := row.Scan(
		&i.ID,
		&i.AuthID,
		&i.Status,
		&i.DeclineReason,
		&i.Amount,
		&i.FiatCurrency,
		&i.Token,
		&i.TokenAmount,
		&i.Rate,
		&i.BufferBps,
		&i.DebitedAmount,
		&i.ReturnedAmount,
		&i.CardRef,
		&i.ReceivedAt,
		&i.DecidedAt,
		&i.TxHash,
	)
	return i, err
}

const listAuthorizationEvents = `-- name: ListAuthorizationEvents :many
SELECT to_status, reason, created_at
FROM authorization_events
WHERE authorization_id = $1
ORDER BY id
`

type ListAuthorizationEventsRow struct {
	ToStatus  string
	Reason    *string
	CreatedAt time.Time
}

// The status history in the order of the events.
func (q *Queries) ListAuthorizationEvents(ctx context.Context, authorizationID uuid.UUID) ([]ListAuthorizationEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizationEvents, authorizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorizationEventsRow{}
	for rows.Next() {
		var i ListAuthorizationEventsRow
		if err := rows.Scan(&i.ToStatus, &i.Reason, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorizationReturns = `-- name: ListAuthorizationReturns :many
SELECT r.return_id, r.type, r.status, r.token_amount::text AS token_amount, r.created_at,
       COALESCE('0x' || encode(x.tx_hash, 'hex'), '')::text AS tx_hash
FROM returns r
LEFT JOIN LATERAL (
    SELECT t.tx_hash FROM operator_txs t
    WHERE t.return_row_id = r.id AND t.purpose = 'REFUND' AND t.tx_hash IS NOT NULL
    ORDER BY t.status IN ('INCLUDED', 'CONFIRMED') DESC, t.created_at DESC
    LIMIT 1
) x ON true
WHERE r.authorization_id = $1
ORDER BY r.created_at, r.id
`

type ListAuthorizationReturnsRow struct {
	ReturnID    string
	Type        string
	Status      string
	TokenAmount string
	CreatedAt   time.Time
	TxHash      string
}

func (q *Queries) ListAuthorizationReturns(ctx context.Context, authorizationID uuid.UUID) ([]ListAuthorizationReturnsRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizationReturns, authorizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorizationReturnsRow{}
	for rows.Next() {
		var i ListAuthorizationReturnsRow
		if err := rows.Scan(
			&i.ReturnID,
			&i.Type,
			&i.Status,
			&i.TokenAmount,
			&i.CreatedAt,
			&i.TxHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorizationsPage = `-- name: ListAuthorizationsPage :many
SELECT a.id, a.auth_id, a.status, a.decline_reason, COALESCE(trim_scale(a.fiat_amount)::text, '')::text AS amount, a.fiat_currency,
       a.token, COALESCE(a.token_amount::text, '')::text AS token_amount, COALESCE(trim_scale(a.rate)::text, '')::text AS rate, a.buffer_bps,
       a.debited_amount::text AS debited_amount, a.returned_amount::text AS returned_amount,
       k.card_ref, a.received_at, a.decided_at, COALESCE('0x' || encode(d.tx_hash, 'hex'), '')::text AS tx_hash
FROM authorizations a
LEFT JOIN cards k ON k.id = a.card_id
LEFT JOIN LATERAL (
    SELECT t.tx_hash FROM operator_txs t
    WHERE t.authorization_id = a.id AND t.purpose = 'DEBIT' AND t.tx_hash IS NOT NULL
    ORDER BY t.status IN ('INCLUDED', 'CONFIRMED') DESC, t.created_at DESC
    LIMIT 1
) d ON true
WHERE a.tenant_id = $1
  AND ($2::timestamptz IS NULL
       OR a.received_at < $2::timestamptz
       OR (a.received_at = $2::timestamptz AND a.auth_id > $3::text))
  AND ($4::text IS NULL OR k.card_ref = $4::text)
  AND ($5::text IS NULL OR k.owner_ref = $5::text)
  AND ($6::text IS NULL OR a.status = $6::text)
  AND ($7::timestamptz IS NULL OR a.received_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR a.received_at < $8::timestamptz)
ORDER BY a.received_at DESC, a.auth_id
LIMIT $9
`

type ListAuthorizationsPageParams struct {
	TenantID        uuid.UUID
	AfterReceivedAt *time.Time
	AfterAuthID     *string
	CardRef         *string
	OwnerRef        *string
	Status          *string
	ReceivedFrom    *time.Time
	ReceivedTo      *time.Time
	PageLimit       int32
}

type ListAuthorizationsPageRow struct {
	ID             uuid.UUID
	AuthID         string
	Status         string
	DeclineReason  *string
	Amount         string
	FiatCurrency   *string
	Token          *string
	TokenAmount    string
	Rate           string
	BufferBps      *int32
	DebitedAmount  string
	ReturnedAmount string
	CardRef        *string
	ReceivedAt     time.Time
	DecidedAt      *time.Time
	TxHash         string
}

// Order received_at descending, auth_id, after the position (after_received_at, after_auth_id). Filters
// combine with AND; a null filter does not filter. A tombstone has no card: a card or owner filter skips it.
func (q *Queries) ListAuthorizationsPage(ctx context.Context, arg ListAuthorizationsPageParams) ([]ListAuthorizationsPageRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizationsPage,
		arg.TenantID,
		arg.AfterReceivedAt,
		arg.AfterAuthID,
		arg.CardRef,
		arg.OwnerRef,
		arg.Status,
		arg.ReceivedFrom,
		arg.ReceivedTo,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorizationsPageRow{}
	for rows.Next() {
		var i ListAuthorizationsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthID,
			&i.Status,
			&i.DeclineReason,
			&i.Amount,
			&i.FiatCurrency,
			&i.Token,
			&i.TokenAmount,
			&i.Rate,
			&i.BufferBps,
			&i.DebitedAmount,
			&i.ReturnedAmount,
			&i.CardRef,
			&i.ReceivedAt,
			&i.DecidedAt,
			&i.TxHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
