// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const connectionHasCards = `-- name: ConnectionHasCards :one
SELECT EXISTS (SELECT 1 FROM cards WHERE connection_id = $1)
`

// EC-114: any card bound to the connection.
func (q *Queries) ConnectionHasCards(ctx context.Context, connectionID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, connectionHasCards, connectionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCard = `-- name: GetCard :one
SELECT k.id, k.card_ref, k.owner_ref, k.connection_id, c.external_account AS wallet_address, k.status,
       k.daily_limit::text AS daily_limit, k.created_at, k.updated_at
FROM cards k
JOIN connections c ON c.id = k.connection_id
WHERE k.tenant_id = $1 AND k.card_ref = $2
`

type GetCardParams struct {
	TenantID uuid.UUID
	CardRef  string
}

type GetCardRow struct {
	ID            uuid.UUID
	CardRef       string
	OwnerRef      string
	ConnectionID  uuid.UUID
	WalletAddress string
	Status        string
	DailyLimit    string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// One card of a tenant with the address of its wallet. Another tenant's card is no row.
func (q *Queries) GetCard(ctx context.Context, arg GetCardParams) (GetCardRow, error) {
	row := q.db.QueryRow(ctx, getCard, arg.TenantID, arg.CardRef)
	var i GetCardRow
	err := row.Scan(
		&i.ID,
		&i.CardRef,
		&i.OwnerRef,
		&i.ConnectionID,
		&i.WalletAddress,
		&i.Status,
		&i.DailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCard = `-- name: InsertCard :one
INSERT INTO cards (tenant_id, card_ref, owner_ref, connection_id, status, daily_limit, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'ACTIVE',
        $5::text::numeric, $6, $6)
ON CONFLICT (tenant_id, card_ref) DO NOTHING
RETURNING id
`

type InsertCardParams struct {
	TenantID     uuid.UUID
	CardRef      string
	OwnerRef     string
	ConnectionID uuid.UUID
	DailyLimit   string
	Now          time.Time
}

// A second card with the same card_ref in the tenant is no row: the caller compares it with the request.
func (q *Queries) InsertCard(ctx context.Context, arg InsertCardParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCard,
		arg.TenantID,
		arg.CardRef,
		arg.OwnerRef,
		arg.ConnectionID,
		arg.DailyLimit,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCardsPage = `-- name: ListCardsPage :many
SELECT k.id, k.card_ref, k.owner_ref, k.connection_id, c.external_account AS wallet_address, k.status,
       k.daily_limit::text AS daily_limit, k.created_at, k.updated_at
FROM cards k
JOIN connections c ON c.id = k.connection_id
WHERE k.tenant_id = $1
  AND (k.created_at, k.card_ref) > ($2::timestamptz, $3::text)
  AND ($4::text IS NULL OR k.owner_ref = $4::text)
ORDER BY k.created_at, k.card_ref
LIMIT $5
`

type ListCardsPageParams struct {
	TenantID       uuid.UUID
	AfterCreatedAt time.Time
	AfterCardRef   string
	OwnerRef       *string
	PageLimit      int32
}

type ListCardsPageRow struct {
	ID            uuid.UUID
	CardRef       string
	OwnerRef      string
	ConnectionID  uuid.UUID
	WalletAddress string
	Status        string
	DailyLimit    string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// One page in the order created_at, card_ref after the position; a range of cards_tenant_created_idx.
func (q *Queries) ListCardsPage(ctx context.Context, arg ListCardsPageParams) ([]ListCardsPageRow, error) {
	rows, err := q.db.Query(ctx, listCardsPage,
		arg.TenantID,
		arg.AfterCreatedAt,
		arg.AfterCardRef,
		arg.OwnerRef,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCardsPageRow{}
	for rows.Next() {
		var i ListCardsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.CardRef,
			&i.OwnerRef,
			&i.ConnectionID,
			&i.WalletAddress,
			&i.Status,
			&i.DailyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCard = `-- name: LockCard :one
SELECT id, status, daily_limit::text AS daily_limit
FROM cards
WHERE tenant_id = $1 AND card_ref = $2
FOR UPDATE
`

type LockCardParams struct {
	TenantID uuid.UUID
	CardRef  string
}

type LockCardRow struct {
	ID         uuid.UUID
	Status     string
	DailyLimit string
}

// The card row of UpdateCard, locked until the end of the transaction.
func (q *Queries) LockCard(ctx context.Context, arg LockCardParams) (LockCardRow, error) {
	row := q.db.QueryRow(ctx, lockCard, arg.TenantID, arg.CardRef)
	var i LockCardRow
	err := row.Scan(&i.ID, &i.Status, &i.DailyLimit)
	return i, err
}

const updateCard = `-- name: UpdateCard :exec
UPDATE cards
SET daily_limit = $1::text::numeric, status = $2, updated_at = $3
WHERE id = $4
`

type UpdateCardParams struct {
	DailyLimit string
	Status     string
	Now        time.Time
	ID         uuid.UUID
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) error {
	_, err := q.db.Exec(ctx, updateCard,
		arg.DailyLimit,
		arg.Status,
		arg.Now,
		arg.ID,
	)
	return err
}
