// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertConnection = `-- name: InsertConnection :exec
INSERT INTO connections (
    id, tenant_id, owner_ref, source_id, external_account, label, status,
    credentials_enc, kek_version, key_fingerprint, permissions, permissions_checked_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13
)
`

type InsertConnectionParams struct {
	ID                   uuid.UUID
	TenantID             uuid.UUID
	OwnerRef             string
	SourceID             int16
	ExternalAccount      string
	Label                *string
	Status               string
	CredentialsEnc       []byte
	KekVersion           *int16
	KeyFingerprint       *string
	Permissions          []string
	PermissionsCheckedAt *time.Time
	CreatedAt            time.Time
}

// The ID and the times come from the caller. No RETURNING: the caller has every value.
func (q *Queries) InsertConnection(ctx context.Context, arg InsertConnectionParams) error {
	_, err := q.db.Exec(ctx, insertConnection,
		arg.ID,
		arg.TenantID,
		arg.OwnerRef,
		arg.SourceID,
		arg.ExternalAccount,
		arg.Label,
		arg.Status,
		arg.CredentialsEnc,
		arg.KekVersion,
		arg.KeyFingerprint,
		arg.Permissions,
		arg.PermissionsCheckedAt,
		arg.CreatedAt,
	)
	return err
}
