// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debits.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const finishSubmittedAuthorization = `-- name: FinishSubmittedAuthorization :execrows
UPDATE authorizations
SET status         = $1,
    decline_reason = $2,
    debited_amount = CASE WHEN $3::bool THEN token_amount ELSE debited_amount END,
    decided_at     = $4
WHERE id = $5 AND status = 'DEBIT_SUBMITTED'
`

type FinishSubmittedAuthorizationParams struct {
	Status        string
	DeclineReason *string
	Debited       bool
	DecidedAt     *time.Time
	ID            uuid.UUID
}

// Steps 12 - 13: DEBIT_SUBMITTED -> APPROVED, DECLINED or TIMED_OUT. debited_amount is the token amount only
// for an approval.
func (q *Queries) FinishSubmittedAuthorization(ctx context.Context, arg FinishSubmittedAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishSubmittedAuthorization,
		arg.Status,
		arg.DeclineReason,
		arg.Debited,
		arg.DecidedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOperatorTxOutcome = `-- name: SetOperatorTxOutcome :exec
UPDATE operator_txs
SET status = $1, block_number = $2, block_hash = $3
WHERE id = $4
`

type SetOperatorTxOutcomeParams struct {
	Status      string
	BlockNumber *int64
	BlockHash   []byte
	ID          uuid.UUID
}

// Step 12: INCLUDED or REVERTED. block_number and block_hash come only from a sealed receipt: null for a
// preconfirmed one (UC-3 row 10).
func (q *Queries) SetOperatorTxOutcome(ctx context.Context, arg SetOperatorTxOutcomeParams) error {
	_, err := q.db.Exec(ctx, setOperatorTxOutcome,
		arg.Status,
		arg.BlockNumber,
		arg.BlockHash,
		arg.ID,
	)
	return err
}

const submitAuthorization = `-- name: SubmitAuthorization :execrows

UPDATE authorizations
SET status = 'DEBIT_SUBMITTED', valid_until = $1
WHERE id = $2 AND status = 'RECEIVED'
`

type SubmitAuthorizationParams struct {
	ValidUntil *time.Time
	ID         uuid.UUID
}

// Debit path of card-auth (SRS - Card Spend UC-1 steps 10 - 13), role cas_card_auth.
// Step 10: RECEIVED -> DEBIT_SUBMITTED with the on-chain expiry of the debit.
func (q *Queries) SubmitAuthorization(ctx context.Context, arg SubmitAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, submitAuthorization, arg.ValidUntil, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
