// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const declineReceivedAuthorization = `-- name: DeclineReceivedAuthorization :execrows
UPDATE authorizations
SET status = 'DECLINED', decline_reason = $1, decided_at = $2
WHERE id = $3 AND status = 'RECEIVED'
`

type DeclineReceivedAuthorizationParams struct {
	DeclineReason *string
	DecidedAt     *time.Time
	ID            uuid.UUID
}

// A decline of steps 5 - 9: RECEIVED -> DECLINED. No row: the authorization is no longer RECEIVED.
func (q *Queries) DeclineReceivedAuthorization(ctx context.Context, arg DeclineReceivedAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, declineReceivedAuthorization, arg.DeclineReason, arg.DecidedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCardDaySpend = `-- name: GetCardDaySpend :one
SELECT COALESCE(sum(token_amount), 0)::text AS spent
FROM authorizations
WHERE card_id = $1
  AND status IN ('APPROVED', 'DEBIT_CONFIRMED', 'DEBIT_LOST')
  AND received_at >= $2 AND received_at < $3
`

type GetCardDaySpendParams struct {
	CardID   *uuid.UUID
	DayStart time.Time
	DayEnd   time.Time
}

// Step 8: token amounts of the card's approved authorizations received in [day_start, day_end).
func (q *Queries) GetCardDaySpend(ctx context.Context, arg GetCardDaySpendParams) (string, error) {
	row := q.db.QueryRow(ctx, getCardDaySpend, arg.CardID, arg.DayStart, arg.DayEnd)
	var spent string
	err := row.Scan(&spent)
	return spent, err
}

const getCardForDecision = `-- name: GetCardForDecision :one
SELECT k.id, k.status, k.daily_limit::text AS daily_limit, c.external_account AS wallet_address,
       COALESCE((s.config ->> 'chain_id')::bigint, 0)::bigint AS chain_id
FROM cards k
JOIN connections c ON c.id = k.connection_id
JOIN sources s ON s.id = c.source_id
WHERE k.tenant_id = $1 AND k.card_ref = $2
`

type GetCardForDecisionParams struct {
	TenantID uuid.UUID
	CardRef  string
}

type GetCardForDecisionRow struct {
	ID            uuid.UUID
	Status        string
	DailyLimit    string
	WalletAddress string
	ChainID       int64
}

// Step 6: the card of the tenant, its wallet and the chain of the wallet's connection.
func (q *Queries) GetCardForDecision(ctx context.Context, arg GetCardForDecisionParams) (GetCardForDecisionRow, error) {
	row := q.db.QueryRow(ctx, getCardForDecision, arg.TenantID, arg.CardRef)
	var i GetCardForDecisionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.DailyLimit,
		&i.WalletAddress,
		&i.ChainID,
	)
	return i, err
}

const getDecisionState = `-- name: GetDecisionState :one

SELECT a.id, a.status, a.decline_reason, a.request_hash, a.token,
       COALESCE(a.token_amount::text, '')::text AS token_amount, COALESCE(trim_scale(a.rate)::text, '')::text AS rate,
       a.buffer_bps, COALESCE('0x' || encode(d.tx_hash, 'hex'), '')::text AS tx_hash
FROM authorizations a
LEFT JOIN LATERAL (
    SELECT t.tx_hash FROM operator_txs t
    WHERE t.authorization_id = a.id AND t.purpose = 'DEBIT' AND t.tx_hash IS NOT NULL
    ORDER BY t.status IN ('INCLUDED', 'CONFIRMED') DESC, t.created_at DESC
    LIMIT 1
) d ON true
WHERE a.tenant_id = $1 AND a.auth_id = $2
`

type GetDecisionStateParams struct {
	TenantID uuid.UUID
	AuthID   string
}

type GetDecisionStateRow struct {
	ID            uuid.UUID
	Status        string
	DeclineReason *string
	RequestHash   []byte
	Token         *string
	TokenAmount   string
	Rate          string
	BufferBps     *int32
	TxHash        string
}

// Decision path of card-auth (SRS - Card Spend UC-1 steps 3 - 9), role cas_card_auth.
// Decimals are passed and read as text: no float between the service and the database.
// Step 3: an authorization of the tenant with what a repeated request needs. A tombstone has no request_hash.
// tx_hash by the rule of SRS - Card Spend §2.1.4.
func (q *Queries) GetDecisionState(ctx context.Context, arg GetDecisionStateParams) (GetDecisionStateRow, error) {
	row := q.db.QueryRow(ctx, getDecisionState, arg.TenantID, arg.AuthID)
	var i GetDecisionStateRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.DeclineReason,
		&i.RequestHash,
		&i.Token,
		&i.TokenAmount,
		&i.Rate,
		&i.BufferBps,
		&i.TxHash,
	)
	return i, err
}

const getDecisionStateByID = `-- name: GetDecisionStateByID :one
SELECT a.id, a.status, a.decline_reason, a.request_hash, a.token,
       COALESCE(a.token_amount::text, '')::text AS token_amount, COALESCE(trim_scale(a.rate)::text, '')::text AS rate,
       a.buffer_bps, COALESCE('0x' || encode(d.tx_hash, 'hex'), '')::text AS tx_hash
FROM authorizations a
LEFT JOIN LATERAL (
    SELECT t.tx_hash FROM operator_txs t
    WHERE t.authorization_id = a.id AND t.purpose = 'DEBIT' AND t.tx_hash IS NOT NULL
    ORDER BY t.status IN ('INCLUDED', 'CONFIRMED') DESC, t.created_at DESC
    LIMIT 1
) d ON true
WHERE a.id = $1
`

type GetDecisionStateByIDRow struct {
	ID            uuid.UUID
	Status        string
	DeclineReason *string
	RequestHash   []byte
	Token         *string
	TokenAmount   string
	Rate          string
	BufferBps     *int32
	TxHash        string
}

// GetDecisionState by the primary key: the state of an authorization that left RECEIVED without the engine.
func (q *Queries) GetDecisionStateByID(ctx context.Context, id uuid.UUID) (GetDecisionStateByIDRow, error) {
	row := q.db.QueryRow(ctx, getDecisionStateByID, id)
	var i GetDecisionStateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.DeclineReason,
		&i.RequestHash,
		&i.Token,
		&i.TokenAmount,
		&i.Rate,
		&i.BufferBps,
		&i.TxHash,
	)
	return i, err
}

const insertAuthorizationEvent = `-- name: InsertAuthorizationEvent :exec
INSERT INTO authorization_events (authorization_id, from_status, to_status, reason, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuthorizationEventParams struct {
	AuthorizationID uuid.UUID
	FromStatus      *string
	ToStatus        string
	Reason          *string
	CreatedAt       time.Time
}

// One row per status change; from_status is null for the first.
func (q *Queries) InsertAuthorizationEvent(ctx context.Context, arg InsertAuthorizationEventParams) error {
	_, err := q.db.Exec(ctx, insertAuthorizationEvent,
		arg.AuthorizationID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const insertReceivedAuthorization = `-- name: InsertReceivedAuthorization :one
INSERT INTO authorizations (tenant_id, auth_id, chain_auth_id, request_hash, fiat_amount, fiat_currency, merchant,
                            status, received_at, deadline_at)
VALUES ($1, $2, $3, $4,
        $5::text::numeric, $6, $7, 'RECEIVED',
        $8, $9)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertReceivedAuthorizationParams struct {
	TenantID     uuid.UUID
	AuthID       string
	ChainAuthID  []byte
	RequestHash  []byte
	FiatAmount   string
	FiatCurrency *string
	Merchant     []byte
	ReceivedAt   time.Time
	DeadlineAt   *time.Time
}

// Step 4. A concurrent insert of the same auth_id is no row: the caller reads the winner's row. No conflict target:
// chain_auth_id is unique too and derived from (tenant_id, auth_id), so a racing insert may meet either index first.
func (q *Queries) InsertReceivedAuthorization(ctx context.Context, arg InsertReceivedAuthorizationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertReceivedAuthorization,
		arg.TenantID,
		arg.AuthID,
		arg.ChainAuthID,
		arg.RequestHash,
		arg.FiatAmount,
		arg.FiatCurrency,
		arg.Merchant,
		arg.ReceivedAt,
		arg.DeadlineAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setAuthorizationFacts = `-- name: SetAuthorizationFacts :execrows
UPDATE authorizations
SET card_id        = $1,
    wallet_address = $2,
    chain_id       = $3,
    rate           = $4::text::numeric,
    buffer_bps     = $5,
    token          = $6,
    token_amount   = $7::text::numeric
WHERE id = $8 AND status = 'RECEIVED'
`

type SetAuthorizationFactsParams struct {
	CardID        *uuid.UUID
	WalletAddress []byte
	ChainID       *int64
	Rate          *string
	BufferBps     *int32
	Token         *string
	TokenAmount   *string
	ID            uuid.UUID
}

// The card of step 6 and the quote of step 7, while the authorization is RECEIVED. A value not known yet is null.
func (q *Queries) SetAuthorizationFacts(ctx context.Context, arg SetAuthorizationFactsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAuthorizationFacts,
		arg.CardID,
		arg.WalletAddress,
		arg.ChainID,
		arg.Rate,
		arg.BufferBps,
		arg.Token,
		arg.TokenAmount,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
