// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inspect.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const inspectAudit = `-- name: InspectAudit :many
SELECT action, count(*)::bigint AS row_count,
    bool_or(coalesce(jsonb_path_exists(details, '$.**.uid'), false))::boolean AS has_uid
FROM audit_log
WHERE object_id = $1
GROUP BY action
ORDER BY action
`

type InspectAuditRow struct {
	Action   string
	RowCount int64
	HasUid   bool
}

// The audit rows of a connection per action, and whether any of their details holds a member uid at any depth.
func (q *Queries) InspectAudit(ctx context.Context, objectID string) ([]InspectAuditRow, error) {
	rows, err := q.db.Query(ctx, inspectAudit, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InspectAuditRow{}
	for rows.Next() {
		var i InspectAuditRow
		if err := rows.Scan(&i.Action, &i.RowCount, &i.HasUid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inspectConnection = `-- name: InspectConnection :one
SELECT status, permissions, (credentials_enc IS NOT NULL)::boolean AS has_ciphertext
FROM connections
WHERE id = $1
`

type InspectConnectionRow struct {
	Status        string
	Permissions   []string
	HasCiphertext bool
}

// The state of a connection for casctl connection inspect (X1 D-45): never the account identity or the fingerprint.
func (q *Queries) InspectConnection(ctx context.Context, id uuid.UUID) (InspectConnectionRow, error) {
	row := q.db.QueryRow(ctx, inspectConnection, id)
	var i InspectConnectionRow
	err := row.Scan(&i.Status, &i.Permissions, &i.HasCiphertext)
	return i, err
}

const inspectIPRestricted = `-- name: InspectIPRestricted :one
SELECT coalesce((details -> 'ip_restricted')::text, '')::text AS ip_restricted
FROM audit_log
WHERE object_id = $1 AND action = 'CONNECTION_CREATED'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// ip_restricted of the latest CONNECTION_CREATED row of a connection (X1 D-2); empty when it is not recorded.
func (q *Queries) InspectIPRestricted(ctx context.Context, objectID string) (string, error) {
	row := q.db.QueryRow(ctx, inspectIPRestricted, objectID)
	var ip_restricted string
	err := row.Scan(&ip_restricted)
	return ip_restricted, err
}

const inspectResiduals = `-- name: InspectResiduals :one
SELECT
    (SELECT count(*) FROM balance_snapshots s WHERE s.connection_id = $1::uuid)::bigint AS snapshots,
    (SELECT count(*) FROM snapshot_balances b JOIN balance_snapshots s ON s.id = b.snapshot_id
        WHERE s.connection_id = $1::uuid)::bigint AS balance_rows,
    (SELECT count(*) FROM sync_cursors c WHERE c.connection_id = $1::uuid)::bigint AS cursors,
    (SELECT count(*) FROM ledger_entries e WHERE e.connection_id = $1::uuid)::bigint AS ledger_entries
`

type InspectResidualsRow struct {
	Snapshots     int64
	BalanceRows   int64
	Cursors       int64
	LedgerEntries int64
}

// What is stored for a connection ID, whether the connection exists or was deleted.
func (q *Queries) InspectResiduals(ctx context.Context, connectionID uuid.UUID) (InspectResidualsRow, error) {
	row := q.db.QueryRow(ctx, inspectResiduals, connectionID)
	var i InspectResidualsRow
	err := row.Scan(
		&i.Snapshots,
		&i.BalanceRows,
		&i.Cursors,
		&i.LedgerEntries,
	)
	return i, err
}
