// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertBalanceSnapshot = `-- name: InsertBalanceSnapshot :one
INSERT INTO balance_snapshots (connection_id, taken_at, created_at)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertBalanceSnapshotParams struct {
	ConnectionID uuid.UUID
	TakenAt      time.Time
	CreatedAt    time.Time
}

func (q *Queries) InsertBalanceSnapshot(ctx context.Context, arg InsertBalanceSnapshotParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertBalanceSnapshot, arg.ConnectionID, arg.TakenAt, arg.CreatedAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :execrows
INSERT INTO ledger_entries (
    tenant_id, connection_id, stream, external_id, leg, group_id, type, direction,
    asset, native_asset, amount, occurred_at, raw
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    ($11::text)::numeric, $12, $13
)
ON CONFLICT (connection_id, stream, external_id, leg) DO NOTHING
`

type InsertLedgerEntryParams struct {
	TenantID     uuid.UUID
	ConnectionID uuid.UUID
	Stream       string
	ExternalID   string
	Leg          string
	GroupID      string
	Type         string
	Direction    string
	Asset        string
	NativeAsset  string
	Amount       string
	OccurredAt   time.Time
	Raw          []byte
}

// 0 rows: the idempotency key exists; the entry is skipped and never updated.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.TenantID,
		arg.ConnectionID,
		arg.Stream,
		arg.ExternalID,
		arg.Leg,
		arg.GroupID,
		arg.Type,
		arg.Direction,
		arg.Asset,
		arg.NativeAsset,
		arg.Amount,
		arg.OccurredAt,
		arg.Raw,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSnapshotBalance = `-- name: InsertSnapshotBalance :exec
INSERT INTO snapshot_balances (snapshot_id, account_type, native_asset, asset, free, locked)
VALUES (
    $1, $2, $3, $4,
    ($5::text)::numeric, ($6::text)::numeric
)
`

type InsertSnapshotBalanceParams struct {
	SnapshotID  uuid.UUID
	AccountType string
	NativeAsset string
	Asset       string
	Free        string
	Locked      string
}

func (q *Queries) InsertSnapshotBalance(ctx context.Context, arg InsertSnapshotBalanceParams) error {
	_, err := q.db.Exec(ctx, insertSnapshotBalance,
		arg.SnapshotID,
		arg.AccountType,
		arg.NativeAsset,
		arg.Asset,
		arg.Free,
		arg.Locked,
	)
	return err
}

const listAssetAliases = `-- name: ListAssetAliases :many
SELECT native_asset, asset
FROM asset_aliases
WHERE source_id = $1 AND native_asset = ANY($2::text[])
`

type ListAssetAliasesParams struct {
	SourceID     int16
	NativeAssets []string
}

type ListAssetAliasesRow struct {
	NativeAsset string
	Asset       string
}

func (q *Queries) ListAssetAliases(ctx context.Context, arg ListAssetAliasesParams) ([]ListAssetAliasesRow, error) {
	rows, err := q.db.Query(ctx, listAssetAliases, arg.SourceID, arg.NativeAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetAliasesRow{}
	for rows.Next() {
		var i ListAssetAliasesRow
		if err := rows.Scan(&i.NativeAsset, &i.Asset); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConnectionForWrite = `-- name: LockConnectionForWrite :one
SELECT tenant_id, source_id
FROM connections
WHERE id = $1
FOR SHARE
`

type LockConnectionForWriteRow struct {
	TenantID uuid.UUID
	SourceID int16
}

// Shared lock: a delete of the connection waits for this transaction. No row: the connection is gone.
func (q *Queries) LockConnectionForWrite(ctx context.Context, id uuid.UUID) (LockConnectionForWriteRow, error) {
	row := q.db.QueryRow(ctx, lockConnectionForWrite, id)
	var i LockConnectionForWriteRow
	err := row.Scan(&i.TenantID, &i.SourceID)
	return i, err
}

const lockLedgerWriter = `-- name: LockLedgerWriter :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// The single writer of ledger entries: seq order equals commit order (FR-114). Held to the end of the transaction.
func (q *Queries) LockLedgerWriter(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, lockLedgerWriter, key)
	return err
}

const updateStreamCursor = `-- name: UpdateStreamCursor :execrows
UPDATE sync_cursors
SET cursor = $1, mode = $2
WHERE connection_id = $3 AND stream = $4
`

type UpdateStreamCursorParams struct {
	Cursor       []byte
	Mode         string
	ConnectionID uuid.UUID
	Stream       string
}

func (q *Queries) UpdateStreamCursor(ctx context.Context, arg UpdateStreamCursorParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStreamCursor,
		arg.Cursor,
		arg.Mode,
		arg.ConnectionID,
		arg.Stream,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
