// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiCredential struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Kind       string
	KeyID      string
	SecretHash []byte
	CreatedAt  time.Time
	RevokedAt  *time.Time
}

type AssetAlias struct {
	SourceID    int16
	NativeAsset string
	Asset       string
	Decimals    *int16
}

type AuditLog struct {
	ID           int64
	TenantID     uuid.UUID
	CredentialID *uuid.UUID
	Action       string
	ObjectID     string
	Details      []byte
	CreatedAt    time.Time
}

type BalanceSnapshot struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	TakenAt      time.Time
	CreatedAt    time.Time
}

type Connection struct {
	ID                   uuid.UUID
	TenantID             uuid.UUID
	OwnerRef             string
	SourceID             int16
	ExternalAccount      string
	Label                *string
	Status               string
	CredentialsEnc       []byte
	KekVersion           *int16
	KeyFingerprint       *string
	Permissions          []string
	PermissionsCheckedAt *time.Time
	LastManualSyncAt     *time.Time
	CreatedAt            time.Time
}

type LedgerEntry struct {
	Seq          int64
	TenantID     uuid.UUID
	ConnectionID uuid.UUID
	Stream       string
	ExternalID   string
	Leg          string
	GroupID      string
	Type         string
	Direction    string
	Asset        string
	NativeAsset  string
	Amount       pgtype.Numeric
	OccurredAt   time.Time
	Raw          []byte
	CreatedAt    time.Time
}

type SnapshotBalance struct {
	SnapshotID  uuid.UUID
	AccountType string
	NativeAsset string
	Asset       string
	Free        pgtype.Numeric
	Locked      pgtype.Numeric
}

type Source struct {
	ID      int16
	Code    string
	Kind    string
	Enabled bool
	Config  []byte
}

type SyncCursor struct {
	ConnectionID        uuid.UUID
	Stream              string
	Mode                string
	Cursor              []byte
	NextRunAt           time.Time
	LastSuccessAt       *time.Time
	LastError           *string
	ConsecutiveFailures int32
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	Status    string
	CreatedAt time.Time
}
