// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiCredential struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Kind       string
	KeyID      string
	SecretHash []byte
	CreatedAt  time.Time
	RevokedAt  *time.Time
}

type AssetAlias struct {
	SourceID    int16
	NativeAsset string
	Asset       string
	Decimals    *int16
}

type AuditLog struct {
	ID           int64
	TenantID     uuid.UUID
	CredentialID *uuid.UUID
	Action       string
	ObjectID     string
	Details      []byte
	CreatedAt    time.Time
}

type Authorization struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	AuthID         string
	ChainAuthID    []byte
	ParentAuthID   *string
	CardID         *uuid.UUID
	RequestHash    []byte
	FiatAmount     pgtype.Numeric
	FiatCurrency   *string
	Rate           pgtype.Numeric
	BufferBps      *int32
	Token          *string
	TokenAmount    pgtype.Numeric
	DebitedAmount  pgtype.Numeric
	ReturnedAmount pgtype.Numeric
	WalletAddress  []byte
	ChainID        *int64
	Status         string
	DeclineReason  *string
	Merchant       []byte
	ReceivedAt     time.Time
	DeadlineAt     *time.Time
	ValidUntil     *time.Time
	DecidedAt      *time.Time
}

type AuthorizationEvent struct {
	ID              int64
	AuthorizationID uuid.UUID
	FromStatus      *string
	ToStatus        string
	Reason          *string
	Details         []byte
	CreatedAt       time.Time
}

type BalanceCheckpoint struct {
	ConnectionID uuid.UUID
	NativeAsset  string
	Asset        string
	BlockNumber  *int64
	BlockHash    *string
	TakenAt      time.Time
	Balance      pgtype.Numeric
	LedgerTotal  pgtype.Numeric
	Gap          pgtype.Numeric
	CheckedAt    time.Time
}

type BalanceSnapshot struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	TakenAt      time.Time
	CreatedAt    time.Time
}

type Card struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	CardRef      string
	OwnerRef     string
	ConnectionID uuid.UUID
	Status       string
	DailyLimit   pgtype.Numeric
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Connection struct {
	ID                   uuid.UUID
	TenantID             uuid.UUID
	OwnerRef             string
	SourceID             int16
	ExternalAccount      string
	Label                *string
	Status               string
	CredentialsEnc       []byte
	KekVersion           *int16
	KeyFingerprint       *string
	Permissions          []string
	PermissionsCheckedAt *time.Time
	LastManualSyncAt     *time.Time
	CreatedAt            time.Time
}

type LedgerEntry struct {
	Seq          int64
	TenantID     uuid.UUID
	ConnectionID uuid.UUID
	Stream       string
	ExternalID   string
	Leg          string
	GroupID      string
	Type         string
	Direction    string
	Asset        string
	NativeAsset  string
	Amount       pgtype.Numeric
	OccurredAt   time.Time
	Raw          []byte
	CreatedAt    time.Time
}

type OperatorAccount struct {
	ChainID   int64
	Address   []byte
	NextNonce int64
}

type OperatorTx struct {
	ID              uuid.UUID
	ChainID         int64
	OperatorAddress []byte
	Nonce           int64
	Purpose         string
	AuthorizationID *uuid.UUID
	ReturnRowID     *uuid.UUID
	TxHash          []byte
	ReplacedHashes  [][]byte
	Status          string
	BlockNumber     *int64
	BlockHash       []byte
	CreatedAt       time.Time
}

type ReconciliationRun struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	SourceID   int16
	PeriodFrom time.Time
	PeriodTo   time.Time
	ToBlock    int64
	Totals     []byte
	Mismatches []byte
	CreatedAt  time.Time
}

type Return struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	AuthorizationID uuid.UUID
	ReturnID        string
	ChainRefundID   []byte
	Type            string
	RequestHash     []byte
	FiatAmount      pgtype.Numeric
	TokenAmount     pgtype.Numeric
	Status          string
	Attempts        int32
	CreatedAt       time.Time
}

type SnapshotBalance struct {
	SnapshotID  uuid.UUID
	AccountType string
	NativeAsset string
	Asset       string
	Free        pgtype.Numeric
	Locked      pgtype.Numeric
}

type Source struct {
	ID      int16
	Code    string
	Kind    string
	Enabled bool
	Config  []byte
}

type SyncCursor struct {
	ConnectionID        uuid.UUID
	Stream              string
	Mode                string
	Cursor              []byte
	NextRunAt           time.Time
	LastSuccessAt       *time.Time
	LastError           *string
	ConsecutiveFailures int32
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	Status    string
	CreatedAt time.Time
}
