// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operator_txs.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertPlannedOperatorTx = `-- name: InsertPlannedOperatorTx :one

INSERT INTO operator_txs (chain_id, operator_address, nonce, purpose, authorization_id, return_row_id, status, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, 'PLANNED', $7)
RETURNING id
`

type InsertPlannedOperatorTxParams struct {
	ChainID         int64
	OperatorAddress []byte
	Nonce           int64
	Purpose         string
	AuthorizationID *uuid.UUID
	ReturnRowID     *uuid.UUID
	CreatedAt       time.Time
}

// Operator queue of card-auth (SRS - Card Spend §2.4 operator_txs, ADR-10): one nonce sequence for debits and
// refunds, role cas_card_auth.
// The intent of an operator transaction with its reserved nonce, written before anything is sent (FR-5).
func (q *Queries) InsertPlannedOperatorTx(ctx context.Context, arg InsertPlannedOperatorTxParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPlannedOperatorTx,
		arg.ChainID,
		arg.OperatorAddress,
		arg.Nonce,
		arg.Purpose,
		arg.AuthorizationID,
		arg.ReturnRowID,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markOperatorTxSent = `-- name: MarkOperatorTxSent :execrows
UPDATE operator_txs
SET tx_hash = $1, status = 'SENT'
WHERE id = $2 AND status = 'PLANNED'
`

type MarkOperatorTxSentParams struct {
	TxHash []byte
	ID     uuid.UUID
}

// The hash of the signed transaction, stored before it is sent.
func (q *Queries) MarkOperatorTxSent(ctx context.Context, arg MarkOperatorTxSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOperatorTxSent, arg.TxHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replaceOperatorTxHash = `-- name: ReplaceOperatorTxHash :execrows
UPDATE operator_txs
SET replaced_hashes = array_append(replaced_hashes, tx_hash), tx_hash = $1, status = 'SENT'
WHERE id = $2 AND tx_hash = $3 AND status = 'SENT'
`

type ReplaceOperatorTxHashParams struct {
	TxHash  []byte
	ID      uuid.UUID
	OldHash []byte
}

// A new transaction in the same nonce slot: the old hash moves to replaced_hashes, the new one is current.
func (q *Queries) ReplaceOperatorTxHash(ctx context.Context, arg ReplaceOperatorTxHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceOperatorTxHash, arg.TxHash, arg.ID, arg.OldHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
