// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operator_txs.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertPlannedOperatorTx = `-- name: InsertPlannedOperatorTx :one

INSERT INTO operator_txs (chain_id, operator_address, nonce, purpose, authorization_id, return_row_id, status, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, 'PLANNED', $7)
RETURNING id
`

type InsertPlannedOperatorTxParams struct {
	ChainID         int64
	OperatorAddress []byte
	Nonce           int64
	Purpose         string
	AuthorizationID *uuid.UUID
	ReturnRowID     *uuid.UUID
	CreatedAt       time.Time
}

// Operator queue of card-auth (SRS - Card Spend §2.4 operator_txs, ADR-10): one nonce sequence for debits and
// refunds, role cas_card_auth.
// The intent of an operator transaction with its reserved nonce, written before anything is sent (FR-5).
func (q *Queries) InsertPlannedOperatorTx(ctx context.Context, arg InsertPlannedOperatorTxParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPlannedOperatorTx,
		arg.ChainID,
		arg.OperatorAddress,
		arg.Nonce,
		arg.Purpose,
		arg.AuthorizationID,
		arg.ReturnRowID,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listUnminedOperatorTxs = `-- name: ListUnminedOperatorTxs :many
SELECT t.id, t.purpose, t.nonce, t.status, t.tx_hash, t.replaced_hashes, t.created_at, t.authorization_id, t.return_row_id,
       a.valid_until, a.status AS authorization_status, a.chain_auth_id, a.wallet_address,
       COALESCE(a.token_amount::text, '')::text AS token_amount,
       r.chain_refund_id, COALESCE(r.token_amount::text, '')::text AS refund_amount, ra.chain_auth_id AS refund_auth_id
FROM operator_txs t
LEFT JOIN authorizations a ON a.id = t.authorization_id
LEFT JOIN returns r ON r.id = t.return_row_id
LEFT JOIN authorizations ra ON ra.id = r.authorization_id
WHERE t.chain_id = $1 AND t.operator_address = $2
  AND (t.status = 'SENT' OR (t.status = 'PLANNED' AND t.purpose = 'DEBIT'))
ORDER BY t.nonce
`

type ListUnminedOperatorTxsParams struct {
	ChainID         int64
	OperatorAddress []byte
}

type ListUnminedOperatorTxsRow struct {
	ID                  uuid.UUID
	Purpose             string
	Nonce               int64
	Status              string
	TxHash              []byte
	ReplacedHashes      [][]byte
	CreatedAt           time.Time
	AuthorizationID     *uuid.UUID
	ReturnRowID         *uuid.UUID
	ValidUntil          *time.Time
	AuthorizationStatus *string
	ChainAuthID         []byte
	WalletAddress       []byte
	TokenAmount         string
	ChainRefundID       []byte
	RefundAmount        string
	RefundAuthID        []byte
}

// Tracker, rows 7 - 9: every operator transaction of this chain and operator not mined yet, with what a replacement
// or a release needs. Rows of another chain or another operator key are never touched.
func (q *Queries) ListUnminedOperatorTxs(ctx context.Context, arg ListUnminedOperatorTxsParams) ([]ListUnminedOperatorTxsRow, error) {
	rows, err := q.db.Query(ctx, listUnminedOperatorTxs, arg.ChainID, arg.OperatorAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnminedOperatorTxsRow{}
	for rows.Next() {
		var i ListUnminedOperatorTxsRow
		if err := rows.Scan(
			&i.ID,
			&i.Purpose,
			&i.Nonce,
			&i.Status,
			&i.TxHash,
			&i.ReplacedHashes,
			&i.CreatedAt,
			&i.AuthorizationID,
			&i.ReturnRowID,
			&i.ValidUntil,
			&i.AuthorizationStatus,
			&i.ChainAuthID,
			&i.WalletAddress,
			&i.TokenAmount,
			&i.ChainRefundID,
			&i.RefundAmount,
			&i.RefundAuthID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOperatorTxSent = `-- name: MarkOperatorTxSent :execrows
UPDATE operator_txs
SET tx_hash = $1, status = 'SENT', purpose = $2
WHERE id = $3 AND status = 'PLANNED'
`

type MarkOperatorTxSentParams struct {
	TxHash  []byte
	Purpose string
	ID      uuid.UUID
}

// The hash of the signed transaction, stored before it is sent. purpose is RELEASE when a debit slot is released.
func (q *Queries) MarkOperatorTxSent(ctx context.Context, arg MarkOperatorTxSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOperatorTxSent, arg.TxHash, arg.Purpose, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const oldestUnminedOperatorTx = `-- name: OldestUnminedOperatorTx :one
SELECT COALESCE(min(created_at), 'epoch'::timestamptz)::timestamptz AS oldest
FROM operator_txs
WHERE chain_id = $1 AND operator_address = $2 AND status IN ('PLANNED', 'SENT')
`

type OldestUnminedOperatorTxParams struct {
	ChainID         int64
	OperatorAddress []byte
}

// operator_tx_pending_seconds (SRS - Card Spend §2.5.1): the created_at of the oldest operator transaction not mined.
func (q *Queries) OldestUnminedOperatorTx(ctx context.Context, arg OldestUnminedOperatorTxParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, oldestUnminedOperatorTx, arg.ChainID, arg.OperatorAddress)
	var oldest time.Time
	err := row.Scan(&oldest)
	return oldest, err
}

const replaceOperatorTxHash = `-- name: ReplaceOperatorTxHash :execrows
UPDATE operator_txs
SET replaced_hashes = array_append(replaced_hashes, tx_hash), tx_hash = $1, status = 'SENT',
    purpose = $2, block_number = NULL, block_hash = NULL
WHERE id = $3 AND tx_hash = $4 AND status IN ('SENT', 'INCLUDED', 'REVERTED')
`

type ReplaceOperatorTxHashParams struct {
	TxHash  []byte
	Purpose string
	ID      uuid.UUID
	OldHash []byte
}

// A new transaction in the same nonce slot — a replacement, a release, a resubmission of a dropped debit: the old hash
// moves to replaced_hashes, the new one is current, the block of the old one is cleared.
func (q *Queries) ReplaceOperatorTxHash(ctx context.Context, arg ReplaceOperatorTxHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceOperatorTxHash,
		arg.TxHash,
		arg.Purpose,
		arg.ID,
		arg.OldHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOperatorTxBlock = `-- name: SetOperatorTxBlock :exec
UPDATE operator_txs
SET block_number = $1, block_hash = $2
WHERE id = $3
`

type SetOperatorTxBlockParams struct {
	BlockNumber *int64
	BlockHash   []byte
	ID          uuid.UUID
}

// Tracker, reorg: the block of an included transaction as the chain shows it now; null when only preconfirmed.
func (q *Queries) SetOperatorTxBlock(ctx context.Context, arg SetOperatorTxBlockParams) error {
	_, err := q.db.Exec(ctx, setOperatorTxBlock, arg.BlockNumber, arg.BlockHash, arg.ID)
	return err
}

const setOperatorTxResolved = `-- name: SetOperatorTxResolved :exec
UPDATE operator_txs
SET tx_hash = $1, purpose = $2, status = $3,
    block_number = $4, block_hash = $5
WHERE id = $6
`

type SetOperatorTxResolvedParams struct {
	TxHash      []byte
	Purpose     string
	Status      string
	BlockNumber *int64
	BlockHash   []byte
	ID          uuid.UUID
}

// Tracker: a slot used on chain by an earlier hash of the row: that hash becomes current again with its purpose.
func (q *Queries) SetOperatorTxResolved(ctx context.Context, arg SetOperatorTxResolvedParams) error {
	_, err := q.db.Exec(ctx, setOperatorTxResolved,
		arg.TxHash,
		arg.Purpose,
		arg.Status,
		arg.BlockNumber,
		arg.BlockHash,
		arg.ID,
	)
	return err
}
