// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operator_accounts.sql

package repository

import (
	"context"
)

const insertOperatorAccount = `-- name: InsertOperatorAccount :exec
INSERT INTO operator_accounts (chain_id, address, next_nonce)
VALUES ($1, $2, $3)
`

type InsertOperatorAccountParams struct {
	ChainID   int64
	Address   []byte
	NextNonce int64
}

func (q *Queries) InsertOperatorAccount(ctx context.Context, arg InsertOperatorAccountParams) error {
	_, err := q.db.Exec(ctx, insertOperatorAccount, arg.ChainID, arg.Address, arg.NextNonce)
	return err
}

const lockOperatorAccount = `-- name: LockOperatorAccount :one
SELECT next_nonce
FROM operator_accounts
WHERE chain_id = $1 AND address = $2
FOR UPDATE
`

type LockOperatorAccountParams struct {
	ChainID int64
	Address []byte
}

// The nonce row of an operator on a network, locked until the end of the transaction.
func (q *Queries) LockOperatorAccount(ctx context.Context, arg LockOperatorAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockOperatorAccount, arg.ChainID, arg.Address)
	var next_nonce int64
	err := row.Scan(&next_nonce)
	return next_nonce, err
}

const setOperatorNextNonce = `-- name: SetOperatorNextNonce :exec
UPDATE operator_accounts
SET next_nonce = $1
WHERE chain_id = $2 AND address = $3
`

type SetOperatorNextNonceParams struct {
	NextNonce int64
	ChainID   int64
	Address   []byte
}

func (q *Queries) SetOperatorNextNonce(ctx context.Context, arg SetOperatorNextNonceParams) error {
	_, err := q.db.Exec(ctx, setOperatorNextNonce, arg.NextNonce, arg.ChainID, arg.Address)
	return err
}
