// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reads.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const connectionExists = `-- name: ConnectionExists :one
SELECT EXISTS (SELECT 1 FROM connections WHERE id = $1 AND tenant_id = $2)::bool
`

type ConnectionExistsParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) ConnectionExists(ctx context.Context, arg ConnectionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, connectionExists, arg.ID, arg.TenantID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listBalanceConnections = `-- name: ListBalanceConnections :many
SELECT c.id, s.code AS source_code, s.kind AS source_kind, s.config AS source_config,
       -- The zero UUID and the epoch stand for "no snapshot": sqlc reads these columns as not null.
       COALESCE(snap.id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS snapshot_id,
       COALESCE(snap.taken_at, 'epoch'::timestamptz)::timestamptz AS taken_at,
       health.streams, health.succeeded,
       COALESCE(health.oldest_success, 'epoch'::timestamptz)::timestamptz AS oldest_success
FROM connections c
JOIN sources s ON s.id = c.source_id
LEFT JOIN LATERAL (
    SELECT bs.id, bs.taken_at
    FROM balance_snapshots bs
    WHERE bs.connection_id = c.id
    ORDER BY bs.created_at DESC, bs.id DESC
    LIMIT 1
) snap ON true
CROSS JOIN LATERAL (
    SELECT count(*) AS streams, count(sc.last_success_at) AS succeeded, min(sc.last_success_at) AS oldest_success
    FROM sync_cursors sc
    WHERE sc.connection_id = c.id AND split_part(sc.stream, ':', 1) = 'balances'
) health
WHERE c.tenant_id = $1
  AND ($2::text IS NULL OR c.owner_ref = $2::text)
  AND ($3::uuid IS NULL OR c.id = $3::uuid)
ORDER BY c.created_at, c.id
`

type ListBalanceConnectionsParams struct {
	TenantID     uuid.UUID
	OwnerRef     *string
	ConnectionID *uuid.UUID
}

type ListBalanceConnectionsRow struct {
	ID            uuid.UUID
	SourceCode    string
	SourceKind    string
	SourceConfig  []byte
	SnapshotID    uuid.UUID
	TakenAt       time.Time
	Streams       int64
	Succeeded     int64
	OldestSuccess time.Time
}

// The selected connections of a tenant in the order of ListConnections, each with its newest snapshot by
// import time and the health of its balance streams (family balances).
func (q *Queries) ListBalanceConnections(ctx context.Context, arg ListBalanceConnectionsParams) ([]ListBalanceConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listBalanceConnections, arg.TenantID, arg.OwnerRef, arg.ConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBalanceConnectionsRow{}
	for rows.Next() {
		var i ListBalanceConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceCode,
			&i.SourceKind,
			&i.SourceConfig,
			&i.SnapshotID,
			&i.TakenAt,
			&i.Streams,
			&i.Succeeded,
			&i.OldestSuccess,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerPage = `-- name: ListLedgerPage :many
SELECT le.seq, le.connection_id, le.type, le.leg, le.direction, le.asset, le.native_asset,
       trim_scale(le.amount)::text AS amount, le.group_id, le.external_id, le.occurred_at
FROM ledger_entries le
JOIN connections c ON c.id = le.connection_id
WHERE le.tenant_id = $1
  AND le.seq > $2
  AND ($3::text IS NULL OR c.owner_ref = $3::text)
  AND ($4::uuid IS NULL OR le.connection_id = $4::uuid)
  AND ($5::text[] IS NULL OR le.type = ANY($5::text[]))
  AND ($6::timestamptz IS NULL OR le.occurred_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR le.occurred_at < $7::timestamptz)
ORDER BY le.seq
LIMIT $8
`

type ListLedgerPageParams struct {
	TenantID     uuid.UUID
	AfterSeq     int64
	OwnerRef     *string
	ConnectionID *uuid.UUID
	Types        []string
	OccurredFrom *time.Time
	OccurredTo   *time.Time
	PageLimit    int32
}

type ListLedgerPageRow struct {
	Seq          int64
	ConnectionID uuid.UUID
	Type         string
	Leg          string
	Direction    string
	Asset        string
	NativeAsset  string
	Amount       string
	GroupID      string
	ExternalID   string
	OccurredAt   time.Time
}

// One page of the ledger of a tenant above after_seq in ascending seq, the filters combined with AND.
// page_limit is the page size plus one, to know whether more entries follow. No OFFSET.
func (q *Queries) ListLedgerPage(ctx context.Context, arg ListLedgerPageParams) ([]ListLedgerPageRow, error) {
	rows, err := q.db.Query(ctx, listLedgerPage,
		arg.TenantID,
		arg.AfterSeq,
		arg.OwnerRef,
		arg.ConnectionID,
		arg.Types,
		arg.OccurredFrom,
		arg.OccurredTo,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerPageRow{}
	for rows.Next() {
		var i ListLedgerPageRow
		if err := rows.Scan(
			&i.Seq,
			&i.ConnectionID,
			&i.Type,
			&i.Leg,
			&i.Direction,
			&i.Asset,
			&i.NativeAsset,
			&i.Amount,
			&i.GroupID,
			&i.ExternalID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotBalances = `-- name: ListSnapshotBalances :many
SELECT snapshot_id, account_type, asset, native_asset,
       trim_scale(free)::text AS free, trim_scale(locked)::text AS locked
FROM snapshot_balances
WHERE snapshot_id = ANY($1::uuid[])
ORDER BY snapshot_id, account_type, native_asset
`

type ListSnapshotBalancesRow struct {
	SnapshotID  uuid.UUID
	AccountType string
	Asset       string
	NativeAsset string
	Free        string
	Locked      string
}

// Amounts as plain decimals: trim_scale removes trailing zeros, numeric text has no exponent.
func (q *Queries) ListSnapshotBalances(ctx context.Context, snapshotIds []uuid.UUID) ([]ListSnapshotBalancesRow, error) {
	rows, err := q.db.Query(ctx, listSnapshotBalances, snapshotIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnapshotBalancesRow{}
	for rows.Next() {
		var i ListSnapshotBalancesRow
		if err := rows.Scan(
			&i.SnapshotID,
			&i.AccountType,
			&i.Asset,
			&i.NativeAsset,
			&i.Free,
			&i.Locked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConnectionForTrigger = `-- name: LockConnectionForTrigger :one
SELECT status, last_manual_sync_at
FROM connections
WHERE id = $1 AND tenant_id = $2
FOR UPDATE
`

type LockConnectionForTriggerParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type LockConnectionForTriggerRow struct {
	Status           string
	LastManualSyncAt *time.Time
}

// First lock of TriggerSync: the connection row, then its cursors.
func (q *Queries) LockConnectionForTrigger(ctx context.Context, arg LockConnectionForTriggerParams) (LockConnectionForTriggerRow, error) {
	row := q.db.QueryRow(ctx, lockConnectionForTrigger, arg.ID, arg.TenantID)
	var i LockConnectionForTriggerRow
	err := row.Scan(&i.Status, &i.LastManualSyncAt)
	return i, err
}

const makeStreamsDue = `-- name: MakeStreamsDue :exec
UPDATE sync_cursors
SET next_run_at = $1
WHERE connection_id = $2
`

type MakeStreamsDueParams struct {
	At           time.Time
	ConnectionID uuid.UUID
}

// Every stream of the connection is due now. The failure counters are not changed.
func (q *Queries) MakeStreamsDue(ctx context.Context, arg MakeStreamsDueParams) error {
	_, err := q.db.Exec(ctx, makeStreamsDue, arg.At, arg.ConnectionID)
	return err
}

const setLastManualSync = `-- name: SetLastManualSync :exec
UPDATE connections
SET last_manual_sync_at = $1
WHERE id = $2
`

type SetLastManualSyncParams struct {
	At *time.Time
	ID uuid.UUID
}

func (q *Queries) SetLastManualSync(ctx context.Context, arg SetLastManualSyncParams) error {
	_, err := q.db.Exec(ctx, setLastManualSync, arg.At, arg.ID)
	return err
}
