// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation_runs.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getNewestRunToBlock = `-- name: GetNewestRunToBlock :one
SELECT n.to_block
FROM tenants t
CROSS JOIN LATERAL (
    SELECT r.to_block, r.created_at, r.id
    FROM reconciliation_runs r
    WHERE r.source_id = $1 AND r.tenant_id = t.id
    ORDER BY r.created_at DESC, r.id DESC
    LIMIT 1
) n
ORDER BY n.created_at DESC, n.id DESC
LIMIT 1
`

// to_block of the newest run of a source, of any tenant; no row when the source has none. The newest run of each
// tenant is one probe of the index (source_id, tenant_id, created_at DESC, id DESC); the newest of those wins.
func (q *Queries) GetNewestRunToBlock(ctx context.Context, sourceID int16) (int64, error) {
	row := q.db.QueryRow(ctx, getNewestRunToBlock, sourceID)
	var to_block int64
	err := row.Scan(&to_block)
	return to_block, err
}

const getReconciliationRun = `-- name: GetReconciliationRun :one
SELECT r.id, s.code AS source_code, r.period_from, r.period_to, r.to_block, r.totals, r.mismatches, r.created_at
FROM reconciliation_runs r
JOIN sources s ON s.id = r.source_id
WHERE r.tenant_id = $1 AND s.code = $2
  AND ($3::uuid IS NULL OR r.id = $3::uuid)
ORDER BY r.created_at DESC, r.id DESC
LIMIT 1
`

type GetReconciliationRunParams struct {
	TenantID   uuid.UUID
	SourceCode string
	RunID      *uuid.UUID
}

type GetReconciliationRunRow struct {
	ID         uuid.UUID
	SourceCode string
	PeriodFrom time.Time
	PeriodTo   time.Time
	ToBlock    int64
	Totals     []byte
	Mismatches []byte
	CreatedAt  time.Time
}

// A run of a tenant on a source: the one of run_id, or the newest when run_id is null; the index
// (source_id, tenant_id, created_at DESC, id DESC).
func (q *Queries) GetReconciliationRun(ctx context.Context, arg GetReconciliationRunParams) (GetReconciliationRunRow, error) {
	row := q.db.QueryRow(ctx, getReconciliationRun, arg.TenantID, arg.SourceCode, arg.RunID)
	var i GetReconciliationRunRow
	err := row.Scan(
		&i.ID,
		&i.SourceCode,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.ToBlock,
		&i.Totals,
		&i.Mismatches,
		&i.CreatedAt,
	)
	return i, err
}

const getTreasuryLogsCursor = `-- name: GetTreasuryLogsCursor :one

SELECT cursor
FROM sync_cursors
WHERE connection_id = $1 AND stream = 'logs'
`

// Reads of the stored reconciliation runs by server (SRS - Core §2.1.1, §3.2): the reconciliation worker, the gauge
// reconciliation_mismatches and GetReconciliationReport. Role cas_server.
// The logs cursor of a connection; no row when the stream has none.
func (q *Queries) GetTreasuryLogsCursor(ctx context.Context, connectionID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTreasuryLogsCursor, connectionID)
	var cursor []byte
	err := row.Scan(&cursor)
	return cursor, err
}

const listNewestRunMismatches = `-- name: ListNewestRunMismatches :many
SELECT s.code AS source_code, n.mismatches
FROM sources s
CROSS JOIN tenants t
CROSS JOIN LATERAL (
    SELECT r.mismatches
    FROM reconciliation_runs r
    WHERE r.source_id = s.id AND r.tenant_id = t.id
    ORDER BY r.created_at DESC, r.id DESC
    LIMIT 1
) n
ORDER BY s.code
`

type ListNewestRunMismatchesRow struct {
	SourceCode string
	Mismatches []byte
}

// The newest run of each tenant on each source, with its source code and its mismatches: one probe of the index
// (source_id, tenant_id, created_at DESC, id DESC) per source and tenant.
func (q *Queries) ListNewestRunMismatches(ctx context.Context) ([]ListNewestRunMismatchesRow, error) {
	rows, err := q.db.Query(ctx, listNewestRunMismatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNewestRunMismatchesRow{}
	for rows.Next() {
		var i ListNewestRunMismatchesRow
		if err := rows.Scan(&i.SourceCode, &i.Mismatches); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
