// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconcile.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getReconcileTreasury = `-- name: GetReconcileTreasury :one

SELECT c.id, c.tenant_id, t.name AS tenant_name, c.source_id, sc.cursor
FROM connections c
JOIN tenants t ON t.id = c.tenant_id
LEFT JOIN sync_cursors sc ON sc.connection_id = c.id AND sc.stream = 'logs'
WHERE c.id = $1
`

type GetReconcileTreasuryRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	TenantName string
	SourceID   int16
	Cursor     []byte
}

// Reconciliation of one EVM source (SRS - Card Spend UC-4): reads only, plus the insert of a run; role cas_server
// (SRS - Core §3.2). Base units as integer strings, decimals without trailing zeros, IDs and hashes as 0x hex.
// tx_hash (SRS - Card Spend §2.1.4): of the DEBIT row, or of the REFUND rows of a return, that is INCLUDED or
// CONFIRMED; else of the newest such row with a hash; else empty.
// The treasury connection named in sources.config, its tenant (the platform tenant, S3 D-1) and its logs cursor;
// the cursor is null when the stream has no row.
func (q *Queries) GetReconcileTreasury(ctx context.Context, id uuid.UUID) (GetReconcileTreasuryRow, error) {
	row := q.db.QueryRow(ctx, getReconcileTreasury, id)
	var i GetReconcileTreasuryRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TenantName,
		&i.SourceID,
		&i.Cursor,
	)
	return i, err
}

const insertReconciliationRun = `-- name: InsertReconciliationRun :one
INSERT INTO reconciliation_runs (tenant_id, source_id, period_from, period_to, to_block, totals, mismatches)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
)
RETURNING id, created_at
`

type InsertReconciliationRunParams struct {
	TenantID   uuid.UUID
	SourceID   int16
	PeriodFrom time.Time
	PeriodTo   time.Time
	ToBlock    int64
	Totals     []byte
	Mismatches []byte
}

type InsertReconciliationRunRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

// Append-only: one row per run of a tenant on a source.
func (q *Queries) InsertReconciliationRun(ctx context.Context, arg InsertReconciliationRunParams) (InsertReconciliationRunRow, error) {
	row := q.db.QueryRow(ctx, insertReconciliationRun,
		arg.TenantID,
		arg.SourceID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.ToBlock,
		arg.Totals,
		arg.Mismatches,
	)
	var i InsertReconciliationRunRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listKnownChainAuthIDs = `-- name: ListKnownChainAuthIDs :many
SELECT chain_auth_id
FROM authorizations
WHERE chain_auth_id = ANY($1::bytea[])
`

// Which of the authIds belong to an authorization of any tenant (rule 2).
func (q *Queries) ListKnownChainAuthIDs(ctx context.Context, ids [][]byte) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listKnownChainAuthIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var chain_auth_id []byte
		if err := rows.Scan(&chain_auth_id); err != nil {
			return nil, err
		}
		items = append(items, chain_auth_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnownChainRefundIDs = `-- name: ListKnownChainRefundIDs :many
SELECT chain_refund_id
FROM returns
WHERE chain_refund_id = ANY($1::bytea[])
`

// Which of the refundIds belong to a return of any tenant (rule 4).
func (q *Queries) ListKnownChainRefundIDs(ctx context.Context, ids [][]byte) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listKnownChainRefundIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var chain_refund_id []byte
		if err := rows.Scan(&chain_refund_id); err != nil {
			return nil, err
		}
		items = append(items, chain_refund_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconcileAuthorizations = `-- name: ListReconcileAuthorizations :many
SELECT a.auth_id, a.chain_auth_id, a.status, COALESCE(a.token_amount::text, '')::text AS token_amount, a.received_at,
       COALESCE('0x' || encode(d.tx_hash, 'hex'), '')::text AS tx_hash
FROM authorizations a
LEFT JOIN LATERAL (
    SELECT t.tx_hash FROM operator_txs t
    WHERE t.authorization_id = a.id AND t.purpose = 'DEBIT' AND t.tx_hash IS NOT NULL
    ORDER BY t.status IN ('INCLUDED', 'CONFIRMED') DESC, t.created_at DESC
    LIMIT 1
) d ON true
WHERE a.tenant_id = $1 AND a.chain_id = $2::bigint
  AND a.valid_until <= $3::timestamptz
ORDER BY a.received_at, a.auth_id
`

type ListReconcileAuthorizationsParams struct {
	TenantID uuid.UUID
	ChainID  int64
	PeriodTo time.Time
}

type ListReconcileAuthorizationsRow struct {
	AuthID      string
	ChainAuthID []byte
	Status      string
	TokenAmount string
	ReceivedAt  time.Time
	TxHash      string
}

// The authorizations of a tenant on a chain eligible for rules 1 and 2a: valid_until at or before period_to.
// Oldest first.
func (q *Queries) ListReconcileAuthorizations(ctx context.Context, arg ListReconcileAuthorizationsParams) ([]ListReconcileAuthorizationsRow, error) {
	rows, err := q.db.Query(ctx, listReconcileAuthorizations, arg.TenantID, arg.ChainID, arg.PeriodTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconcileAuthorizationsRow{}
	for rows.Next() {
		var i ListReconcileAuthorizationsRow
		if err := rows.Scan(
			&i.AuthID,
			&i.ChainAuthID,
			&i.Status,
			&i.TokenAmount,
			&i.ReceivedAt,
			&i.TxHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconcileCheckpoints = `-- name: ListReconcileCheckpoints :many
SELECT asset, native_asset, trim_scale(balance)::text AS balance, trim_scale(ledger_total)::text AS ledger_total
FROM balance_checkpoints
WHERE connection_id = $1 AND gap <> 0
ORDER BY asset, native_asset
`

type ListReconcileCheckpointsRow struct {
	Asset       string
	NativeAsset string
	Balance     string
	LedgerTotal string
}

// The balance checkpoints of the treasury connection with a gap other than 0 (rule 5), in asset units.
func (q *Queries) ListReconcileCheckpoints(ctx context.Context, connectionID uuid.UUID) ([]ListReconcileCheckpointsRow, error) {
	rows, err := q.db.Query(ctx, listReconcileCheckpoints, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconcileCheckpointsRow{}
	for rows.Next() {
		var i ListReconcileCheckpointsRow
		if err := rows.Scan(
			&i.Asset,
			&i.NativeAsset,
			&i.Balance,
			&i.LedgerTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconcileEvents = `-- name: ListReconcileEvents :many
SELECT le.type, le.occurred_at,
       COALESCE(le.raw -> 'args' ->> 'authId', '')::text AS auth_id,
       COALESCE(le.raw -> 'args' ->> 'refundId', '')::text AS refund_id,
       COALESCE(le.raw -> 'args' ->> 'amount', '')::text AS amount,
       COALESCE(le.raw ->> 'transactionHash', '')::text AS tx_hash
FROM ledger_entries le
WHERE le.connection_id = $1 AND le.stream = 'logs'
  AND ((le.type = 'CARD_DEBIT' AND le.direction = 'IN') OR (le.type = 'CARD_REFUND' AND le.direction = 'OUT'))
ORDER BY le.seq
`

type ListReconcileEventsRow struct {
	Type       string
	OccurredAt time.Time
	AuthID     string
	RefundID   string
	Amount     string
	TxHash     string
}

// The Debited and Refunded events of the treasury connection: CARD_DEBIT IN and CARD_REFUND OUT of its logs stream,
// with the fields of the stored log (SRS - EVM Connector §2.4). In the order of the ledger.
func (q *Queries) ListReconcileEvents(ctx context.Context, connectionID uuid.UUID) ([]ListReconcileEventsRow, error) {
	rows, err := q.db.Query(ctx, listReconcileEvents, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconcileEventsRow{}
	for rows.Next() {
		var i ListReconcileEventsRow
		if err := rows.Scan(
			&i.Type,
			&i.OccurredAt,
			&i.AuthID,
			&i.RefundID,
			&i.Amount,
			&i.TxHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconcileReturns = `-- name: ListReconcileReturns :many
WITH refund AS (
    SELECT DISTINCT ON (t.return_row_id) t.return_row_id, t.tx_hash, t.block_number
    FROM operator_txs t
    WHERE t.purpose = 'REFUND' AND t.return_row_id IS NOT NULL AND t.tx_hash IS NOT NULL
    ORDER BY t.return_row_id, t.status IN ('INCLUDED', 'CONFIRMED') DESC, t.created_at DESC
)
SELECT r.return_id, r.chain_refund_id, r.token_amount::text AS token_amount,
       ('0x' || encode(x.tx_hash, 'hex'))::text AS tx_hash
FROM returns r
JOIN authorizations a ON a.id = r.authorization_id
JOIN refund x ON x.return_row_id = r.id
WHERE r.tenant_id = $1 AND a.chain_id = $2::bigint AND r.status = 'CONFIRMED'
  AND x.block_number <= $3::bigint
ORDER BY r.created_at, r.return_id
`

type ListReconcileReturnsParams struct {
	TenantID uuid.UUID
	ChainID  int64
	ToBlock  int64
}

type ListReconcileReturnsRow struct {
	ReturnID      string
	ChainRefundID []byte
	TokenAmount   string
	TxHash        string
}

// The returns of a tenant on a chain eligible for rule 3: CONFIRMED, and the block of its REFUND row at or below
// to_block. The REFUND row is the one of tx_hash; a return whose row has no block is not eligible.
func (q *Queries) ListReconcileReturns(ctx context.Context, arg ListReconcileReturnsParams) ([]ListReconcileReturnsRow, error) {
	rows, err := q.db.Query(ctx, listReconcileReturns, arg.TenantID, arg.ChainID, arg.ToBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconcileReturnsRow{}
	for rows.Next() {
		var i ListReconcileReturnsRow
		if err := rows.Scan(
			&i.ReturnID,
			&i.ChainRefundID,
			&i.TokenAmount,
			&i.TxHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconcileTenants = `-- name: ListReconcileTenants :many
SELECT t.id, t.name
FROM tenants t
WHERE t.id <> $1
  AND EXISTS (SELECT 1 FROM authorizations a WHERE a.tenant_id = t.id AND a.chain_id = $2::bigint)
ORDER BY t.name
`

type ListReconcileTenantsParams struct {
	PlatformTenantID uuid.UUID
	ChainID          int64
}

type ListReconcileTenantsRow struct {
	ID   uuid.UUID
	Name string
}

// The partner tenants of a chain: every tenant but the platform tenant with an authorization on the chain.
func (q *Queries) ListReconcileTenants(ctx context.Context, arg ListReconcileTenantsParams) ([]ListReconcileTenantsRow, error) {
	rows, err := q.db.Query(ctx, listReconcileTenants, arg.PlatformTenantID, arg.ChainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconcileTenantsRow{}
	for rows.Next() {
		var i ListReconcileTenantsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
