// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: returns.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addReturnedAmount = `-- name: AddReturnedAmount :exec
UPDATE authorizations
SET returned_amount = returned_amount + $1::text::numeric
WHERE id = $2
`

type AddReturnedAmountParams struct {
	Amount string
	ID     uuid.UUID
}

// UC-2 step 6.
func (q *Queries) AddReturnedAmount(ctx context.Context, arg AddReturnedAmountParams) error {
	_, err := q.db.Exec(ctx, addReturnedAmount, arg.Amount, arg.ID)
	return err
}

const closeOpenReturns = `-- name: CloseOpenReturns :one
WITH open_returns AS (
    SELECT id, token_amount FROM returns
    WHERE authorization_id = $1 AND status IN ('ACCEPTED', 'RETRYING', 'SUBMITTED')
    FOR UPDATE
), closed AS (
    UPDATE returns r SET status = 'NOTHING_TO_RETURN', token_amount = 0
    FROM open_returns o WHERE r.id = o.id
    RETURNING o.token_amount
)
UPDATE authorizations a
SET returned_amount = a.returned_amount - (SELECT COALESCE(sum(c.token_amount), 0) FROM closed c)
WHERE a.id = $1
RETURNING (SELECT count(*) FROM closed)::bigint AS closed
`

// FR-14: the open returns of a DEBIT_LOST authorization close as NOTHING_TO_RETURN with no tokens; returned_amount
// drops by their amounts (UC-3 row 3, st6b). Returns the number closed.
func (q *Queries) CloseOpenReturns(ctx context.Context, authorizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, closeOpenReturns, authorizationID)
	var closed int64
	err := row.Scan(&closed)
	return closed, err
}

const countReturnsNotConfirmed = `-- name: CountReturnsNotConfirmed :one
SELECT count(*)
FROM returns r
JOIN authorizations a ON a.id = r.authorization_id
WHERE r.status IN ('ACCEPTED', 'SUBMITTED', 'INCLUDED', 'RETRYING') AND a.chain_id = $1
`

// returns_not_confirmed (SRS - Card Spend §2.5.1).
func (q *Queries) CountReturnsNotConfirmed(ctx context.Context, chainID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReturnsNotConfirmed, chainID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReturnForRequest = `-- name: GetReturnForRequest :one

SELECT r.id, r.request_hash, r.status, r.token_amount::text AS token_amount, a.auth_id
FROM returns r
JOIN authorizations a ON a.id = r.authorization_id
WHERE r.tenant_id = $1 AND r.return_id = $2
`

type GetReturnForRequestParams struct {
	TenantID uuid.UUID
	ReturnID string
}

type GetReturnForRequestRow struct {
	ID          uuid.UUID
	RequestHash []byte
	Status      string
	TokenAmount string
	AuthID      string
}

// Returns of card-auth (SRS - Card Spend UC-2, UC-3 for returns), role cas_card_auth.
// Amounts are passed and read as text: no float between the service and the database.
// UC-2 step 2: a return of the tenant by return_id with what a repeated request needs.
func (q *Queries) GetReturnForRequest(ctx context.Context, arg GetReturnForRequestParams) (GetReturnForRequestRow, error) {
	row := q.db.QueryRow(ctx, getReturnForRequest, arg.TenantID, arg.ReturnID)
	var i GetReturnForRequestRow
	err := row.Scan(
		&i.ID,
		&i.RequestHash,
		&i.Status,
		&i.TokenAmount,
		&i.AuthID,
	)
	return i, err
}

const getReturnedFiat = `-- name: GetReturnedFiat :one
SELECT COALESCE(sum(fiat_amount), 0)::text AS returned
FROM returns
WHERE authorization_id = $1
`

// UC-2 step 5: the fiat amount of the returns of an authorization so far.
func (q *Queries) GetReturnedFiat(ctx context.Context, authorizationID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getReturnedFiat, authorizationID)
	var returned string
	err := row.Scan(&returned)
	return returned, err
}

const insertReturn = `-- name: InsertReturn :one
INSERT INTO returns (tenant_id, authorization_id, return_id, chain_refund_id, type, request_hash, fiat_amount,
                     token_amount, status, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7::text::numeric, $8::text::numeric,
        $9, $10)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertReturnParams struct {
	TenantID        uuid.UUID
	AuthorizationID uuid.UUID
	ReturnID        string
	ChainRefundID   []byte
	Type            string
	RequestHash     []byte
	FiatAmount      *string
	TokenAmount     string
	Status          string
	CreatedAt       time.Time
}

// UC-2 steps 3, 4 and 6. A concurrent return with the same return_id is no row: the caller reads it.
func (q *Queries) InsertReturn(ctx context.Context, arg InsertReturnParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertReturn,
		arg.TenantID,
		arg.AuthorizationID,
		arg.ReturnID,
		arg.ChainRefundID,
		arg.Type,
		arg.RequestHash,
		arg.FiatAmount,
		arg.TokenAmount,
		arg.Status,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTombstone = `-- name: InsertTombstone :one
INSERT INTO authorizations (tenant_id, auth_id, chain_auth_id, status, decline_reason, received_at, decided_at)
VALUES ($1, $2, $3, 'DECLINED', 'REVERSED_BEFORE_AUTH',
        $4, $4)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertTombstoneParams struct {
	TenantID    uuid.UUID
	AuthID      string
	ChainAuthID []byte
	Now         time.Time
}

// UC-2 step 3: the tombstone of a reversal for an unknown auth_id. A concurrent authorization with the same auth_id
// is no row: the caller reads it.
func (q *Queries) InsertTombstone(ctx context.Context, arg InsertTombstoneParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTombstone,
		arg.TenantID,
		arg.AuthID,
		arg.ChainAuthID,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listReturnsInFlight = `-- name: ListReturnsInFlight :many
SELECT r.id, r.status, r.chain_refund_id, r.token_amount::text AS token_amount, a.chain_auth_id,
       COALESCE(t.id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS tx_id,
       t.tx_hash, COALESCE(t.nonce, -1)::bigint AS nonce, COALESCE(t.status, '')::text AS tx_status,
       t.block_number, t.block_hash
FROM returns r
JOIN authorizations a ON a.id = r.authorization_id
LEFT JOIN LATERAL (
    SELECT o.id, o.tx_hash, o.nonce, o.status, o.block_number, o.block_hash FROM operator_txs o
    WHERE o.return_row_id = r.id AND o.purpose = 'REFUND'
    ORDER BY o.created_at DESC, o.nonce DESC
    LIMIT 1
) t ON true
WHERE r.status IN ('SUBMITTED', 'INCLUDED')
  AND a.chain_id = $1
  AND NOT EXISTS (
      SELECT 1 FROM operator_txs o
      WHERE o.return_row_id = r.id AND (o.chain_id <> $1 OR o.operator_address <> $2))
ORDER BY r.created_at, r.id
`

type ListReturnsInFlightParams struct {
	ChainID         *int64
	OperatorAddress []byte
}

type ListReturnsInFlightRow struct {
	ID            uuid.UUID
	Status        string
	ChainRefundID []byte
	TokenAmount   string
	ChainAuthID   []byte
	TxID          uuid.UUID
	TxHash        []byte
	Nonce         int64
	TxStatus      string
	BlockNumber   *int64
	BlockHash     []byte
}

// Tracker: SUBMITTED and INCLUDED returns of this chain and operator with the current transaction of their latest slot.
func (q *Queries) ListReturnsInFlight(ctx context.Context, arg ListReturnsInFlightParams) ([]ListReturnsInFlightRow, error) {
	rows, err := q.db.Query(ctx, listReturnsInFlight, arg.ChainID, arg.OperatorAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReturnsInFlightRow{}
	for rows.Next() {
		var i ListReturnsInFlightRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ChainRefundID,
			&i.TokenAmount,
			&i.ChainAuthID,
			&i.TxID,
			&i.TxHash,
			&i.Nonce,
			&i.TxStatus,
			&i.BlockNumber,
			&i.BlockHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnsToSend = `-- name: ListReturnsToSend :many
SELECT r.id, r.chain_refund_id, r.token_amount::text AS token_amount, a.chain_auth_id
FROM returns r
JOIN authorizations a ON a.id = r.authorization_id
LEFT JOIN LATERAL (
    SELECT max(t.created_at) AS last_attempt FROM operator_txs t WHERE t.return_row_id = r.id
) l ON true
WHERE (r.status = 'ACCEPTED'
   OR (r.status = 'RETRYING' AND (l.last_attempt IS NULL OR l.last_attempt <= $1::timestamptz)))
  AND a.chain_id = $2
  AND NOT EXISTS (
      SELECT 1 FROM operator_txs o
      WHERE o.return_row_id = r.id AND (o.chain_id <> $2 OR o.operator_address <> $3))
ORDER BY r.created_at, r.id
LIMIT $4
`

type ListReturnsToSendParams struct {
	DueBefore       time.Time
	ChainID         *int64
	OperatorAddress []byte
	PageLimit       int32
}

type ListReturnsToSendRow struct {
	ID            uuid.UUID
	ChainRefundID []byte
	TokenAmount   string
	ChainAuthID   []byte
}

// Tracker: ACCEPTED returns, and RETRYING returns whose last attempt is return_retry_interval old, of this chain and
// operator.
func (q *Queries) ListReturnsToSend(ctx context.Context, arg ListReturnsToSendParams) ([]ListReturnsToSendRow, error) {
	rows, err := q.db.Query(ctx, listReturnsToSend,
		arg.DueBefore,
		arg.ChainID,
		arg.OperatorAddress,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReturnsToSendRow{}
	for rows.Next() {
		var i ListReturnsToSendRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainRefundID,
			&i.TokenAmount,
			&i.ChainAuthID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuthorizationForReturn = `-- name: LockAuthorizationForReturn :one
SELECT id, status, debited_amount::text AS debited_amount, returned_amount::text AS returned_amount,
       COALESCE(fiat_amount::text, '')::text AS fiat_amount
FROM authorizations
WHERE tenant_id = $1 AND auth_id = $2
FOR UPDATE
`

type LockAuthorizationForReturnParams struct {
	TenantID uuid.UUID
	AuthID   string
}

type LockAuthorizationForReturnRow struct {
	ID             uuid.UUID
	Status         string
	DebitedAmount  string
	ReturnedAmount string
	FiatAmount     string
}

// UC-2 steps 3 - 5: the authorization of the return, locked until the end of the transaction, so that two returns
// of one authorization are accepted one after another.
func (q *Queries) LockAuthorizationForReturn(ctx context.Context, arg LockAuthorizationForReturnParams) (LockAuthorizationForReturnRow, error) {
	row := q.db.QueryRow(ctx, lockAuthorizationForReturn, arg.TenantID, arg.AuthID)
	var i LockAuthorizationForReturnRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.DebitedAmount,
		&i.ReturnedAmount,
		&i.FiatAmount,
	)
	return i, err
}

const lockReturnToSend = `-- name: LockReturnToSend :one
SELECT r.status,
       COALESCE(p.id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS planned_id, COALESCE(p.nonce, -1)::bigint AS planned_nonce
FROM returns r
LEFT JOIN LATERAL (
    SELECT o.id, o.nonce FROM operator_txs o
    WHERE o.return_row_id = r.id AND o.status = 'PLANNED'
    ORDER BY o.created_at DESC
    LIMIT 1
) p ON true
WHERE r.id = $1
FOR UPDATE OF r
`

type LockReturnToSendRow struct {
	Status       string
	PlannedID    uuid.UUID
	PlannedNonce int64
}

// Tracker: a return about to be sent, with the latest slot of an earlier attempt that was never sent.
func (q *Queries) LockReturnToSend(ctx context.Context, id uuid.UUID) (LockReturnToSendRow, error) {
	row := q.db.QueryRow(ctx, lockReturnToSend, id)
	var i LockReturnToSendRow
	err := row.Scan(&i.Status, &i.PlannedID, &i.PlannedNonce)
	return i, err
}

const setOperatorTxStatus = `-- name: SetOperatorTxStatus :exec
UPDATE operator_txs
SET status = $1,
    block_number = COALESCE($2, block_number),
    block_hash = COALESCE($3, block_hash)
WHERE id = $4
`

type SetOperatorTxStatusParams struct {
	Status      string
	BlockNumber *int64
	BlockHash   []byte
	ID          uuid.UUID
}

// Tracker: the status of an operator transaction; block number and hash only from a sealed receipt.
func (q *Queries) SetOperatorTxStatus(ctx context.Context, arg SetOperatorTxStatusParams) error {
	_, err := q.db.Exec(ctx, setOperatorTxStatus,
		arg.Status,
		arg.BlockNumber,
		arg.BlockHash,
		arg.ID,
	)
	return err
}

const setReturnStatus = `-- name: SetReturnStatus :execrows
UPDATE returns
SET status = $1, attempts = attempts + $2::int
WHERE id = $3 AND status = ANY ($4::text[])
`

type SetReturnStatusParams struct {
	Status       string
	Attempt      int32
	ID           uuid.UUID
	FromStatuses []string
}

// Tracker: a status change of a return from one of the expected statuses; attempts grows with each send.
func (q *Queries) SetReturnStatus(ctx context.Context, arg SetReturnStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setReturnStatus,
		arg.Status,
		arg.Attempt,
		arg.ID,
		arg.FromStatuses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
