// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package repository

import (
	"context"
)

const getSourceByCode = `-- name: GetSourceByCode :one
SELECT id, code, kind, enabled, config
FROM sources
WHERE code = $1
`

func (q *Queries) GetSourceByCode(ctx context.Context, code string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByCode, code)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Enabled,
		&i.Config,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, code, kind, enabled, config
FROM sources
ORDER BY code
`

// Every source, enabled or not. Availability also depends on the registered connectors.
func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Kind,
			&i.Enabled,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
