// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package repository

import (
	"context"
)

const addFakeAlias = `-- name: AddFakeAlias :execrows
INSERT INTO asset_aliases (source_id, native_asset, asset)
SELECT id, $1, $2 FROM sources WHERE code = 'fake'
ON CONFLICT (source_id, native_asset) DO NOTHING
`

type AddFakeAliasParams struct {
	NativeAsset string
	Asset       string
}

// Alias of an asset of the fake source: 1 row when added, 0 when it exists.
func (q *Queries) AddFakeAlias(ctx context.Context, arg AddFakeAliasParams) (int64, error) {
	result, err := q.db.Exec(ctx, addFakeAlias, arg.NativeAsset, arg.Asset)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addFakeSource = `-- name: AddFakeSource :execrows
INSERT INTO sources (code, kind, enabled, config)
VALUES ('fake', 'EXCHANGE', true, '{}')
ON CONFLICT (code) DO NOTHING
`

// Development seed of the fake connector: 1 row when added, 0 when it exists.
func (q *Queries) AddFakeSource(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, addFakeSource)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSourceAliasesOfAsset = `-- name: DeleteSourceAliasesOfAsset :exec
DELETE FROM asset_aliases
WHERE source_id = $1 AND asset = $2
`

type DeleteSourceAliasesOfAssetParams struct {
	SourceID int16
	Asset    string
}

func (q *Queries) DeleteSourceAliasesOfAsset(ctx context.Context, arg DeleteSourceAliasesOfAssetParams) error {
	_, err := q.db.Exec(ctx, deleteSourceAliasesOfAsset, arg.SourceID, arg.Asset)
	return err
}

const getSourceByCode = `-- name: GetSourceByCode :one
SELECT id, code, kind, enabled, config
FROM sources
WHERE code = $1
`

func (q *Queries) GetSourceByCode(ctx context.Context, code string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByCode, code)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Enabled,
		&i.Config,
	)
	return i, err
}

const insertSourceAlias = `-- name: InsertSourceAlias :exec
INSERT INTO asset_aliases (source_id, native_asset, asset, decimals)
VALUES ($1, $2, $3, $4)
`

type InsertSourceAliasParams struct {
	SourceID    int16
	NativeAsset string
	Asset       string
	Decimals    *int16
}

func (q *Queries) InsertSourceAlias(ctx context.Context, arg InsertSourceAliasParams) error {
	_, err := q.db.Exec(ctx, insertSourceAlias,
		arg.SourceID,
		arg.NativeAsset,
		arg.Asset,
		arg.Decimals,
	)
	return err
}

const listSourceAliasesOfAsset = `-- name: ListSourceAliasesOfAsset :many
SELECT native_asset
FROM asset_aliases
WHERE source_id = $1 AND asset = $2
ORDER BY native_asset
`

type ListSourceAliasesOfAssetParams struct {
	SourceID int16
	Asset    string
}

// The aliases of a source that map to one canonical asset: the tracked token of an EVM source.
func (q *Queries) ListSourceAliasesOfAsset(ctx context.Context, arg ListSourceAliasesOfAssetParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSourceAliasesOfAsset, arg.SourceID, arg.Asset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var native_asset string
		if err := rows.Scan(&native_asset); err != nil {
			return nil, err
		}
		items = append(items, native_asset)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, code, kind, enabled, config
FROM sources
ORDER BY code
`

// Every source, enabled or not. Availability also depends on the registered connectors.
func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Kind,
			&i.Enabled,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSourceByCode = `-- name: LockSourceByCode :one
SELECT id, code, kind, enabled, config
FROM sources
WHERE code = $1
FOR UPDATE
`

// casctl source set: the source row, locked until the end of the transaction.
func (q *Queries) LockSourceByCode(ctx context.Context, code string) (Source, error) {
	row := q.db.QueryRow(ctx, lockSourceByCode, code)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Enabled,
		&i.Config,
	)
	return i, err
}

const setSourceConfigValue = `-- name: SetSourceConfigValue :exec
UPDATE sources
SET config = config || jsonb_build_object($1::text, $2::jsonb)
WHERE id = $3
`

type SetSourceConfigValueParams struct {
	Key   string
	Value []byte
	ID    int16
}

// One key of sources.config; the other keys are kept.
func (q *Queries) SetSourceConfigValue(ctx context.Context, arg SetSourceConfigValueParams) error {
	_, err := q.db.Exec(ctx, setSourceConfigValue, arg.Key, arg.Value, arg.ID)
	return err
}
