// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package repository

import (
	"context"
)

const addFakeSource = `-- name: AddFakeSource :execrows
INSERT INTO sources (code, kind, enabled, config)
VALUES ('fake', 'EXCHANGE', true, '{}')
ON CONFLICT (code) DO NOTHING
`

// Development seed of the fake connector: 1 row when added, 0 when it exists.
func (q *Queries) AddFakeSource(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, addFakeSource)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSourceByCode = `-- name: GetSourceByCode :one
SELECT id, code, kind, enabled, config
FROM sources
WHERE code = $1
`

func (q *Queries) GetSourceByCode(ctx context.Context, code string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByCode, code)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Enabled,
		&i.Config,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, code, kind, enabled, config
FROM sources
ORDER BY code
`

// Every source, enabled or not. Availability also depends on the registered connectors.
func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Kind,
			&i.Enabled,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
