// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_cursors.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertSyncCursor = `-- name: InsertSyncCursor :exec
INSERT INTO sync_cursors (connection_id, stream, mode, cursor, next_run_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSyncCursorParams struct {
	ConnectionID uuid.UUID
	Stream       string
	Mode         string
	Cursor       []byte
	NextRunAt    time.Time
}

func (q *Queries) InsertSyncCursor(ctx context.Context, arg InsertSyncCursorParams) error {
	_, err := q.db.Exec(ctx, insertSyncCursor,
		arg.ConnectionID,
		arg.Stream,
		arg.Mode,
		arg.Cursor,
		arg.NextRunAt,
	)
	return err
}
