// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracker_debits.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLateDebitReturnStatus = `-- name: GetLateDebitReturnStatus :one
SELECT status FROM returns WHERE authorization_id = $1 AND type = 'LATE_DEBIT'
`

// Row 5: the status of the LATE_DEBIT return of an authorization.
func (q *Queries) GetLateDebitReturnStatus(ctx context.Context, authorizationID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLateDebitReturnStatus, authorizationID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listAuthorizationTxs = `-- name: ListAuthorizationTxs :many
SELECT id, purpose, nonce, status, tx_hash, replaced_hashes, block_number, block_hash
FROM operator_txs
WHERE authorization_id = $1
ORDER BY nonce DESC
`

type ListAuthorizationTxsRow struct {
	ID             uuid.UUID
	Purpose        string
	Nonce          int64
	Status         string
	TxHash         []byte
	ReplacedHashes [][]byte
	BlockNumber    *int64
	BlockHash      []byte
}

// The operator transactions of an authorization, newest slot first.
func (q *Queries) ListAuthorizationTxs(ctx context.Context, authorizationID *uuid.UUID) ([]ListAuthorizationTxsRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizationTxs, authorizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorizationTxsRow{}
	for rows.Next() {
		var i ListAuthorizationTxsRow
		if err := rows.Scan(
			&i.ID,
			&i.Purpose,
			&i.Nonce,
			&i.Status,
			&i.TxHash,
			&i.ReplacedHashes,
			&i.BlockNumber,
			&i.BlockHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorizationsToTrack = `-- name: ListAuthorizationsToTrack :many

SELECT a.id, a.tenant_id, a.auth_id, a.chain_auth_id, a.status, a.wallet_address, COALESCE(a.token_amount::text, '')::text AS token_amount,
       a.debited_amount::text AS debited_amount, a.valid_until, a.deadline_at
FROM authorizations a
WHERE a.status IN ('APPROVED', 'DEBIT_SUBMITTED', 'TIMED_OUT', 'LATE_DEBIT', 'RECEIVED')
  AND (a.chain_id = $1 OR a.chain_id IS NULL)
  AND NOT EXISTS (
      SELECT 1 FROM operator_txs o
      WHERE o.authorization_id = a.id AND (o.chain_id <> $1 OR o.operator_address <> $2))
ORDER BY a.received_at, a.id
`

type ListAuthorizationsToTrackParams struct {
	ChainID         *int64
	OperatorAddress []byte
}

type ListAuthorizationsToTrackRow struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	AuthID        string
	ChainAuthID   []byte
	Status        string
	WalletAddress []byte
	TokenAmount   string
	DebitedAmount string
	ValidUntil    *time.Time
	DeadlineAt    *time.Time
}

// Debit side of the tracker of card-auth (SRS - Card Spend UC-3), role cas_card_auth.
// Every authorization of this chain that is not final: APPROVED, DEBIT_SUBMITTED, TIMED_OUT, LATE_DEBIT, and RECEIVED
// (whose chain is not known before its card is read). An authorization with a slot of another chain or another
// operator key is never touched.
func (q *Queries) ListAuthorizationsToTrack(ctx context.Context, arg ListAuthorizationsToTrackParams) ([]ListAuthorizationsToTrackRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizationsToTrack, arg.ChainID, arg.OperatorAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorizationsToTrackRow{}
	for rows.Next() {
		var i ListAuthorizationsToTrackRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AuthID,
			&i.ChainAuthID,
			&i.Status,
			&i.WalletAddress,
			&i.TokenAmount,
			&i.DebitedAmount,
			&i.ValidUntil,
			&i.DeadlineAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAuthorization = `-- name: MoveAuthorization :execrows
UPDATE authorizations
SET status = $1,
    decline_reason = COALESCE($2, decline_reason),
    debited_amount = COALESCE($3::text::numeric, debited_amount),
    returned_amount = returned_amount + COALESCE($4::text::numeric, 0),
    decided_at = COALESCE(decided_at, $5),
    valid_until = COALESCE($6, valid_until)
WHERE id = $7 AND status = $8
`

type MoveAuthorizationParams struct {
	ToStatus      string
	DeclineReason *string
	DebitedAmount *string
	ReturnedAdd   *string
	DecidedAt     *time.Time
	ValidUntil    *time.Time
	ID            uuid.UUID
	FromStatus    string
}

// Tracker: a status change of an authorization from an expected status. A null value keeps the stored one.
func (q *Queries) MoveAuthorization(ctx context.Context, arg MoveAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveAuthorization,
		arg.ToStatus,
		arg.DeclineReason,
		arg.DebitedAmount,
		arg.ReturnedAdd,
		arg.DecidedAt,
		arg.ValidUntil,
		arg.ID,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAuthorizationValidUntil = `-- name: SetAuthorizationValidUntil :exec
UPDATE authorizations SET valid_until = $1 WHERE id = $2
`

type SetAuthorizationValidUntilParams struct {
	ValidUntil *time.Time
	ID         uuid.UUID
}

// Row 2: the new validUntil of a resubmitted debit.
func (q *Queries) SetAuthorizationValidUntil(ctx context.Context, arg SetAuthorizationValidUntilParams) error {
	_, err := q.db.Exec(ctx, setAuthorizationValidUntil, arg.ValidUntil, arg.ID)
	return err
}
