// Contract of Crypto Account Service: balances and ledger.
// Specification: docs/srs/core.md §2.1.3, §2.1.4.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cas/v1/account_data_service.proto

package casv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountDataService_GetBalances_FullMethodName       = "/cas.v1.AccountDataService/GetBalances"
	AccountDataService_ListLedgerEntries_FullMethodName = "/cas.v1.AccountDataService/ListLedgerEntries"
)

// AccountDataServiceClient is the client API for AccountDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountDataService reads balances and the ledger of the caller's tenant.
// Reads never call a source. Amounts are decimal strings, never floats.
type AccountDataServiceClient interface {
	// GetBalances returns the latest snapshot of each selected connection.
	GetBalances(ctx context.Context, in *GetBalancesRequest, opts ...grpc.CallOption) (*GetBalancesResponse, error)
	// ListLedgerEntries returns ledger entries in ascending `seq`, for incremental pull.
	ListLedgerEntries(ctx context.Context, in *ListLedgerEntriesRequest, opts ...grpc.CallOption) (*ListLedgerEntriesResponse, error)
}

type accountDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountDataServiceClient(cc grpc.ClientConnInterface) AccountDataServiceClient {
	return &accountDataServiceClient{cc}
}

func (c *accountDataServiceClient) GetBalances(ctx context.Context, in *GetBalancesRequest, opts ...grpc.CallOption) (*GetBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalancesResponse)
	err := c.cc.Invoke(ctx, AccountDataService_GetBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountDataServiceClient) ListLedgerEntries(ctx context.Context, in *ListLedgerEntriesRequest, opts ...grpc.CallOption) (*ListLedgerEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLedgerEntriesResponse)
	err := c.cc.Invoke(ctx, AccountDataService_ListLedgerEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountDataServiceServer is the server API for AccountDataService service.
// All implementations must embed UnimplementedAccountDataServiceServer
// for forward compatibility.
//
// AccountDataService reads balances and the ledger of the caller's tenant.
// Reads never call a source. Amounts are decimal strings, never floats.
type AccountDataServiceServer interface {
	// GetBalances returns the latest snapshot of each selected connection.
	GetBalances(context.Context, *GetBalancesRequest) (*GetBalancesResponse, error)
	// ListLedgerEntries returns ledger entries in ascending `seq`, for incremental pull.
	ListLedgerEntries(context.Context, *ListLedgerEntriesRequest) (*ListLedgerEntriesResponse, error)
	mustEmbedUnimplementedAccountDataServiceServer()
}

// UnimplementedAccountDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountDataServiceServer struct{}

func (UnimplementedAccountDataServiceServer) GetBalances(context.Context, *GetBalancesRequest) (*GetBalancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalances not implemented")
}
func (UnimplementedAccountDataServiceServer) ListLedgerEntries(context.Context, *ListLedgerEntriesRequest) (*ListLedgerEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLedgerEntries not implemented")
}
func (UnimplementedAccountDataServiceServer) mustEmbedUnimplementedAccountDataServiceServer() {}
func (UnimplementedAccountDataServiceServer) testEmbeddedByValue()                            {}

// UnsafeAccountDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountDataServiceServer will
// result in compilation errors.
type UnsafeAccountDataServiceServer interface {
	mustEmbedUnimplementedAccountDataServiceServer()
}

func RegisterAccountDataServiceServer(s grpc.ServiceRegistrar, srv AccountDataServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountDataService_ServiceDesc, srv)
}

func _AccountDataService_GetBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountDataServiceServer).GetBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountDataService_GetBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountDataServiceServer).GetBalances(ctx, req.(*GetBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountDataService_ListLedgerEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLedgerEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountDataServiceServer).ListLedgerEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountDataService_ListLedgerEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountDataServiceServer).ListLedgerEntries(ctx, req.(*ListLedgerEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountDataService_ServiceDesc is the grpc.ServiceDesc for AccountDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cas.v1.AccountDataService",
	HandlerType: (*AccountDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalances",
			Handler:    _AccountDataService_GetBalances_Handler,
		},
		{
			MethodName: "ListLedgerEntries",
			Handler:    _AccountDataService_ListLedgerEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cas/v1/account_data_service.proto",
}
