// Contract of Crypto Account Service: balances and ledger.
// Specification: docs/srs/core.md §2.1.3, §2.1.4.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cas/v1/account_data_service.proto

package casv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wallet of an account that holds a balance.
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED   AccountType = 0
	AccountType_ACCOUNT_TYPE_SPOT          AccountType = 1
	AccountType_ACCOUNT_TYPE_FUNDING       AccountType = 2
	AccountType_ACCOUNT_TYPE_EARN_FLEXIBLE AccountType = 3
	AccountType_ACCOUNT_TYPE_EARN_LOCKED   AccountType = 4
	AccountType_ACCOUNT_TYPE_WALLET        AccountType = 5
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_SPOT",
		2: "ACCOUNT_TYPE_FUNDING",
		3: "ACCOUNT_TYPE_EARN_FLEXIBLE",
		4: "ACCOUNT_TYPE_EARN_LOCKED",
		5: "ACCOUNT_TYPE_WALLET",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED":   0,
		"ACCOUNT_TYPE_SPOT":          1,
		"ACCOUNT_TYPE_FUNDING":       2,
		"ACCOUNT_TYPE_EARN_FLEXIBLE": 3,
		"ACCOUNT_TYPE_EARN_LOCKED":   4,
		"ACCOUNT_TYPE_WALLET":        5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_account_data_service_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_cas_v1_account_data_service_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_account_data_service_proto_rawDescGZIP(), []int{0}
}

// Type of a ledger entry.
type LedgerEntryType int32

const (
	LedgerEntryType_LEDGER_ENTRY_TYPE_UNSPECIFIED LedgerEntryType = 0
	LedgerEntryType_LEDGER_ENTRY_TYPE_DEPOSIT     LedgerEntryType = 1
	LedgerEntryType_LEDGER_ENTRY_TYPE_WITHDRAWAL  LedgerEntryType = 2
	LedgerEntryType_LEDGER_ENTRY_TYPE_TRADE       LedgerEntryType = 3
	LedgerEntryType_LEDGER_ENTRY_TYPE_FEE         LedgerEntryType = 4
	LedgerEntryType_LEDGER_ENTRY_TYPE_CONVERT     LedgerEntryType = 5
	LedgerEntryType_LEDGER_ENTRY_TYPE_REWARD      LedgerEntryType = 6
	LedgerEntryType_LEDGER_ENTRY_TYPE_CARD_DEBIT  LedgerEntryType = 7
	LedgerEntryType_LEDGER_ENTRY_TYPE_CARD_REFUND LedgerEntryType = 8
)

// Enum value maps for LedgerEntryType.
var (
	LedgerEntryType_name = map[int32]string{
		0: "LEDGER_ENTRY_TYPE_UNSPECIFIED",
		1: "LEDGER_ENTRY_TYPE_DEPOSIT",
		2: "LEDGER_ENTRY_TYPE_WITHDRAWAL",
		3: "LEDGER_ENTRY_TYPE_TRADE",
		4: "LEDGER_ENTRY_TYPE_FEE",
		5: "LEDGER_ENTRY_TYPE_CONVERT",
		6: "LEDGER_ENTRY_TYPE_REWARD",
		7: "LEDGER_ENTRY_TYPE_CARD_DEBIT",
		8: "LEDGER_ENTRY_TYPE_CARD_REFUND",
	}
	LedgerEntryType_value = map[string]int32{
		"LEDGER_ENTRY_TYPE_UNSPECIFIED": 0,
		"LEDGER_ENTRY_TYPE_DEPOSIT":     1,
		"LEDGER_ENTRY_TYPE_WITHDRAWAL":  2,
		"LEDGER_ENTRY_TYPE_TRADE":       3,
		"LEDGER_ENTRY_TYPE_FEE":         4,
		"LEDGER_ENTRY_TYPE_CONVERT":     5,
		"LEDGER_ENTRY_TYPE_REWARD":      6,
		"LEDGER_ENTRY_TYPE_CARD_DEBIT":  7,
		"LEDGER_ENTRY_TYPE_CARD_REFUND": 8,
	}
)

func (x LedgerEntryType) Enum() *LedgerEntryType {
	p := new(LedgerEntryType)
	*p = x
	return p
}

func (x LedgerEntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerEntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_account_data_service_proto_enumTypes[1].Descriptor()
}

func (LedgerEntryType) Type() protoreflect.EnumType {
	return &file_cas_v1_account_data_service_proto_enumTypes[1]
}

func (x LedgerEntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerEntryType.Descriptor instead.
func (LedgerEntryType) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_account_data_service_proto_rawDescGZIP(), []int{1}
}

// Leg of an operation.
type LedgerLeg int32

const (
	LedgerLeg_LEDGER_LEG_UNSPECIFIED LedgerLeg = 0
	LedgerLeg_LEDGER_LEG_SINGLE      LedgerLeg = 1
	LedgerLeg_LEDGER_LEG_BASE        LedgerLeg = 2
	LedgerLeg_LEDGER_LEG_QUOTE       LedgerLeg = 3
	LedgerLeg_LEDGER_LEG_FEE         LedgerLeg = 4
)

// Enum value maps for LedgerLeg.
var (
	LedgerLeg_name = map[int32]string{
		0: "LEDGER_LEG_UNSPECIFIED",
		1: "LEDGER_LEG_SINGLE",
		2: "LEDGER_LEG_BASE",
		3: "LEDGER_LEG_QUOTE",
		4: "LEDGER_LEG_FEE",
	}
	LedgerLeg_value = map[string]int32{
		"LEDGER_LEG_UNSPECIFIED": 0,
		"LEDGER_LEG_SINGLE":      1,
		"LEDGER_LEG_BASE":        2,
		"LEDGER_LEG_QUOTE":       3,
		"LEDGER_LEG_FEE":         4,
	}
)

func (x LedgerLeg) Enum() *LedgerLeg {
	p := new(LedgerLeg)
	*p = x
	return p
}

func (x LedgerLeg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerLeg) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_account_data_service_proto_enumTypes[2].Descriptor()
}

func (LedgerLeg) Type() protoreflect.EnumType {
	return &file_cas_v1_account_data_service_proto_enumTypes[2]
}

func (x LedgerLeg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerLeg.Descriptor instead.
func (LedgerLeg) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_account_data_service_proto_rawDescGZIP(), []int{2}
}

// Direction of a movement, from the account's point of view.
type LedgerDirection int32

const (
	LedgerDirection_LEDGER_DIRECTION_UNSPECIFIED LedgerDirection = 0
	LedgerDirection_LEDGER_DIRECTION_IN          LedgerDirection = 1
	LedgerDirection_LEDGER_DIRECTION_OUT         LedgerDirection = 2
)

// Enum value maps for LedgerDirection.
var (
	LedgerDirection_name = map[int32]string{
		0: "LEDGER_DIRECTION_UNSPECIFIED",
		1: "LEDGER_DIRECTION_IN",
		2: "LEDGER_DIRECTION_OUT",
	}
	LedgerDirection_value = map[string]int32{
		"LEDGER_DIRECTION_UNSPECIFIED": 0,
		"LEDGER_DIRECTION_IN":          1,
		"LEDGER_DIRECTION_OUT":         2,
	}
)

func (x LedgerDirection) Enum() *LedgerDirection {
	p := new(LedgerDirection)
	*p = x
	return p
}

func (x LedgerDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_account_data_service_proto_enumTypes[3].Descriptor()
}

func (LedgerDirection) Type() protoreflect.EnumType {
	return &file_cas_v1_account_data_service_proto_enumTypes[3]
}

func (x LedgerDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerDirection.Descriptor instead.
func (LedgerDirection) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_account_data_service_proto_rawDescGZIP(), []int{3}
}

// Freshness of the balances of one connection.
type ConnectionSnapshot struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Source code.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Time of the returned snapshot. Absent before the first successful sync.
	AsOf *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	// True when the last successful run of the balance stream is older than `stale_after`, or when there was none.
	Stale         bool `protobuf:"varint,4,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionSnapshot) Reset() {
	*x = ConnectionSnapshot{}
	mi := &file_cas_v1_account_data_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionSnapshot) ProtoMessage() {}

func (x *ConnectionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_account_data_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionSnapshot.ProtoReflect.Descriptor instead.
func (*ConnectionSnapshot) Descriptor() ([]byte, []int) {
	return file_cas_v1_account_data_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionSnapshot) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionSnapshot) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ConnectionSnapshot) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

func (x *ConnectionSnapshot) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

// Balance of one asset in one account type.
type Balance struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	AccountType  AccountType            `protobuf:"varint,2,opt,name=account_type,json=accountType,proto3,enum=cas.v1.AccountType" json:"account_type,omitempty"`
	// Canonical asset.
	Asset string `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	// Code or token address at the source.
	NativeAsset string `protobuf:"bytes,4,opt,name=native_asset,json=nativeAsset,proto3" json:"native_asset,omitempty"`
	// Decimal string: available amount.
	Free string `protobuf:"bytes,5,opt,name=free,proto3" json:"free,omitempty"`
	// Decimal string: amount in orders or lock-up.
	Locked        string `protobuf:"bytes,6,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_cas_v1_account_data_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_account_data_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_cas_v1_account_data_service_proto_rawDescGZIP(), []int{1}
}

func (x *Balance) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Balance) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *Balance) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Balance) GetNativeAsset() string {
	if x != nil {
		return x.NativeAsset
	}
	return ""
}

func (x *Balance) GetFree() string {
	if x != nil {
		return x.Free
	}
	return ""
}

func (x *Balance) GetLocked() string {
	if x != nil {
		return x.Locked
	}
	return ""
}

type GetBalancesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: exactly one.
	//
	// Types that are valid to be assigned to Selector:
	//
	//	*GetBalancesRequest_OwnerRef
	//	*GetBalancesRequest_ConnectionId
	Selector      isGetBalancesRequest_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesRequest) Reset() {
	*x = GetBalancesRequest{}
	mi := &file_cas_v1_account_data_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesRequest) ProtoMessage() {}

func (x *GetBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_account_data_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetBalancesRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_account_data_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalancesRequest) GetSelector() isGetBalancesRequest_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *GetBalancesRequest) GetOwnerRef() string {
	if x != nil {
		if x, ok := x.Selector.(*GetBalancesRequest_OwnerRef); ok {
			return x.OwnerRef
		}
	}
	return ""
}

func (x *GetBalancesRequest) GetConnectionId() string {
	if x != nil {
		if x, ok := x.Selector.(*GetBalancesRequest_ConnectionId); ok {
			return x.ConnectionId
		}
	}
	return ""
}

type isGetBalancesRequest_Selector interface {
	isGetBalancesRequest_Selector()
}

type GetBalancesRequest_OwnerRef struct {
	// All connections of the owner.
	OwnerRef string `protobuf:"bytes,1,opt,name=owner_ref,json=ownerRef,proto3,oneof"`
}

type GetBalancesRequest_ConnectionId struct {
	// One connection.
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3,oneof"`
}

func (*GetBalancesRequest_OwnerRef) isGetBalancesRequest_Selector() {}

func (*GetBalancesRequest_ConnectionId) isGetBalancesRequest_Selector() {}

type GetBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*ConnectionSnapshot  `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	Balances      []*Balance             `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesResponse) Reset() {
	*x = GetBalancesResponse{}
	mi := &file_cas_v1_account_data_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesResponse) ProtoMessage() {}

func (x *GetBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_account_data_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetBalancesResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_account_data_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalancesResponse) GetConnections() []*ConnectionSnapshot {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *GetBalancesResponse) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

// One immutable movement of one asset.
type LedgerEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Position in the order of arrival. Grows only.
	Seq          int64           `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ConnectionId string          `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Type         LedgerEntryType `protobuf:"varint,3,opt,name=type,proto3,enum=cas.v1.LedgerEntryType" json:"type,omitempty"`
	Leg          LedgerLeg       `protobuf:"varint,4,opt,name=leg,proto3,enum=cas.v1.LedgerLeg" json:"leg,omitempty"`
	Direction    LedgerDirection `protobuf:"varint,5,opt,name=direction,proto3,enum=cas.v1.LedgerDirection" json:"direction,omitempty"`
	// Canonical asset.
	Asset string `protobuf:"bytes,6,opt,name=asset,proto3" json:"asset,omitempty"`
	// Code or token address at the source.
	NativeAsset string `protobuf:"bytes,7,opt,name=native_asset,json=nativeAsset,proto3" json:"native_asset,omitempty"`
	// Decimal string, always positive.
	Amount string `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount,omitempty"`
	// Same for all legs of one operation.
	GroupId string `protobuf:"bytes,9,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// ID at the source.
	ExternalId string `protobuf:"bytes,10,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// Time at the source.
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_cas_v1_account_data_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_account_data_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_cas_v1_account_data_service_proto_rawDescGZIP(), []int{4}
}

func (x *LedgerEntry) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LedgerEntry) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *LedgerEntry) GetType() LedgerEntryType {
	if x != nil {
		return x.Type
	}
	return LedgerEntryType_LEDGER_ENTRY_TYPE_UNSPECIFIED
}

func (x *LedgerEntry) GetLeg() LedgerLeg {
	if x != nil {
		return x.Leg
	}
	return LedgerLeg_LEDGER_LEG_UNSPECIFIED
}

func (x *LedgerEntry) GetDirection() LedgerDirection {
	if x != nil {
		return x.Direction
	}
	return LedgerDirection_LEDGER_DIRECTION_UNSPECIFIED
}

func (x *LedgerEntry) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *LedgerEntry) GetNativeAsset() string {
	if x != nil {
		return x.NativeAsset
	}
	return ""
}

func (x *LedgerEntry) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *LedgerEntry) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *LedgerEntry) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *LedgerEntry) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ListLedgerEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter.
	OwnerRef string `protobuf:"bytes,1,opt,name=owner_ref,json=ownerRef,proto3" json:"owner_ref,omitempty"`
	// Optional filter. Unknown in the tenant: NOT_FOUND.
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Entries with `seq` above this value are returned.
	AfterSeq int64 `protobuf:"varint,3,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	// Optional filter.
	Types []LedgerEntryType `protobuf:"varint,4,rep,packed,name=types,proto3,enum=cas.v1.LedgerEntryType" json:"types,omitempty"`
	// Optional filter, inclusive.
	OccurredFrom *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_from,json=occurredFrom,proto3" json:"occurred_from,omitempty"`
	// Optional filter, exclusive.
	OccurredTo *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_to,json=occurredTo,proto3" json:"occurred_to,omitempty"`
	// 100 when 0; at most 500.
	PageSize      int32 `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerEntriesRequest) Reset() {
	*x = ListLedgerEntriesRequest{}
	mi := &file_cas_v1_account_data_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerEntriesRequest) ProtoMessage() {}

func (x *ListLedgerEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_account_data_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListLedgerEntriesRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_account_data_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListLedgerEntriesRequest) GetOwnerRef() string {
	if x != nil {
		return x.OwnerRef
	}
	return ""
}

func (x *ListLedgerEntriesRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ListLedgerEntriesRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *ListLedgerEntriesRequest) GetTypes() []LedgerEntryType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ListLedgerEntriesRequest) GetOccurredFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredFrom
	}
	return nil
}

func (x *ListLedgerEntriesRequest) GetOccurredTo() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredTo
	}
	return nil
}

func (x *ListLedgerEntriesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListLedgerEntriesResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*LedgerEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Highest `seq` of the response; the next `after_seq`. An empty response returns the `after_seq` of the request.
	LastSeq int64 `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	// More entries exist after `last_seq`.
	HasMore       bool `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerEntriesResponse) Reset() {
	*x = ListLedgerEntriesResponse{}
	mi := &file_cas_v1_account_data_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerEntriesResponse) ProtoMessage() {}

func (x *ListLedgerEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_account_data_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListLedgerEntriesResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_account_data_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListLedgerEntriesResponse) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListLedgerEntriesResponse) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *ListLedgerEntriesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_cas_v1_account_data_service_proto protoreflect.FileDescriptor

const file_cas_v1_account_data_service_proto_rawDesc = "" +
	"\n" +
	"!cas/v1/account_data_service.proto\x12\x06cas.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x01\n" +
	"\x12ConnectionSnapshot\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12/\n" +
	"\x05as_of\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\x12\x14\n" +
	"\x05stale\x18\x04 \x01(\bR\x05stale\"\xcb\x01\n" +
	"\aBalance\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x126\n" +
	"\faccount_type\x18\x02 \x01(\x0e2\x13.cas.v1.AccountTypeR\vaccountType\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12!\n" +
	"\fnative_asset\x18\x04 \x01(\tR\vnativeAsset\x12\x12\n" +
	"\x04free\x18\x05 \x01(\tR\x04free\x12\x16\n" +
	"\x06locked\x18\x06 \x01(\tR\x06locked\"f\n" +
	"\x12GetBalancesRequest\x12\x1d\n" +
	"\towner_ref\x18\x01 \x01(\tH\x00R\bownerRef\x12%\n" +
	"\rconnection_id\x18\x02 \x01(\tH\x00R\fconnectionIdB\n" +
	"\n" +
	"\bselector\"\x80\x01\n" +
	"\x13GetBalancesResponse\x12<\n" +
	"\vconnections\x18\x01 \x03(\v2\x1a.cas.v1.ConnectionSnapshotR\vconnections\x12+\n" +
	"\bbalances\x18\x02 \x03(\v2\x0f.cas.v1.BalanceR\bbalances\"\x97\x03\n" +
	"\vLedgerEntry\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.cas.v1.LedgerEntryTypeR\x04type\x12#\n" +
	"\x03leg\x18\x04 \x01(\x0e2\x11.cas.v1.LedgerLegR\x03leg\x125\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x17.cas.v1.LedgerDirectionR\tdirection\x12\x14\n" +
	"\x05asset\x18\x06 \x01(\tR\x05asset\x12!\n" +
	"\fnative_asset\x18\a \x01(\tR\vnativeAsset\x12\x16\n" +
	"\x06amount\x18\b \x01(\tR\x06amount\x12\x19\n" +
	"\bgroup_id\x18\t \x01(\tR\agroupId\x12\x1f\n" +
	"\vexternal_id\x18\n" +
	" \x01(\tR\n" +
	"externalId\x12;\n" +
	"\voccurred_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xc3\x02\n" +
	"\x18ListLedgerEntriesRequest\x12\x1b\n" +
	"\towner_ref\x18\x01 \x01(\tR\bownerRef\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x1b\n" +
	"\tafter_seq\x18\x03 \x01(\x03R\bafterSeq\x12-\n" +
	"\x05types\x18\x04 \x03(\x0e2\x17.cas.v1.LedgerEntryTypeR\x05types\x12?\n" +
	"\roccurred_from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\foccurredFrom\x12;\n" +
	"\voccurred_to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredTo\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"\x80\x01\n" +
	"\x19ListLedgerEntriesResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.cas.v1.LedgerEntryR\aentries\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x03R\alastSeq\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore*\xb3\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACCOUNT_TYPE_SPOT\x10\x01\x12\x18\n" +
	"\x14ACCOUNT_TYPE_FUNDING\x10\x02\x12\x1e\n" +
	"\x1aACCOUNT_TYPE_EARN_FLEXIBLE\x10\x03\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_EARN_LOCKED\x10\x04\x12\x17\n" +
	"\x13ACCOUNT_TYPE_WALLET\x10\x05*\xaf\x02\n" +
	"\x0fLedgerEntryType\x12!\n" +
	"\x1dLEDGER_ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19LEDGER_ENTRY_TYPE_DEPOSIT\x10\x01\x12 \n" +
	"\x1cLEDGER_ENTRY_TYPE_WITHDRAWAL\x10\x02\x12\x1b\n" +
	"\x17LEDGER_ENTRY_TYPE_TRADE\x10\x03\x12\x19\n" +
	"\x15LEDGER_ENTRY_TYPE_FEE\x10\x04\x12\x1d\n" +
	"\x19LEDGER_ENTRY_TYPE_CONVERT\x10\x05\x12\x1c\n" +
	"\x18LEDGER_ENTRY_TYPE_REWARD\x10\x06\x12 \n" +
	"\x1cLEDGER_ENTRY_TYPE_CARD_DEBIT\x10\a\x12!\n" +
	"\x1dLEDGER_ENTRY_TYPE_CARD_REFUND\x10\b*}\n" +
	"\tLedgerLeg\x12\x1a\n" +
	"\x16LEDGER_LEG_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LEDGER_LEG_SINGLE\x10\x01\x12\x13\n" +
	"\x0fLEDGER_LEG_BASE\x10\x02\x12\x14\n" +
	"\x10LEDGER_LEG_QUOTE\x10\x03\x12\x12\n" +
	"\x0eLEDGER_LEG_FEE\x10\x04*f\n" +
	"\x0fLedgerDirection\x12 \n" +
	"\x1cLEDGER_DIRECTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13LEDGER_DIRECTION_IN\x10\x01\x12\x18\n" +
	"\x14LEDGER_DIRECTION_OUT\x10\x022\xb6\x01\n" +
	"\x12AccountDataService\x12F\n" +
	"\vGetBalances\x12\x1a.cas.v1.GetBalancesRequest\x1a\x1b.cas.v1.GetBalancesResponse\x12X\n" +
	"\x11ListLedgerEntries\x12 .cas.v1.ListLedgerEntriesRequest\x1a!.cas.v1.ListLedgerEntriesResponseBKZIgithub.com/DigitLock/crypto-account-service/internal/grpc/pb/cas/v1;casv1b\x06proto3"

var (
	file_cas_v1_account_data_service_proto_rawDescOnce sync.Once
	file_cas_v1_account_data_service_proto_rawDescData []byte
)

func file_cas_v1_account_data_service_proto_rawDescGZIP() []byte {
	file_cas_v1_account_data_service_proto_rawDescOnce.Do(func() {
		file_cas_v1_account_data_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cas_v1_account_data_service_proto_rawDesc), len(file_cas_v1_account_data_service_proto_rawDesc)))
	})
	return file_cas_v1_account_data_service_proto_rawDescData
}

var file_cas_v1_account_data_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cas_v1_account_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cas_v1_account_data_service_proto_goTypes = []any{
	(AccountType)(0),                  // 0: cas.v1.AccountType
	(LedgerEntryType)(0),              // 1: cas.v1.LedgerEntryType
	(LedgerLeg)(0),                    // 2: cas.v1.LedgerLeg
	(LedgerDirection)(0),              // 3: cas.v1.LedgerDirection
	(*ConnectionSnapshot)(nil),        // 4: cas.v1.ConnectionSnapshot
	(*Balance)(nil),                   // 5: cas.v1.Balance
	(*GetBalancesRequest)(nil),        // 6: cas.v1.GetBalancesRequest
	(*GetBalancesResponse)(nil),       // 7: cas.v1.GetBalancesResponse
	(*LedgerEntry)(nil),               // 8: cas.v1.LedgerEntry
	(*ListLedgerEntriesRequest)(nil),  // 9: cas.v1.ListLedgerEntriesRequest
	(*ListLedgerEntriesResponse)(nil), // 10: cas.v1.ListLedgerEntriesResponse
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_cas_v1_account_data_service_proto_depIdxs = []int32{
	11, // 0: cas.v1.ConnectionSnapshot.as_of:type_name -> google.protobuf.Timestamp
	0,  // 1: cas.v1.Balance.account_type:type_name -> cas.v1.AccountType
	4,  // 2: cas.v1.GetBalancesResponse.connections:type_name -> cas.v1.ConnectionSnapshot
	5,  // 3: cas.v1.GetBalancesResponse.balances:type_name -> cas.v1.Balance
	1,  // 4: cas.v1.LedgerEntry.type:type_name -> cas.v1.LedgerEntryType
	2,  // 5: cas.v1.LedgerEntry.leg:type_name -> cas.v1.LedgerLeg
	3,  // 6: cas.v1.LedgerEntry.direction:type_name -> cas.v1.LedgerDirection
	11, // 7: cas.v1.LedgerEntry.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 8: cas.v1.ListLedgerEntriesRequest.types:type_name -> cas.v1.LedgerEntryType
	11, // 9: cas.v1.ListLedgerEntriesRequest.occurred_from:type_name -> google.protobuf.Timestamp
	11, // 10: cas.v1.ListLedgerEntriesRequest.occurred_to:type_name -> google.protobuf.Timestamp
	8,  // 11: cas.v1.ListLedgerEntriesResponse.entries:type_name -> cas.v1.LedgerEntry
	6,  // 12: cas.v1.AccountDataService.GetBalances:input_type -> cas.v1.GetBalancesRequest
	9,  // 13: cas.v1.AccountDataService.ListLedgerEntries:input_type -> cas.v1.ListLedgerEntriesRequest
	7,  // 14: cas.v1.AccountDataService.GetBalances:output_type -> cas.v1.GetBalancesResponse
	10, // 15: cas.v1.AccountDataService.ListLedgerEntries:output_type -> cas.v1.ListLedgerEntriesResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cas_v1_account_data_service_proto_init() }
func file_cas_v1_account_data_service_proto_init() {
	if File_cas_v1_account_data_service_proto != nil {
		return
	}
	file_cas_v1_account_data_service_proto_msgTypes[2].OneofWrappers = []any{
		(*GetBalancesRequest_OwnerRef)(nil),
		(*GetBalancesRequest_ConnectionId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cas_v1_account_data_service_proto_rawDesc), len(file_cas_v1_account_data_service_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cas_v1_account_data_service_proto_goTypes,
		DependencyIndexes: file_cas_v1_account_data_service_proto_depIdxs,
		EnumInfos:         file_cas_v1_account_data_service_proto_enumTypes,
		MessageInfos:      file_cas_v1_account_data_service_proto_msgTypes,
	}.Build()
	File_cas_v1_account_data_service_proto = out.File
	file_cas_v1_account_data_service_proto_goTypes = nil
	file_cas_v1_account_data_service_proto_depIdxs = nil
}
