// Contract of Crypto Account Service: cards, authorizations and reconciliation runs.
// Specification: docs/srs/core.md §2.1.1, §2.1.5; docs/srs/card-spend.md §2.1.4, UC-4.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cas/v1/card_service.proto

package casv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CardService_RegisterCard_FullMethodName            = "/cas.v1.CardService/RegisterCard"
	CardService_UpdateCard_FullMethodName              = "/cas.v1.CardService/UpdateCard"
	CardService_GetCard_FullMethodName                 = "/cas.v1.CardService/GetCard"
	CardService_ListCards_FullMethodName               = "/cas.v1.CardService/ListCards"
	CardService_GetAuthorization_FullMethodName        = "/cas.v1.CardService/GetAuthorization"
	CardService_ListAuthorizations_FullMethodName      = "/cas.v1.CardService/ListAuthorizations"
	CardService_GetReconciliationReport_FullMethodName = "/cas.v1.CardService/GetReconciliationReport"
)

// CardServiceClient is the client API for CardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CardService manages the card registry of the caller's tenant and reads its authorizations.
// Every method needs the metadata `authorization: Bearer <service token>`.
type CardServiceClient interface {
	// RegisterCard binds a card_ref to a wallet connection. The same request repeated returns the existing card.
	// ALREADY_EXISTS for a known card_ref with a different body.
	// FAILED_PRECONDITION reason: CONNECTION_NOT_USABLE.
	RegisterCard(ctx context.Context, in *RegisterCardRequest, opts ...grpc.CallOption) (*RegisterCardResponse, error)
	// UpdateCard changes the daily limit, or freezes or unfreezes a card. At least one optional field is required.
	UpdateCard(ctx context.Context, in *UpdateCardRequest, opts ...grpc.CallOption) (*UpdateCardResponse, error)
	// GetCard returns one card.
	GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardResponse, error)
	// ListCards returns the cards of the tenant, ordered by creation time and card_ref.
	ListCards(ctx context.Context, in *ListCardsRequest, opts ...grpc.CallOption) (*ListCardsResponse, error)
	// GetAuthorization returns one authorization with its returns and status history. A tombstone is returned too.
	GetAuthorization(ctx context.Context, in *GetAuthorizationRequest, opts ...grpc.CallOption) (*GetAuthorizationResponse, error)
	// ListAuthorizations returns authorizations without returns and history, newest first.
	ListAuthorizations(ctx context.Context, in *ListAuthorizationsRequest, opts ...grpc.CallOption) (*ListAuthorizationsResponse, error)
	// GetReconciliationReport returns one reconciliation run of the tenant on a source (SRS — Core §2.1.1). From S3.
	// INVALID_ARGUMENT: source empty, or run_id malformed. NOT_FOUND: unknown source; a run_id of another tenant or
	// another source; no run at all.
	GetReconciliationReport(ctx context.Context, in *GetReconciliationReportRequest, opts ...grpc.CallOption) (*GetReconciliationReportResponse, error)
}

type cardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCardServiceClient(cc grpc.ClientConnInterface) CardServiceClient {
	return &cardServiceClient{cc}
}

func (c *cardServiceClient) RegisterCard(ctx context.Context, in *RegisterCardRequest, opts ...grpc.CallOption) (*RegisterCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCardResponse)
	err := c.cc.Invoke(ctx, CardService_RegisterCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) UpdateCard(ctx context.Context, in *UpdateCardRequest, opts ...grpc.CallOption) (*UpdateCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCardResponse)
	err := c.cc.Invoke(ctx, CardService_UpdateCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCardResponse)
	err := c.cc.Invoke(ctx, CardService_GetCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) ListCards(ctx context.Context, in *ListCardsRequest, opts ...grpc.CallOption) (*ListCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCardsResponse)
	err := c.cc.Invoke(ctx, CardService_ListCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) GetAuthorization(ctx context.Context, in *GetAuthorizationRequest, opts ...grpc.CallOption) (*GetAuthorizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthorizationResponse)
	err := c.cc.Invoke(ctx, CardService_GetAuthorization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) ListAuthorizations(ctx context.Context, in *ListAuthorizationsRequest, opts ...grpc.CallOption) (*ListAuthorizationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuthorizationsResponse)
	err := c.cc.Invoke(ctx, CardService_ListAuthorizations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) GetReconciliationReport(ctx context.Context, in *GetReconciliationReportRequest, opts ...grpc.CallOption) (*GetReconciliationReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReconciliationReportResponse)
	err := c.cc.Invoke(ctx, CardService_GetReconciliationReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardServiceServer is the server API for CardService service.
// All implementations must embed UnimplementedCardServiceServer
// for forward compatibility.
//
// CardService manages the card registry of the caller's tenant and reads its authorizations.
// Every method needs the metadata `authorization: Bearer <service token>`.
type CardServiceServer interface {
	// RegisterCard binds a card_ref to a wallet connection. The same request repeated returns the existing card.
	// ALREADY_EXISTS for a known card_ref with a different body.
	// FAILED_PRECONDITION reason: CONNECTION_NOT_USABLE.
	RegisterCard(context.Context, *RegisterCardRequest) (*RegisterCardResponse, error)
	// UpdateCard changes the daily limit, or freezes or unfreezes a card. At least one optional field is required.
	UpdateCard(context.Context, *UpdateCardRequest) (*UpdateCardResponse, error)
	// GetCard returns one card.
	GetCard(context.Context, *GetCardRequest) (*GetCardResponse, error)
	// ListCards returns the cards of the tenant, ordered by creation time and card_ref.
	ListCards(context.Context, *ListCardsRequest) (*ListCardsResponse, error)
	// GetAuthorization returns one authorization with its returns and status history. A tombstone is returned too.
	GetAuthorization(context.Context, *GetAuthorizationRequest) (*GetAuthorizationResponse, error)
	// ListAuthorizations returns authorizations without returns and history, newest first.
	ListAuthorizations(context.Context, *ListAuthorizationsRequest) (*ListAuthorizationsResponse, error)
	// GetReconciliationReport returns one reconciliation run of the tenant on a source (SRS — Core §2.1.1). From S3.
	// INVALID_ARGUMENT: source empty, or run_id malformed. NOT_FOUND: unknown source; a run_id of another tenant or
	// another source; no run at all.
	GetReconciliationReport(context.Context, *GetReconciliationReportRequest) (*GetReconciliationReportResponse, error)
	mustEmbedUnimplementedCardServiceServer()
}

// UnimplementedCardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCardServiceServer struct{}

func (UnimplementedCardServiceServer) RegisterCard(context.Context, *RegisterCardRequest) (*RegisterCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCard not implemented")
}
func (UnimplementedCardServiceServer) UpdateCard(context.Context, *UpdateCardRequest) (*UpdateCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCard not implemented")
}
func (UnimplementedCardServiceServer) GetCard(context.Context, *GetCardRequest) (*GetCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedCardServiceServer) ListCards(context.Context, *ListCardsRequest) (*ListCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCards not implemented")
}
func (UnimplementedCardServiceServer) GetAuthorization(context.Context, *GetAuthorizationRequest) (*GetAuthorizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthorization not implemented")
}
func (UnimplementedCardServiceServer) ListAuthorizations(context.Context, *ListAuthorizationsRequest) (*ListAuthorizationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuthorizations not implemented")
}
func (UnimplementedCardServiceServer) GetReconciliationReport(context.Context, *GetReconciliationReportRequest) (*GetReconciliationReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReconciliationReport not implemented")
}
func (UnimplementedCardServiceServer) mustEmbedUnimplementedCardServiceServer() {}
func (UnimplementedCardServiceServer) testEmbeddedByValue()                     {}

// UnsafeCardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardServiceServer will
// result in compilation errors.
type UnsafeCardServiceServer interface {
	mustEmbedUnimplementedCardServiceServer()
}

func RegisterCardServiceServer(s grpc.ServiceRegistrar, srv CardServiceServer) {
	// If the following call panics, it indicates UnimplementedCardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CardService_ServiceDesc, srv)
}

func _CardService_RegisterCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).RegisterCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_RegisterCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).RegisterCard(ctx, req.(*RegisterCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_UpdateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).UpdateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_UpdateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).UpdateCard(ctx, req.(*UpdateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_GetCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).GetCard(ctx, req.(*GetCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_ListCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).ListCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_ListCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).ListCards(ctx, req.(*ListCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_GetAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).GetAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_GetAuthorization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).GetAuthorization(ctx, req.(*GetAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_ListAuthorizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuthorizationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).ListAuthorizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_ListAuthorizations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).ListAuthorizations(ctx, req.(*ListAuthorizationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_GetReconciliationReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReconciliationReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).GetReconciliationReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardService_GetReconciliationReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).GetReconciliationReport(ctx, req.(*GetReconciliationReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CardService_ServiceDesc is the grpc.ServiceDesc for CardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cas.v1.CardService",
	HandlerType: (*CardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCard",
			Handler:    _CardService_RegisterCard_Handler,
		},
		{
			MethodName: "UpdateCard",
			Handler:    _CardService_UpdateCard_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _CardService_GetCard_Handler,
		},
		{
			MethodName: "ListCards",
			Handler:    _CardService_ListCards_Handler,
		},
		{
			MethodName: "GetAuthorization",
			Handler:    _CardService_GetAuthorization_Handler,
		},
		{
			MethodName: "ListAuthorizations",
			Handler:    _CardService_ListAuthorizations_Handler,
		},
		{
			MethodName: "GetReconciliationReport",
			Handler:    _CardService_GetReconciliationReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cas/v1/card_service.proto",
}
