// Contract of Crypto Account Service: cards and authorizations.
// Specification: docs/srs/core.md §2.1.1, §2.1.5; docs/srs/card-spend.md §2.1.4.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cas/v1/card_service.proto

package casv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State of a card.
type CardStatus int32

const (
	CardStatus_CARD_STATUS_UNSPECIFIED CardStatus = 0
	// Authorizations are decided.
	CardStatus_CARD_STATUS_ACTIVE CardStatus = 1
	// Authorizations are declined with CARD_FROZEN.
	CardStatus_CARD_STATUS_FROZEN CardStatus = 2
)

// Enum value maps for CardStatus.
var (
	CardStatus_name = map[int32]string{
		0: "CARD_STATUS_UNSPECIFIED",
		1: "CARD_STATUS_ACTIVE",
		2: "CARD_STATUS_FROZEN",
	}
	CardStatus_value = map[string]int32{
		"CARD_STATUS_UNSPECIFIED": 0,
		"CARD_STATUS_ACTIVE":      1,
		"CARD_STATUS_FROZEN":      2,
	}
)

func (x CardStatus) Enum() *CardStatus {
	p := new(CardStatus)
	*p = x
	return p
}

func (x CardStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_card_service_proto_enumTypes[0].Descriptor()
}

func (CardStatus) Type() protoreflect.EnumType {
	return &file_cas_v1_card_service_proto_enumTypes[0]
}

func (x CardStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardStatus.Descriptor instead.
func (CardStatus) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{0}
}

// State of an authorization (SRS — Card Spend §2.3.1).
type AuthorizationStatus int32

const (
	AuthorizationStatus_AUTHORIZATION_STATUS_UNSPECIFIED AuthorizationStatus = 0
	// Stored, checks running.
	AuthorizationStatus_AUTHORIZATION_STATUS_RECEIVED AuthorizationStatus = 1
	// Debit sent, decision pending.
	AuthorizationStatus_AUTHORIZATION_STATUS_DEBIT_SUBMITTED AuthorizationStatus = 2
	// Debit included or preconfirmed. The processor was told: approved.
	AuthorizationStatus_AUTHORIZATION_STATUS_APPROVED AuthorizationStatus = 3
	// Debit is final by the finality rule of the network.
	AuthorizationStatus_AUTHORIZATION_STATUS_DEBIT_CONFIRMED AuthorizationStatus = 4
	// No tokens moved. The processor was told: declined.
	AuthorizationStatus_AUTHORIZATION_STATUS_DECLINED AuthorizationStatus = 5
	// Decline sent at the deadline; debit outcome not known yet.
	AuthorizationStatus_AUTHORIZATION_STATUS_TIMED_OUT AuthorizationStatus = 6
	// Debit landed after the decline; automatic return in progress.
	AuthorizationStatus_AUTHORIZATION_STATUS_LATE_DEBIT AuthorizationStatus = 7
	// Late debit fully returned.
	AuthorizationStatus_AUTHORIZATION_STATUS_LATE_DEBIT_REFUNDED AuthorizationStatus = 8
	// Approved debit dropped and could not be repeated.
	AuthorizationStatus_AUTHORIZATION_STATUS_DEBIT_LOST AuthorizationStatus = 9
)

// Enum value maps for AuthorizationStatus.
var (
	AuthorizationStatus_name = map[int32]string{
		0: "AUTHORIZATION_STATUS_UNSPECIFIED",
		1: "AUTHORIZATION_STATUS_RECEIVED",
		2: "AUTHORIZATION_STATUS_DEBIT_SUBMITTED",
		3: "AUTHORIZATION_STATUS_APPROVED",
		4: "AUTHORIZATION_STATUS_DEBIT_CONFIRMED",
		5: "AUTHORIZATION_STATUS_DECLINED",
		6: "AUTHORIZATION_STATUS_TIMED_OUT",
		7: "AUTHORIZATION_STATUS_LATE_DEBIT",
		8: "AUTHORIZATION_STATUS_LATE_DEBIT_REFUNDED",
		9: "AUTHORIZATION_STATUS_DEBIT_LOST",
	}
	AuthorizationStatus_value = map[string]int32{
		"AUTHORIZATION_STATUS_UNSPECIFIED":         0,
		"AUTHORIZATION_STATUS_RECEIVED":            1,
		"AUTHORIZATION_STATUS_DEBIT_SUBMITTED":     2,
		"AUTHORIZATION_STATUS_APPROVED":            3,
		"AUTHORIZATION_STATUS_DEBIT_CONFIRMED":     4,
		"AUTHORIZATION_STATUS_DECLINED":            5,
		"AUTHORIZATION_STATUS_TIMED_OUT":           6,
		"AUTHORIZATION_STATUS_LATE_DEBIT":          7,
		"AUTHORIZATION_STATUS_LATE_DEBIT_REFUNDED": 8,
		"AUTHORIZATION_STATUS_DEBIT_LOST":          9,
	}
)

func (x AuthorizationStatus) Enum() *AuthorizationStatus {
	p := new(AuthorizationStatus)
	*p = x
	return p
}

func (x AuthorizationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_card_service_proto_enumTypes[1].Descriptor()
}

func (AuthorizationStatus) Type() protoreflect.EnumType {
	return &file_cas_v1_card_service_proto_enumTypes[1]
}

func (x AuthorizationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationStatus.Descriptor instead.
func (AuthorizationStatus) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{1}
}

// Reason of a decline (SRS — Card Spend §2.1.2).
type DeclineReason int32

const (
	DeclineReason_DECLINE_REASON_UNSPECIFIED DeclineReason = 0
	// card_ref is unknown for the tenant.
	DeclineReason_DECLINE_REASON_CARD_NOT_FOUND DeclineReason = 1
	// Card status is FROZEN.
	DeclineReason_DECLINE_REASON_CARD_FROZEN DeclineReason = 2
	// The contract is paused.
	DeclineReason_DECLINE_REASON_PROGRAM_PAUSED DeclineReason = 3
	// No rate pair for the currency.
	DeclineReason_DECLINE_REASON_CURRENCY_NOT_SUPPORTED DeclineReason = 4
	// CRS is unavailable, answers after the rate budget, or marks the rate outdated.
	DeclineReason_DECLINE_REASON_RATE_UNAVAILABLE DeclineReason = 5
	// Card daily limit or wallet daily limit would be exceeded.
	DeclineReason_DECLINE_REASON_LIMIT_EXCEEDED DeclineReason = 6
	// Wallet balance below the token amount.
	DeclineReason_DECLINE_REASON_INSUFFICIENT_FUNDS DeclineReason = 7
	// Allowance below the token amount.
	DeclineReason_DECLINE_REASON_INSUFFICIENT_ALLOWANCE DeclineReason = 8
	// RPC error or read timeout.
	DeclineReason_DECLINE_REASON_CHAIN_UNAVAILABLE DeclineReason = 9
	// The debit transaction reverted.
	DeclineReason_DECLINE_REASON_DEBIT_REVERTED DeclineReason = 10
	// No decision by the deadline.
	DeclineReason_DECLINE_REASON_TIMEOUT DeclineReason = 11
	// A reversal for this auth_id arrived first.
	DeclineReason_DECLINE_REASON_REVERSED_BEFORE_AUTH DeclineReason = 12
	// Unexpected failure.
	DeclineReason_DECLINE_REASON_INTERNAL_ERROR DeclineReason = 13
)

// Enum value maps for DeclineReason.
var (
	DeclineReason_name = map[int32]string{
		0:  "DECLINE_REASON_UNSPECIFIED",
		1:  "DECLINE_REASON_CARD_NOT_FOUND",
		2:  "DECLINE_REASON_CARD_FROZEN",
		3:  "DECLINE_REASON_PROGRAM_PAUSED",
		4:  "DECLINE_REASON_CURRENCY_NOT_SUPPORTED",
		5:  "DECLINE_REASON_RATE_UNAVAILABLE",
		6:  "DECLINE_REASON_LIMIT_EXCEEDED",
		7:  "DECLINE_REASON_INSUFFICIENT_FUNDS",
		8:  "DECLINE_REASON_INSUFFICIENT_ALLOWANCE",
		9:  "DECLINE_REASON_CHAIN_UNAVAILABLE",
		10: "DECLINE_REASON_DEBIT_REVERTED",
		11: "DECLINE_REASON_TIMEOUT",
		12: "DECLINE_REASON_REVERSED_BEFORE_AUTH",
		13: "DECLINE_REASON_INTERNAL_ERROR",
	}
	DeclineReason_value = map[string]int32{
		"DECLINE_REASON_UNSPECIFIED":            0,
		"DECLINE_REASON_CARD_NOT_FOUND":         1,
		"DECLINE_REASON_CARD_FROZEN":            2,
		"DECLINE_REASON_PROGRAM_PAUSED":         3,
		"DECLINE_REASON_CURRENCY_NOT_SUPPORTED": 4,
		"DECLINE_REASON_RATE_UNAVAILABLE":       5,
		"DECLINE_REASON_LIMIT_EXCEEDED":         6,
		"DECLINE_REASON_INSUFFICIENT_FUNDS":     7,
		"DECLINE_REASON_INSUFFICIENT_ALLOWANCE": 8,
		"DECLINE_REASON_CHAIN_UNAVAILABLE":      9,
		"DECLINE_REASON_DEBIT_REVERTED":         10,
		"DECLINE_REASON_TIMEOUT":                11,
		"DECLINE_REASON_REVERSED_BEFORE_AUTH":   12,
		"DECLINE_REASON_INTERNAL_ERROR":         13,
	}
)

func (x DeclineReason) Enum() *DeclineReason {
	p := new(DeclineReason)
	*p = x
	return p
}

func (x DeclineReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeclineReason) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_card_service_proto_enumTypes[2].Descriptor()
}

func (DeclineReason) Type() protoreflect.EnumType {
	return &file_cas_v1_card_service_proto_enumTypes[2]
}

func (x DeclineReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeclineReason.Descriptor instead.
func (DeclineReason) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{2}
}

// Type of a return (SRS — Card Spend §2.4 returns).
type ReturnType int32

const (
	ReturnType_RETURN_TYPE_UNSPECIFIED ReturnType = 0
	// Reversal requested by the processor.
	ReturnType_RETURN_TYPE_REVERSAL ReturnType = 1
	// Refund requested by the processor.
	ReturnType_RETURN_TYPE_REFUND ReturnType = 2
	// Automatic return of a debit that landed after the decline.
	ReturnType_RETURN_TYPE_LATE_DEBIT ReturnType = 3
)

// Enum value maps for ReturnType.
var (
	ReturnType_name = map[int32]string{
		0: "RETURN_TYPE_UNSPECIFIED",
		1: "RETURN_TYPE_REVERSAL",
		2: "RETURN_TYPE_REFUND",
		3: "RETURN_TYPE_LATE_DEBIT",
	}
	ReturnType_value = map[string]int32{
		"RETURN_TYPE_UNSPECIFIED": 0,
		"RETURN_TYPE_REVERSAL":    1,
		"RETURN_TYPE_REFUND":      2,
		"RETURN_TYPE_LATE_DEBIT":  3,
	}
)

func (x ReturnType) Enum() *ReturnType {
	p := new(ReturnType)
	*p = x
	return p
}

func (x ReturnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnType) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_card_service_proto_enumTypes[3].Descriptor()
}

func (ReturnType) Type() protoreflect.EnumType {
	return &file_cas_v1_card_service_proto_enumTypes[3]
}

func (x ReturnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnType.Descriptor instead.
func (ReturnType) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{3}
}

// State of a return (SRS — Card Spend §2.3.2).
type ReturnStatus int32

const (
	ReturnStatus_RETURN_STATUS_UNSPECIFIED ReturnStatus = 0
	// Stored; waiting for the tracker.
	ReturnStatus_RETURN_STATUS_ACCEPTED ReturnStatus = 1
	// Refund transaction sent.
	ReturnStatus_RETURN_STATUS_SUBMITTED ReturnStatus = 2
	// Refund included or preconfirmed.
	ReturnStatus_RETURN_STATUS_INCLUDED ReturnStatus = 3
	// Refund is final.
	ReturnStatus_RETURN_STATUS_CONFIRMED ReturnStatus = 4
	// Last attempt failed; will be repeated.
	ReturnStatus_RETURN_STATUS_RETRYING ReturnStatus = 5
	// Nothing to return.
	ReturnStatus_RETURN_STATUS_NOTHING_TO_RETURN ReturnStatus = 6
)

// Enum value maps for ReturnStatus.
var (
	ReturnStatus_name = map[int32]string{
		0: "RETURN_STATUS_UNSPECIFIED",
		1: "RETURN_STATUS_ACCEPTED",
		2: "RETURN_STATUS_SUBMITTED",
		3: "RETURN_STATUS_INCLUDED",
		4: "RETURN_STATUS_CONFIRMED",
		5: "RETURN_STATUS_RETRYING",
		6: "RETURN_STATUS_NOTHING_TO_RETURN",
	}
	ReturnStatus_value = map[string]int32{
		"RETURN_STATUS_UNSPECIFIED":       0,
		"RETURN_STATUS_ACCEPTED":          1,
		"RETURN_STATUS_SUBMITTED":         2,
		"RETURN_STATUS_INCLUDED":          3,
		"RETURN_STATUS_CONFIRMED":         4,
		"RETURN_STATUS_RETRYING":          5,
		"RETURN_STATUS_NOTHING_TO_RETURN": 6,
	}
)

func (x ReturnStatus) Enum() *ReturnStatus {
	p := new(ReturnStatus)
	*p = x
	return p
}

func (x ReturnStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_card_service_proto_enumTypes[4].Descriptor()
}

func (ReturnStatus) Type() protoreflect.EnumType {
	return &file_cas_v1_card_service_proto_enumTypes[4]
}

func (x ReturnStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnStatus.Descriptor instead.
func (ReturnStatus) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{4}
}

// A processor card reference bound to a wallet connection (SRS — Core §2.1.5).
type Card struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque card reference from the processor, 1 to 64 characters. No card number.
	CardRef string `protobuf:"bytes,1,opt,name=card_ref,json=cardRef,proto3" json:"card_ref,omitempty"`
	// Owner of the bound connection.
	OwnerRef string `protobuf:"bytes,2,opt,name=owner_ref,json=ownerRef,proto3" json:"owner_ref,omitempty"`
	// UUID of the bound wallet connection.
	ConnectionId string `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Address of the bound wallet in EIP-55 form.
	WalletAddress string `protobuf:"bytes,4,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	// ACTIVE or FROZEN.
	Status CardStatus `protobuf:"varint,5,opt,name=status,proto3,enum=cas.v1.CardStatus" json:"status,omitempty"`
	// Card daily limit in base units of the funding token: an integer string.
	DailyLimit string `protobuf:"bytes,6,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	// When the card was registered.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the card was last changed.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_cas_v1_card_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetCardRef() string {
	if x != nil {
		return x.CardRef
	}
	return ""
}

func (x *Card) GetOwnerRef() string {
	if x != nil {
		return x.OwnerRef
	}
	return ""
}

func (x *Card) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Card) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *Card) GetStatus() CardStatus {
	if x != nil {
		return x.Status
	}
	return CardStatus_CARD_STATUS_UNSPECIFIED
}

func (x *Card) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Card) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Rate and buffer of a quote.
type Quote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// USD per one unit of the authorization currency, a decimal string. Empty for USD.
	Rate string `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	// Buffer in basis points.
	BufferBps     int32 `protobuf:"varint,2,opt,name=buffer_bps,json=bufferBps,proto3" json:"buffer_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_cas_v1_card_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{1}
}

func (x *Quote) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *Quote) GetBufferBps() int32 {
	if x != nil {
		return x.BufferBps
	}
	return 0
}

// One reversal, refund or automatic return of an authorization.
type Return struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Processor's ID, or a generated ID for LATE_DEBIT.
	ReturnId string `protobuf:"bytes,1,opt,name=return_id,json=returnId,proto3" json:"return_id,omitempty"`
	// REVERSAL, REFUND or LATE_DEBIT.
	Type ReturnType `protobuf:"varint,2,opt,name=type,proto3,enum=cas.v1.ReturnType" json:"type,omitempty"`
	// State of the return.
	Status ReturnStatus `protobuf:"varint,3,opt,name=status,proto3,enum=cas.v1.ReturnStatus" json:"status,omitempty"`
	// Tokens to return, base units: an integer string.
	TokenAmount string `protobuf:"bytes,4,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	// Refund transaction hash. Empty before the first send and for NOTHING_TO_RETURN.
	TxHash string `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// When the return was accepted.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Return) Reset() {
	*x = Return{}
	mi := &file_cas_v1_card_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Return) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Return) ProtoMessage() {}

func (x *Return) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Return.ProtoReflect.Descriptor instead.
func (*Return) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{2}
}

func (x *Return) GetReturnId() string {
	if x != nil {
		return x.ReturnId
	}
	return ""
}

func (x *Return) GetType() ReturnType {
	if x != nil {
		return x.Type
	}
	return ReturnType_RETURN_TYPE_UNSPECIFIED
}

func (x *Return) GetStatus() ReturnStatus {
	if x != nil {
		return x.Status
	}
	return ReturnStatus_RETURN_STATUS_UNSPECIFIED
}

func (x *Return) GetTokenAmount() string {
	if x != nil {
		return x.TokenAmount
	}
	return ""
}

func (x *Return) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *Return) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// One status change of an authorization.
type StatusChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new status.
	Status AuthorizationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=cas.v1.AuthorizationStatus" json:"status,omitempty"`
	// Decline reason or cause. Empty when none.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// When the status changed.
	At            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusChange) Reset() {
	*x = StatusChange{}
	mi := &file_cas_v1_card_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusChange) ProtoMessage() {}

func (x *StatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusChange.ProtoReflect.Descriptor instead.
func (*StatusChange) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{3}
}

func (x *StatusChange) GetStatus() AuthorizationStatus {
	if x != nil {
		return x.Status
	}
	return AuthorizationStatus_AUTHORIZATION_STATUS_UNSPECIFIED
}

func (x *StatusChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StatusChange) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

// A card authorization (SRS — Card Spend §2.1.4). amount, currency, token, token_amount, quote and tx_hash are
// empty when the authorization has none, as in a tombstone.
type Authorization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Processor's authorization ID.
	AuthId string `protobuf:"bytes,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	// State of the authorization.
	Status AuthorizationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=cas.v1.AuthorizationStatus" json:"status,omitempty"`
	// Set for DECLINED and TIMED_OUT.
	DeclineReason DeclineReason `protobuf:"varint,3,opt,name=decline_reason,json=declineReason,proto3,enum=cas.v1.DeclineReason" json:"decline_reason,omitempty"`
	// Amount in currency, a decimal string.
	Amount string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// ISO 4217 code of the authorization currency.
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// Funding token symbol.
	Token string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	// Quoted amount, base units: an integer string.
	TokenAmount string `protobuf:"bytes,7,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	// Rate and buffer used. Absent when there was no quote.
	Quote *Quote `protobuf:"bytes,8,opt,name=quote,proto3" json:"quote,omitempty"`
	// Tokens debited, base units: an integer string. `0` if none.
	DebitedAmount string `protobuf:"bytes,9,opt,name=debited_amount,json=debitedAmount,proto3" json:"debited_amount,omitempty"`
	// Sum of accepted returns, base units: an integer string.
	ReturnedAmount string `protobuf:"bytes,10,opt,name=returned_amount,json=returnedAmount,proto3" json:"returned_amount,omitempty"`
	// Debit transaction hash.
	TxHash string `protobuf:"bytes,11,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// Returns of this authorization. Empty in ListAuthorizations.
	Returns []*Return `protobuf:"bytes,12,rep,name=returns,proto3" json:"returns,omitempty"`
	// Status changes in order. Empty in ListAuthorizations.
	History []*StatusChange `protobuf:"bytes,13,rep,name=history,proto3" json:"history,omitempty"`
	// Card reference of the request. Empty for a tombstone.
	CardRef string `protobuf:"bytes,14,opt,name=card_ref,json=cardRef,proto3" json:"card_ref,omitempty"`
	// When the request was received.
	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// When the decision was sent. Absent before the decision and for a tombstone.
	DecidedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authorization) Reset() {
	*x = Authorization{}
	mi := &file_cas_v1_card_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorization) ProtoMessage() {}

func (x *Authorization) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorization.ProtoReflect.Descriptor instead.
func (*Authorization) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{4}
}

func (x *Authorization) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *Authorization) GetStatus() AuthorizationStatus {
	if x != nil {
		return x.Status
	}
	return AuthorizationStatus_AUTHORIZATION_STATUS_UNSPECIFIED
}

func (x *Authorization) GetDeclineReason() DeclineReason {
	if x != nil {
		return x.DeclineReason
	}
	return DeclineReason_DECLINE_REASON_UNSPECIFIED
}

func (x *Authorization) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Authorization) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Authorization) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Authorization) GetTokenAmount() string {
	if x != nil {
		return x.TokenAmount
	}
	return ""
}

func (x *Authorization) GetQuote() *Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *Authorization) GetDebitedAmount() string {
	if x != nil {
		return x.DebitedAmount
	}
	return ""
}

func (x *Authorization) GetReturnedAmount() string {
	if x != nil {
		return x.ReturnedAmount
	}
	return ""
}

func (x *Authorization) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *Authorization) GetReturns() []*Return {
	if x != nil {
		return x.Returns
	}
	return nil
}

func (x *Authorization) GetHistory() []*StatusChange {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *Authorization) GetCardRef() string {
	if x != nil {
		return x.CardRef
	}
	return ""
}

func (x *Authorization) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *Authorization) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

type RegisterCardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required, 1 to 64 characters. Unique per tenant.
	CardRef string `protobuf:"bytes,1,opt,name=card_ref,json=cardRef,proto3" json:"card_ref,omitempty"`
	// Required. Must equal the owner of the connection.
	OwnerRef string `protobuf:"bytes,2,opt,name=owner_ref,json=ownerRef,proto3" json:"owner_ref,omitempty"`
	// Required. UUID of an ACTIVE connection of kind EVM_WALLET.
	ConnectionId string `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Required. Base-unit integer string ≥ 0, at most 78 digits.
	DailyLimit    string `protobuf:"bytes,4,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCardRequest) Reset() {
	*x = RegisterCardRequest{}
	mi := &file_cas_v1_card_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCardRequest) ProtoMessage() {}

func (x *RegisterCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCardRequest.ProtoReflect.Descriptor instead.
func (*RegisterCardRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterCardRequest) GetCardRef() string {
	if x != nil {
		return x.CardRef
	}
	return ""
}

func (x *RegisterCardRequest) GetOwnerRef() string {
	if x != nil {
		return x.OwnerRef
	}
	return ""
}

func (x *RegisterCardRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *RegisterCardRequest) GetDailyLimit() string {
	if x != nil {
		return x.DailyLimit
	}
	return ""
}

type RegisterCardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The registered card.
	Card          *Card `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCardResponse) Reset() {
	*x = RegisterCardResponse{}
	mi := &file_cas_v1_card_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCardResponse) ProtoMessage() {}

func (x *RegisterCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCardResponse.ProtoReflect.Descriptor instead.
func (*RegisterCardResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type UpdateCardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The card to change.
	CardRef string `protobuf:"bytes,1,opt,name=card_ref,json=cardRef,proto3" json:"card_ref,omitempty"`
	// Optional. New daily limit: a base-unit integer string ≥ 0.
	DailyLimit *string `protobuf:"bytes,2,opt,name=daily_limit,json=dailyLimit,proto3,oneof" json:"daily_limit,omitempty"`
	// Optional. ACTIVE or FROZEN.
	Status        *CardStatus `protobuf:"varint,3,opt,name=status,proto3,enum=cas.v1.CardStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_cas_v1_card_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCardRequest) GetCardRef() string {
	if x != nil {
		return x.CardRef
	}
	return ""
}

func (x *UpdateCardRequest) GetDailyLimit() string {
	if x != nil && x.DailyLimit != nil {
		return *x.DailyLimit
	}
	return ""
}

func (x *UpdateCardRequest) GetStatus() CardStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return CardStatus_CARD_STATUS_UNSPECIFIED
}

type UpdateCardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The card after the change.
	Card          *Card `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardResponse) Reset() {
	*x = UpdateCardResponse{}
	mi := &file_cas_v1_card_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardResponse) ProtoMessage() {}

func (x *UpdateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type GetCardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The card to read.
	CardRef       string `protobuf:"bytes,1,opt,name=card_ref,json=cardRef,proto3" json:"card_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_cas_v1_card_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetCardRequest) GetCardRef() string {
	if x != nil {
		return x.CardRef
	}
	return ""
}

type GetCardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The card.
	Card          *Card `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_cas_v1_card_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type ListCardsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter, at most 128 characters.
	OwnerRef string `protobuf:"bytes,1,opt,name=owner_ref,json=ownerRef,proto3" json:"owner_ref,omitempty"`
	// 100 when 0; at most 500.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// `next_page_token` of the previous response.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsRequest) Reset() {
	*x = ListCardsRequest{}
	mi := &file_cas_v1_card_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsRequest) ProtoMessage() {}

func (x *ListCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsRequest.ProtoReflect.Descriptor instead.
func (*ListCardsRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListCardsRequest) GetOwnerRef() string {
	if x != nil {
		return x.OwnerRef
	}
	return ""
}

func (x *ListCardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCardsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCardsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cards of the page.
	Cards []*Card `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	// Empty on the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsResponse) Reset() {
	*x = ListCardsResponse{}
	mi := &file_cas_v1_card_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsResponse) ProtoMessage() {}

func (x *ListCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsResponse.ProtoReflect.Descriptor instead.
func (*ListCardsResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *ListCardsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetAuthorizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The authorization to read.
	AuthId        string `protobuf:"bytes,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorizationRequest) Reset() {
	*x = GetAuthorizationRequest{}
	mi := &file_cas_v1_card_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationRequest) ProtoMessage() {}

func (x *GetAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetAuthorizationRequest) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

type GetAuthorizationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The authorization with its returns and history.
	Authorization *Authorization `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorizationResponse) Reset() {
	*x = GetAuthorizationResponse{}
	mi := &file_cas_v1_card_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationResponse) ProtoMessage() {}

func (x *GetAuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetAuthorizationResponse) GetAuthorization() *Authorization {
	if x != nil {
		return x.Authorization
	}
	return nil
}

type ListAuthorizationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter.
	CardRef string `protobuf:"bytes,1,opt,name=card_ref,json=cardRef,proto3" json:"card_ref,omitempty"`
	// Optional filter: the owner of the card.
	OwnerRef string `protobuf:"bytes,2,opt,name=owner_ref,json=ownerRef,proto3" json:"owner_ref,omitempty"`
	// Optional filter. AUTHORIZATION_STATUS_UNSPECIFIED: no filter.
	Status AuthorizationStatus `protobuf:"varint,3,opt,name=status,proto3,enum=cas.v1.AuthorizationStatus" json:"status,omitempty"`
	// Optional, inclusive.
	ReceivedFrom *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=received_from,json=receivedFrom,proto3" json:"received_from,omitempty"`
	// Optional, exclusive.
	ReceivedTo *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=received_to,json=receivedTo,proto3" json:"received_to,omitempty"`
	// 100 when 0; at most 500.
	PageSize int32 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// `next_page_token` of the previous response.
	PageToken     string `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorizationsRequest) Reset() {
	*x = ListAuthorizationsRequest{}
	mi := &file_cas_v1_card_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorizationsRequest) ProtoMessage() {}

func (x *ListAuthorizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorizationsRequest.ProtoReflect.Descriptor instead.
func (*ListAuthorizationsRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListAuthorizationsRequest) GetCardRef() string {
	if x != nil {
		return x.CardRef
	}
	return ""
}

func (x *ListAuthorizationsRequest) GetOwnerRef() string {
	if x != nil {
		return x.OwnerRef
	}
	return ""
}

func (x *ListAuthorizationsRequest) GetStatus() AuthorizationStatus {
	if x != nil {
		return x.Status
	}
	return AuthorizationStatus_AUTHORIZATION_STATUS_UNSPECIFIED
}

func (x *ListAuthorizationsRequest) GetReceivedFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedFrom
	}
	return nil
}

func (x *ListAuthorizationsRequest) GetReceivedTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedTo
	}
	return nil
}

func (x *ListAuthorizationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuthorizationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAuthorizationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authorizations of the page, without returns and history.
	Authorizations []*Authorization `protobuf:"bytes,1,rep,name=authorizations,proto3" json:"authorizations,omitempty"`
	// Empty on the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorizationsResponse) Reset() {
	*x = ListAuthorizationsResponse{}
	mi := &file_cas_v1_card_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorizationsResponse) ProtoMessage() {}

func (x *ListAuthorizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_card_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorizationsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthorizationsResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_card_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListAuthorizationsResponse) GetAuthorizations() []*Authorization {
	if x != nil {
		return x.Authorizations
	}
	return nil
}

func (x *ListAuthorizationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_cas_v1_card_service_proto protoreflect.FileDescriptor

const file_cas_v1_card_service_proto_rawDesc = "" +
	"\n" +
	"\x19cas/v1/card_service.proto\x12\x06cas.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x02\n" +
	"\x04Card\x12\x19\n" +
	"\bcard_ref\x18\x01 \x01(\tR\acardRef\x12\x1b\n" +
	"\towner_ref\x18\x02 \x01(\tR\bownerRef\x12#\n" +
	"\rconnection_id\x18\x03 \x01(\tR\fconnectionId\x12%\n" +
	"\x0ewallet_address\x18\x04 \x01(\tR\rwalletAddress\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.cas.v1.CardStatusR\x06status\x12\x1f\n" +
	"\vdaily_limit\x18\x06 \x01(\tR\n" +
	"dailyLimit\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\":\n" +
	"\x05Quote\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\tR\x04rate\x12\x1d\n" +
	"\n" +
	"buffer_bps\x18\x02 \x01(\x05R\tbufferBps\"\xf2\x01\n" +
	"\x06Return\x12\x1b\n" +
	"\treturn_id\x18\x01 \x01(\tR\breturnId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.cas.v1.ReturnTypeR\x04type\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.cas.v1.ReturnStatusR\x06status\x12!\n" +
	"\ftoken_amount\x18\x04 \x01(\tR\vtokenAmount\x12\x17\n" +
	"\atx_hash\x18\x05 \x01(\tR\x06txHash\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x87\x01\n" +
	"\fStatusChange\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.cas.v1.AuthorizationStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\x83\x05\n" +
	"\rAuthorization\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\tR\x06authId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.cas.v1.AuthorizationStatusR\x06status\x12<\n" +
	"\x0edecline_reason\x18\x03 \x01(\x0e2\x15.cas.v1.DeclineReasonR\rdeclineReason\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\x12!\n" +
	"\ftoken_amount\x18\a \x01(\tR\vtokenAmount\x12#\n" +
	"\x05quote\x18\b \x01(\v2\r.cas.v1.QuoteR\x05quote\x12%\n" +
	"\x0edebited_amount\x18\t \x01(\tR\rdebitedAmount\x12'\n" +
	"\x0freturned_amount\x18\n" +
	" \x01(\tR\x0ereturnedAmount\x12\x17\n" +
	"\atx_hash\x18\v \x01(\tR\x06txHash\x12(\n" +
	"\areturns\x18\f \x03(\v2\x0e.cas.v1.ReturnR\areturns\x12.\n" +
	"\ahistory\x18\r \x03(\v2\x14.cas.v1.StatusChangeR\ahistory\x12\x19\n" +
	"\bcard_ref\x18\x0e \x01(\tR\acardRef\x12;\n" +
	"\vreceived_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x129\n" +
	"\n" +
	"decided_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAt\"\x93\x01\n" +
	"\x13RegisterCardRequest\x12\x19\n" +
	"\bcard_ref\x18\x01 \x01(\tR\acardRef\x12\x1b\n" +
	"\towner_ref\x18\x02 \x01(\tR\bownerRef\x12#\n" +
	"\rconnection_id\x18\x03 \x01(\tR\fconnectionId\x12\x1f\n" +
	"\vdaily_limit\x18\x04 \x01(\tR\n" +
	"dailyLimit\"8\n" +
	"\x14RegisterCardResponse\x12 \n" +
	"\x04card\x18\x01 \x01(\v2\f.cas.v1.CardR\x04card\"\xa0\x01\n" +
	"\x11UpdateCardRequest\x12\x19\n" +
	"\bcard_ref\x18\x01 \x01(\tR\acardRef\x12$\n" +
	"\vdaily_limit\x18\x02 \x01(\tH\x00R\n" +
	"dailyLimit\x88\x01\x01\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.cas.v1.CardStatusH\x01R\x06status\x88\x01\x01B\x0e\n" +
	"\f_daily_limitB\t\n" +
	"\a_status\"6\n" +
	"\x12UpdateCardResponse\x12 \n" +
	"\x04card\x18\x01 \x01(\v2\f.cas.v1.CardR\x04card\"+\n" +
	"\x0eGetCardRequest\x12\x19\n" +
	"\bcard_ref\x18\x01 \x01(\tR\acardRef\"3\n" +
	"\x0fGetCardResponse\x12 \n" +
	"\x04card\x18\x01 \x01(\v2\f.cas.v1.CardR\x04card\"k\n" +
	"\x10ListCardsRequest\x12\x1b\n" +
	"\towner_ref\x18\x01 \x01(\tR\bownerRef\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"_\n" +
	"\x11ListCardsResponse\x12\"\n" +
	"\x05cards\x18\x01 \x03(\v2\f.cas.v1.CardR\x05cards\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"2\n" +
	"\x17GetAuthorizationRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\tR\x06authId\"W\n" +
	"\x18GetAuthorizationResponse\x12;\n" +
	"\rauthorization\x18\x01 \x01(\v2\x15.cas.v1.AuthorizationR\rauthorization\"\xc2\x02\n" +
	"\x19ListAuthorizationsRequest\x12\x19\n" +
	"\bcard_ref\x18\x01 \x01(\tR\acardRef\x12\x1b\n" +
	"\towner_ref\x18\x02 \x01(\tR\bownerRef\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.cas.v1.AuthorizationStatusR\x06status\x12?\n" +
	"\rreceived_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\freceivedFrom\x12;\n" +
	"\vreceived_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedTo\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\"\x83\x01\n" +
	"\x1aListAuthorizationsResponse\x12=\n" +
	"\x0eauthorizations\x18\x01 \x03(\v2\x15.cas.v1.AuthorizationR\x0eauthorizations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*Y\n" +
	"\n" +
	"CardStatus\x12\x1b\n" +
	"\x17CARD_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CARD_STATUS_ACTIVE\x10\x01\x12\x16\n" +
	"\x12CARD_STATUS_FROZEN\x10\x02*\x94\x03\n" +
	"\x13AuthorizationStatus\x12$\n" +
	" AUTHORIZATION_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAUTHORIZATION_STATUS_RECEIVED\x10\x01\x12(\n" +
	"$AUTHORIZATION_STATUS_DEBIT_SUBMITTED\x10\x02\x12!\n" +
	"\x1dAUTHORIZATION_STATUS_APPROVED\x10\x03\x12(\n" +
	"$AUTHORIZATION_STATUS_DEBIT_CONFIRMED\x10\x04\x12!\n" +
	"\x1dAUTHORIZATION_STATUS_DECLINED\x10\x05\x12\"\n" +
	"\x1eAUTHORIZATION_STATUS_TIMED_OUT\x10\x06\x12#\n" +
	"\x1fAUTHORIZATION_STATUS_LATE_DEBIT\x10\a\x12,\n" +
	"(AUTHORIZATION_STATUS_LATE_DEBIT_REFUNDED\x10\b\x12#\n" +
	"\x1fAUTHORIZATION_STATUS_DEBIT_LOST\x10\t*\x8b\x04\n" +
	"\rDeclineReason\x12\x1e\n" +
	"\x1aDECLINE_REASON_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dDECLINE_REASON_CARD_NOT_FOUND\x10\x01\x12\x1e\n" +
	"\x1aDECLINE_REASON_CARD_FROZEN\x10\x02\x12!\n" +
	"\x1dDECLINE_REASON_PROGRAM_PAUSED\x10\x03\x12)\n" +
	"%DECLINE_REASON_CURRENCY_NOT_SUPPORTED\x10\x04\x12#\n" +
	"\x1fDECLINE_REASON_RATE_UNAVAILABLE\x10\x05\x12!\n" +
	"\x1dDECLINE_REASON_LIMIT_EXCEEDED\x10\x06\x12%\n" +
	"!DECLINE_REASON_INSUFFICIENT_FUNDS\x10\a\x12)\n" +
	"%DECLINE_REASON_INSUFFICIENT_ALLOWANCE\x10\b\x12$\n" +
	" DECLINE_REASON_CHAIN_UNAVAILABLE\x10\t\x12!\n" +
	"\x1dDECLINE_REASON_DEBIT_REVERTED\x10\n" +
	"\x12\x1a\n" +
	"\x16DECLINE_REASON_TIMEOUT\x10\v\x12'\n" +
	"#DECLINE_REASON_REVERSED_BEFORE_AUTH\x10\f\x12!\n" +
	"\x1dDECLINE_REASON_INTERNAL_ERROR\x10\r*w\n" +
	"\n" +
	"ReturnType\x12\x1b\n" +
	"\x17RETURN_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RETURN_TYPE_REVERSAL\x10\x01\x12\x16\n" +
	"\x12RETURN_TYPE_REFUND\x10\x02\x12\x1a\n" +
	"\x16RETURN_TYPE_LATE_DEBIT\x10\x03*\xe0\x01\n" +
	"\fReturnStatus\x12\x1d\n" +
	"\x19RETURN_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RETURN_STATUS_ACCEPTED\x10\x01\x12\x1b\n" +
	"\x17RETURN_STATUS_SUBMITTED\x10\x02\x12\x1a\n" +
	"\x16RETURN_STATUS_INCLUDED\x10\x03\x12\x1b\n" +
	"\x17RETURN_STATUS_CONFIRMED\x10\x04\x12\x1a\n" +
	"\x16RETURN_STATUS_RETRYING\x10\x05\x12#\n" +
	"\x1fRETURN_STATUS_NOTHING_TO_RETURN\x10\x062\xcf\x03\n" +
	"\vCardService\x12I\n" +
	"\fRegisterCard\x12\x1b.cas.v1.RegisterCardRequest\x1a\x1c.cas.v1.RegisterCardResponse\x12C\n" +
	"\n" +
	"UpdateCard\x12\x19.cas.v1.UpdateCardRequest\x1a\x1a.cas.v1.UpdateCardResponse\x12:\n" +
	"\aGetCard\x12\x16.cas.v1.GetCardRequest\x1a\x17.cas.v1.GetCardResponse\x12@\n" +
	"\tListCards\x12\x18.cas.v1.ListCardsRequest\x1a\x19.cas.v1.ListCardsResponse\x12U\n" +
	"\x10GetAuthorization\x12\x1f.cas.v1.GetAuthorizationRequest\x1a .cas.v1.GetAuthorizationResponse\x12[\n" +
	"\x12ListAuthorizations\x12!.cas.v1.ListAuthorizationsRequest\x1a\".cas.v1.ListAuthorizationsResponseBKZIgithub.com/DigitLock/crypto-account-service/internal/grpc/pb/cas/v1;casv1b\x06proto3"

var (
	file_cas_v1_card_service_proto_rawDescOnce sync.Once
	file_cas_v1_card_service_proto_rawDescData []byte
)

func file_cas_v1_card_service_proto_rawDescGZIP() []byte {
	file_cas_v1_card_service_proto_rawDescOnce.Do(func() {
		file_cas_v1_card_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cas_v1_card_service_proto_rawDesc), len(file_cas_v1_card_service_proto_rawDesc)))
	})
	return file_cas_v1_card_service_proto_rawDescData
}

var file_cas_v1_card_service_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_cas_v1_card_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cas_v1_card_service_proto_goTypes = []any{
	(CardStatus)(0),                    // 0: cas.v1.CardStatus
	(AuthorizationStatus)(0),           // 1: cas.v1.AuthorizationStatus
	(DeclineReason)(0),                 // 2: cas.v1.DeclineReason
	(ReturnType)(0),                    // 3: cas.v1.ReturnType
	(ReturnStatus)(0),                  // 4: cas.v1.ReturnStatus
	(*Card)(nil),                       // 5: cas.v1.Card
	(*Quote)(nil),                      // 6: cas.v1.Quote
	(*Return)(nil),                     // 7: cas.v1.Return
	(*StatusChange)(nil),               // 8: cas.v1.StatusChange
	(*Authorization)(nil),              // 9: cas.v1.Authorization
	(*RegisterCardRequest)(nil),        // 10: cas.v1.RegisterCardRequest
	(*RegisterCardResponse)(nil),       // 11: cas.v1.RegisterCardResponse
	(*UpdateCardRequest)(nil),          // 12: cas.v1.UpdateCardRequest
	(*UpdateCardResponse)(nil),         // 13: cas.v1.UpdateCardResponse
	(*GetCardRequest)(nil),             // 14: cas.v1.GetCardRequest
	(*GetCardResponse)(nil),            // 15: cas.v1.GetCardResponse
	(*ListCardsRequest)(nil),           // 16: cas.v1.ListCardsRequest
	(*ListCardsResponse)(nil),          // 17: cas.v1.ListCardsResponse
	(*GetAuthorizationRequest)(nil),    // 18: cas.v1.GetAuthorizationRequest
	(*GetAuthorizationResponse)(nil),   // 19: cas.v1.GetAuthorizationResponse
	(*ListAuthorizationsRequest)(nil),  // 20: cas.v1.ListAuthorizationsRequest
	(*ListAuthorizationsResponse)(nil), // 21: cas.v1.ListAuthorizationsResponse
	(*timestamppb.Timestamp)(nil),      // 22: google.protobuf.Timestamp
}
var file_cas_v1_card_service_proto_depIdxs = []int32{
	0,  // 0: cas.v1.Card.status:type_name -> cas.v1.CardStatus
	22, // 1: cas.v1.Card.created_at:type_name -> google.protobuf.Timestamp
	22, // 2: cas.v1.Card.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 3: cas.v1.Return.type:type_name -> cas.v1.ReturnType
	4,  // 4: cas.v1.Return.status:type_name -> cas.v1.ReturnStatus
	22, // 5: cas.v1.Return.created_at:type_name -> google.protobuf.Timestamp
	1,  // 6: cas.v1.StatusChange.status:type_name -> cas.v1.AuthorizationStatus
	22, // 7: cas.v1.StatusChange.at:type_name -> google.protobuf.Timestamp
	1,  // 8: cas.v1.Authorization.status:type_name -> cas.v1.AuthorizationStatus
	2,  // 9: cas.v1.Authorization.decline_reason:type_name -> cas.v1.DeclineReason
	6,  // 10: cas.v1.Authorization.quote:type_name -> cas.v1.Quote
	7,  // 11: cas.v1.Authorization.returns:type_name -> cas.v1.Return
	8,  // 12: cas.v1.Authorization.history:type_name -> cas.v1.StatusChange
	22, // 13: cas.v1.Authorization.received_at:type_name -> google.protobuf.Timestamp
	22, // 14: cas.v1.Authorization.decided_at:type_name -> google.protobuf.Timestamp
	5,  // 15: cas.v1.RegisterCardResponse.card:type_name -> cas.v1.Card
	0,  // 16: cas.v1.UpdateCardRequest.status:type_name -> cas.v1.CardStatus
	5,  // 17: cas.v1.UpdateCardResponse.card:type_name -> cas.v1.Card
	5,  // 18: cas.v1.GetCardResponse.card:type_name -> cas.v1.Card
	5,  // 19: cas.v1.ListCardsResponse.cards:type_name -> cas.v1.Card
	9,  // 20: cas.v1.GetAuthorizationResponse.authorization:type_name -> cas.v1.Authorization
	1,  // 21: cas.v1.ListAuthorizationsRequest.status:type_name -> cas.v1.AuthorizationStatus
	22, // 22: cas.v1.ListAuthorizationsRequest.received_from:type_name -> google.protobuf.Timestamp
	22, // 23: cas.v1.ListAuthorizationsRequest.received_to:type_name -> google.protobuf.Timestamp
	9,  // 24: cas.v1.ListAuthorizationsResponse.authorizations:type_name -> cas.v1.Authorization
	10, // 25: cas.v1.CardService.RegisterCard:input_type -> cas.v1.RegisterCardRequest
	12, // 26: cas.v1.CardService.UpdateCard:input_type -> cas.v1.UpdateCardRequest
	14, // 27: cas.v1.CardService.GetCard:input_type -> cas.v1.GetCardRequest
	16, // 28: cas.v1.CardService.ListCards:input_type -> cas.v1.ListCardsRequest
	18, // 29: cas.v1.CardService.GetAuthorization:input_type -> cas.v1.GetAuthorizationRequest
	20, // 30: cas.v1.CardService.ListAuthorizations:input_type -> cas.v1.ListAuthorizationsRequest
	11, // 31: cas.v1.CardService.RegisterCard:output_type -> cas.v1.RegisterCardResponse
	13, // 32: cas.v1.CardService.UpdateCard:output_type -> cas.v1.UpdateCardResponse
	15, // 33: cas.v1.CardService.GetCard:output_type -> cas.v1.GetCardResponse
	17, // 34: cas.v1.CardService.ListCards:output_type -> cas.v1.ListCardsResponse
	19, // 35: cas.v1.CardService.GetAuthorization:output_type -> cas.v1.GetAuthorizationResponse
	21, // 36: cas.v1.CardService.ListAuthorizations:output_type -> cas.v1.ListAuthorizationsResponse
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_cas_v1_card_service_proto_init() }
func file_cas_v1_card_service_proto_init() {
	if File_cas_v1_card_service_proto != nil {
		return
	}
	file_cas_v1_card_service_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cas_v1_card_service_proto_rawDesc), len(file_cas_v1_card_service_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cas_v1_card_service_proto_goTypes,
		DependencyIndexes: file_cas_v1_card_service_proto_depIdxs,
		EnumInfos:         file_cas_v1_card_service_proto_enumTypes,
		MessageInfos:      file_cas_v1_card_service_proto_msgTypes,
	}.Build()
	File_cas_v1_card_service_proto = out.File
	file_cas_v1_card_service_proto_goTypes = nil
	file_cas_v1_card_service_proto_depIdxs = nil
}
