// Contract of Crypto Account Service: connections.
// Specification: docs/srs/core.md §2.1.1, §2.1.2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cas/v1/connection_service.proto

package casv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind of a source.
type SourceKind int32

const (
	SourceKind_SOURCE_KIND_UNSPECIFIED SourceKind = 0
	SourceKind_SOURCE_KIND_EXCHANGE    SourceKind = 1
	SourceKind_SOURCE_KIND_EVM         SourceKind = 2
)

// Enum value maps for SourceKind.
var (
	SourceKind_name = map[int32]string{
		0: "SOURCE_KIND_UNSPECIFIED",
		1: "SOURCE_KIND_EXCHANGE",
		2: "SOURCE_KIND_EVM",
	}
	SourceKind_value = map[string]int32{
		"SOURCE_KIND_UNSPECIFIED": 0,
		"SOURCE_KIND_EXCHANGE":    1,
		"SOURCE_KIND_EVM":         2,
	}
)

func (x SourceKind) Enum() *SourceKind {
	p := new(SourceKind)
	*p = x
	return p
}

func (x SourceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_connection_service_proto_enumTypes[0].Descriptor()
}

func (SourceKind) Type() protoreflect.EnumType {
	return &file_cas_v1_connection_service_proto_enumTypes[0]
}

func (x SourceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceKind.Descriptor instead.
func (SourceKind) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{0}
}

// Kind of a connection.
type ConnectionKind int32

const (
	ConnectionKind_CONNECTION_KIND_UNSPECIFIED ConnectionKind = 0
	ConnectionKind_CONNECTION_KIND_EXCHANGE    ConnectionKind = 1
	ConnectionKind_CONNECTION_KIND_EVM_WALLET  ConnectionKind = 2
)

// Enum value maps for ConnectionKind.
var (
	ConnectionKind_name = map[int32]string{
		0: "CONNECTION_KIND_UNSPECIFIED",
		1: "CONNECTION_KIND_EXCHANGE",
		2: "CONNECTION_KIND_EVM_WALLET",
	}
	ConnectionKind_value = map[string]int32{
		"CONNECTION_KIND_UNSPECIFIED": 0,
		"CONNECTION_KIND_EXCHANGE":    1,
		"CONNECTION_KIND_EVM_WALLET":  2,
	}
)

func (x ConnectionKind) Enum() *ConnectionKind {
	p := new(ConnectionKind)
	*p = x
	return p
}

func (x ConnectionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_connection_service_proto_enumTypes[1].Descriptor()
}

func (ConnectionKind) Type() protoreflect.EnumType {
	return &file_cas_v1_connection_service_proto_enumTypes[1]
}

func (x ConnectionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionKind.Descriptor instead.
func (ConnectionKind) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{1}
}

// State of a connection.
type ConnectionStatus int32

const (
	ConnectionStatus_CONNECTION_STATUS_UNSPECIFIED ConnectionStatus = 0
	// Usable; sync runs.
	ConnectionStatus_CONNECTION_STATUS_ACTIVE ConnectionStatus = 1
	// A stream reached the failure threshold; sync runs with backoff.
	ConnectionStatus_CONNECTION_STATUS_DEGRADED ConnectionStatus = 2
	// The source rejected the key, or the key is no longer read-only; sync is stopped.
	ConnectionStatus_CONNECTION_STATUS_CREDENTIALS_INVALID ConnectionStatus = 3
)

// Enum value maps for ConnectionStatus.
var (
	ConnectionStatus_name = map[int32]string{
		0: "CONNECTION_STATUS_UNSPECIFIED",
		1: "CONNECTION_STATUS_ACTIVE",
		2: "CONNECTION_STATUS_DEGRADED",
		3: "CONNECTION_STATUS_CREDENTIALS_INVALID",
	}
	ConnectionStatus_value = map[string]int32{
		"CONNECTION_STATUS_UNSPECIFIED":         0,
		"CONNECTION_STATUS_ACTIVE":              1,
		"CONNECTION_STATUS_DEGRADED":            2,
		"CONNECTION_STATUS_CREDENTIALS_INVALID": 3,
	}
)

func (x ConnectionStatus) Enum() *ConnectionStatus {
	p := new(ConnectionStatus)
	*p = x
	return p
}

func (x ConnectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_connection_service_proto_enumTypes[2].Descriptor()
}

func (ConnectionStatus) Type() protoreflect.EnumType {
	return &file_cas_v1_connection_service_proto_enumTypes[2]
}

func (x ConnectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionStatus.Descriptor instead.
func (ConnectionStatus) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{2}
}

// Mode of a stream.
type StreamMode int32

const (
	StreamMode_STREAM_MODE_UNSPECIFIED StreamMode = 0
	StreamMode_STREAM_MODE_BACKFILL    StreamMode = 1
	StreamMode_STREAM_MODE_INCREMENTAL StreamMode = 2
)

// Enum value maps for StreamMode.
var (
	StreamMode_name = map[int32]string{
		0: "STREAM_MODE_UNSPECIFIED",
		1: "STREAM_MODE_BACKFILL",
		2: "STREAM_MODE_INCREMENTAL",
	}
	StreamMode_value = map[string]int32{
		"STREAM_MODE_UNSPECIFIED": 0,
		"STREAM_MODE_BACKFILL":    1,
		"STREAM_MODE_INCREMENTAL": 2,
	}
)

func (x StreamMode) Enum() *StreamMode {
	p := new(StreamMode)
	*p = x
	return p
}

func (x StreamMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamMode) Descriptor() protoreflect.EnumDescriptor {
	return file_cas_v1_connection_service_proto_enumTypes[3].Descriptor()
}

func (StreamMode) Type() protoreflect.EnumType {
	return &file_cas_v1_connection_service_proto_enumTypes[3]
}

func (x StreamMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamMode.Descriptor instead.
func (StreamMode) EnumDescriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{3}
}

// An exchange or an EVM network that CAS can read.
type Source struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source code, used in CreateConnection: `binance`, `base-sepolia`.
	Code          string     `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Kind          SourceKind `protobuf:"varint,2,opt,name=kind,proto3,enum=cas.v1.SourceKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{0}
}

func (x *Source) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Source) GetKind() SourceKind {
	if x != nil {
		return x.Kind
	}
	return SourceKind_SOURCE_KIND_UNSPECIFIED
}

// API key of an exchange account. Never returned.
type ExchangeKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiSecret     string                 `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeKey) Reset() {
	*x = ExchangeKey{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeKey) ProtoMessage() {}

func (x *ExchangeKey) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeKey.ProtoReflect.Descriptor instead.
func (*ExchangeKey) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeKey) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ExchangeKey) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

// Self-custody wallet.
type Wallet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `0x` and 40 hexadecimal characters; mixed case must pass the EIP-55 checksum.
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{2}
}

func (x *Wallet) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// One account at one source.
type Connection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID.
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Source code.
	Source string         `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Kind   ConnectionKind `protobuf:"varint,3,opt,name=kind,proto3,enum=cas.v1.ConnectionKind" json:"kind,omitempty"`
	// Opaque owner ID of the tenant.
	OwnerRef string `protobuf:"bytes,4,opt,name=owner_ref,json=ownerRef,proto3" json:"owner_ref,omitempty"`
	// Display name. Empty when not set.
	Label  string           `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Status ConnectionStatus `protobuf:"varint,6,opt,name=status,proto3,enum=cas.v1.ConnectionStatus" json:"status,omitempty"`
	// Exchanges only: `…` and the last 4 characters of the API key.
	KeyFingerprint string `protobuf:"bytes,7,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	// Exchanges only: permissions reported by the source, or `UNVERIFIED`.
	Permissions   []string               `protobuf:"bytes,8,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{3}
}

func (x *Connection) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Connection) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Connection) GetKind() ConnectionKind {
	if x != nil {
		return x.Kind
	}
	return ConnectionKind_CONNECTION_KIND_UNSPECIFIED
}

func (x *Connection) GetOwnerRef() string {
	if x != nil {
		return x.OwnerRef
	}
	return ""
}

func (x *Connection) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Connection) GetStatus() ConnectionStatus {
	if x != nil {
		return x.Status
	}
	return ConnectionStatus_CONNECTION_STATUS_UNSPECIFIED
}

func (x *Connection) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

func (x *Connection) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Connection) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Health of one stream of a connection.
type StreamHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full stream name: `balances`, `trades:BTCUSDT`.
	Stream    string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Mode      StreamMode             `protobuf:"varint,2,opt,name=mode,proto3,enum=cas.v1.StreamMode" json:"mode,omitempty"`
	NextRunAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	// Absent before the first successful run.
	LastSuccessAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_success_at,json=lastSuccessAt,proto3" json:"last_success_at,omitempty"`
	// Last error, without secrets. Empty after a success.
	LastError           string `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	ConsecutiveFailures int32  `protobuf:"varint,6,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StreamHealth) Reset() {
	*x = StreamHealth{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHealth) ProtoMessage() {}

func (x *StreamHealth) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHealth.ProtoReflect.Descriptor instead.
func (*StreamHealth) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{4}
}

func (x *StreamHealth) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *StreamHealth) GetMode() StreamMode {
	if x != nil {
		return x.Mode
	}
	return StreamMode_STREAM_MODE_UNSPECIFIED
}

func (x *StreamHealth) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *StreamHealth) GetLastSuccessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccessAt
	}
	return nil
}

func (x *StreamHealth) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *StreamHealth) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

type ListSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesRequest) Reset() {
	*x = ListSourcesRequest{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesRequest) ProtoMessage() {}

func (x *ListSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListSourcesRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{5}
}

type ListSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*Source              `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesResponse) Reset() {
	*x = ListSourcesResponse{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesResponse) ProtoMessage() {}

func (x *ListSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListSourcesResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

type CreateConnectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required, at most 128 characters.
	OwnerRef string `protobuf:"bytes,1,opt,name=owner_ref,json=ownerRef,proto3" json:"owner_ref,omitempty"`
	// Required. Source code from ListSources.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Optional, at most 64 characters.
	Label string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	// Required. Must match the kind of the source.
	//
	// Types that are valid to be assigned to Credential:
	//
	//	*CreateConnectionRequest_ExchangeKey
	//	*CreateConnectionRequest_Wallet
	Credential    isCreateConnectionRequest_Credential `protobuf_oneof:"credential"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConnectionRequest) Reset() {
	*x = CreateConnectionRequest{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConnectionRequest) ProtoMessage() {}

func (x *CreateConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConnectionRequest.ProtoReflect.Descriptor instead.
func (*CreateConnectionRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateConnectionRequest) GetOwnerRef() string {
	if x != nil {
		return x.OwnerRef
	}
	return ""
}

func (x *CreateConnectionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateConnectionRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateConnectionRequest) GetCredential() isCreateConnectionRequest_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *CreateConnectionRequest) GetExchangeKey() *ExchangeKey {
	if x != nil {
		if x, ok := x.Credential.(*CreateConnectionRequest_ExchangeKey); ok {
			return x.ExchangeKey
		}
	}
	return nil
}

func (x *CreateConnectionRequest) GetWallet() *Wallet {
	if x != nil {
		if x, ok := x.Credential.(*CreateConnectionRequest_Wallet); ok {
			return x.Wallet
		}
	}
	return nil
}

type isCreateConnectionRequest_Credential interface {
	isCreateConnectionRequest_Credential()
}

type CreateConnectionRequest_ExchangeKey struct {
	ExchangeKey *ExchangeKey `protobuf:"bytes,4,opt,name=exchange_key,json=exchangeKey,proto3,oneof"`
}

type CreateConnectionRequest_Wallet struct {
	Wallet *Wallet `protobuf:"bytes,5,opt,name=wallet,proto3,oneof"`
}

func (*CreateConnectionRequest_ExchangeKey) isCreateConnectionRequest_Credential() {}

func (*CreateConnectionRequest_Wallet) isCreateConnectionRequest_Credential() {}

type CreateConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *Connection            `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConnectionResponse) Reset() {
	*x = CreateConnectionResponse{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConnectionResponse) ProtoMessage() {}

func (x *CreateConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConnectionResponse.ProtoReflect.Descriptor instead.
func (*CreateConnectionResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateConnectionResponse) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type ListConnectionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter.
	OwnerRef string `protobuf:"bytes,1,opt,name=owner_ref,json=ownerRef,proto3" json:"owner_ref,omitempty"`
	// 100 when 0; at most 500.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// `next_page_token` of the previous response.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectionsRequest) Reset() {
	*x = ListConnectionsRequest{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionsRequest) ProtoMessage() {}

func (x *ListConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListConnectionsRequest) GetOwnerRef() string {
	if x != nil {
		return x.OwnerRef
	}
	return ""
}

func (x *ListConnectionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConnectionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListConnectionsResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Connections []*Connection          `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	// Empty on the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectionsResponse) Reset() {
	*x = ListConnectionsResponse{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionsResponse) ProtoMessage() {}

func (x *ListConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListConnectionsResponse) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *ListConnectionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionRequest) Reset() {
	*x = GetConnectionRequest{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionRequest) ProtoMessage() {}

func (x *GetConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetConnectionRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type GetConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *Connection            `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	Streams       []*StreamHealth        `protobuf:"bytes,2,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionResponse) Reset() {
	*x = GetConnectionResponse{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionResponse) ProtoMessage() {}

func (x *GetConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetConnectionResponse) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *GetConnectionResponse) GetStreams() []*StreamHealth {
	if x != nil {
		return x.Streams
	}
	return nil
}

type DeleteConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnectionRequest) Reset() {
	*x = DeleteConnectionRequest{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectionRequest) ProtoMessage() {}

func (x *DeleteConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteConnectionRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteConnectionRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type DeleteConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnectionResponse) Reset() {
	*x = DeleteConnectionResponse{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectionResponse) ProtoMessage() {}

func (x *DeleteConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteConnectionResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{14}
}

type TriggerSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSyncRequest) Reset() {
	*x = TriggerSyncRequest{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSyncRequest) ProtoMessage() {}

func (x *TriggerSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSyncRequest.ProtoReflect.Descriptor instead.
func (*TriggerSyncRequest) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{15}
}

func (x *TriggerSyncRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type TriggerSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSyncResponse) Reset() {
	*x = TriggerSyncResponse{}
	mi := &file_cas_v1_connection_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSyncResponse) ProtoMessage() {}

func (x *TriggerSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_v1_connection_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSyncResponse.ProtoReflect.Descriptor instead.
func (*TriggerSyncResponse) Descriptor() ([]byte, []int) {
	return file_cas_v1_connection_service_proto_rawDescGZIP(), []int{16}
}

var File_cas_v1_connection_service_proto protoreflect.FileDescriptor

const file_cas_v1_connection_service_proto_rawDesc = "" +
	"\n" +
	"\x1fcas/v1/connection_service.proto\x12\x06cas.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\x06Source\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12&\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x12.cas.v1.SourceKindR\x04kind\"E\n" +
	"\vExchangeKey\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tR\tapiSecret\"\"\n" +
	"\x06Wallet\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\xe0\x02\n" +
	"\n" +
	"Connection\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12*\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x16.cas.v1.ConnectionKindR\x04kind\x12\x1b\n" +
	"\towner_ref\x18\x04 \x01(\tR\bownerRef\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.cas.v1.ConnectionStatusR\x06status\x12'\n" +
	"\x0fkey_fingerprint\x18\a \x01(\tR\x0ekeyFingerprint\x12 \n" +
	"\vpermissions\x18\b \x03(\tR\vpermissions\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa0\x02\n" +
	"\fStreamHealth\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12&\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x12.cas.v1.StreamModeR\x04mode\x12:\n" +
	"\vnext_run_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x12B\n" +
	"\x0flast_success_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastSuccessAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x121\n" +
	"\x14consecutive_failures\x18\x06 \x01(\x05R\x13consecutiveFailures\"\x14\n" +
	"\x12ListSourcesRequest\"?\n" +
	"\x13ListSourcesResponse\x12(\n" +
	"\asources\x18\x01 \x03(\v2\x0e.cas.v1.SourceR\asources\"\xd6\x01\n" +
	"\x17CreateConnectionRequest\x12\x1b\n" +
	"\towner_ref\x18\x01 \x01(\tR\bownerRef\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x128\n" +
	"\fexchange_key\x18\x04 \x01(\v2\x13.cas.v1.ExchangeKeyH\x00R\vexchangeKey\x12(\n" +
	"\x06wallet\x18\x05 \x01(\v2\x0e.cas.v1.WalletH\x00R\x06walletB\f\n" +
	"\n" +
	"credential\"N\n" +
	"\x18CreateConnectionResponse\x122\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x12.cas.v1.ConnectionR\n" +
	"connection\"q\n" +
	"\x16ListConnectionsRequest\x12\x1b\n" +
	"\towner_ref\x18\x01 \x01(\tR\bownerRef\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"w\n" +
	"\x17ListConnectionsResponse\x124\n" +
	"\vconnections\x18\x01 \x03(\v2\x12.cas.v1.ConnectionR\vconnections\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\";\n" +
	"\x14GetConnectionRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"{\n" +
	"\x15GetConnectionResponse\x122\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x12.cas.v1.ConnectionR\n" +
	"connection\x12.\n" +
	"\astreams\x18\x02 \x03(\v2\x14.cas.v1.StreamHealthR\astreams\">\n" +
	"\x17DeleteConnectionRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"\x1a\n" +
	"\x18DeleteConnectionResponse\"9\n" +
	"\x12TriggerSyncRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"\x15\n" +
	"\x13TriggerSyncResponse*X\n" +
	"\n" +
	"SourceKind\x12\x1b\n" +
	"\x17SOURCE_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SOURCE_KIND_EXCHANGE\x10\x01\x12\x13\n" +
	"\x0fSOURCE_KIND_EVM\x10\x02*o\n" +
	"\x0eConnectionKind\x12\x1f\n" +
	"\x1bCONNECTION_KIND_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONNECTION_KIND_EXCHANGE\x10\x01\x12\x1e\n" +
	"\x1aCONNECTION_KIND_EVM_WALLET\x10\x02*\x9e\x01\n" +
	"\x10ConnectionStatus\x12!\n" +
	"\x1dCONNECTION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONNECTION_STATUS_ACTIVE\x10\x01\x12\x1e\n" +
	"\x1aCONNECTION_STATUS_DEGRADED\x10\x02\x12)\n" +
	"%CONNECTION_STATUS_CREDENTIALS_INVALID\x10\x03*`\n" +
	"\n" +
	"StreamMode\x12\x1b\n" +
	"\x17STREAM_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STREAM_MODE_BACKFILL\x10\x01\x12\x1b\n" +
	"\x17STREAM_MODE_INCREMENTAL\x10\x022\xf3\x03\n" +
	"\x11ConnectionService\x12F\n" +
	"\vListSources\x12\x1a.cas.v1.ListSourcesRequest\x1a\x1b.cas.v1.ListSourcesResponse\x12U\n" +
	"\x10CreateConnection\x12\x1f.cas.v1.CreateConnectionRequest\x1a .cas.v1.CreateConnectionResponse\x12R\n" +
	"\x0fListConnections\x12\x1e.cas.v1.ListConnectionsRequest\x1a\x1f.cas.v1.ListConnectionsResponse\x12L\n" +
	"\rGetConnection\x12\x1c.cas.v1.GetConnectionRequest\x1a\x1d.cas.v1.GetConnectionResponse\x12U\n" +
	"\x10DeleteConnection\x12\x1f.cas.v1.DeleteConnectionRequest\x1a .cas.v1.DeleteConnectionResponse\x12F\n" +
	"\vTriggerSync\x12\x1a.cas.v1.TriggerSyncRequest\x1a\x1b.cas.v1.TriggerSyncResponseBKZIgithub.com/DigitLock/crypto-account-service/internal/grpc/pb/cas/v1;casv1b\x06proto3"

var (
	file_cas_v1_connection_service_proto_rawDescOnce sync.Once
	file_cas_v1_connection_service_proto_rawDescData []byte
)

func file_cas_v1_connection_service_proto_rawDescGZIP() []byte {
	file_cas_v1_connection_service_proto_rawDescOnce.Do(func() {
		file_cas_v1_connection_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cas_v1_connection_service_proto_rawDesc), len(file_cas_v1_connection_service_proto_rawDesc)))
	})
	return file_cas_v1_connection_service_proto_rawDescData
}

var file_cas_v1_connection_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cas_v1_connection_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cas_v1_connection_service_proto_goTypes = []any{
	(SourceKind)(0),                  // 0: cas.v1.SourceKind
	(ConnectionKind)(0),              // 1: cas.v1.ConnectionKind
	(ConnectionStatus)(0),            // 2: cas.v1.ConnectionStatus
	(StreamMode)(0),                  // 3: cas.v1.StreamMode
	(*Source)(nil),                   // 4: cas.v1.Source
	(*ExchangeKey)(nil),              // 5: cas.v1.ExchangeKey
	(*Wallet)(nil),                   // 6: cas.v1.Wallet
	(*Connection)(nil),               // 7: cas.v1.Connection
	(*StreamHealth)(nil),             // 8: cas.v1.StreamHealth
	(*ListSourcesRequest)(nil),       // 9: cas.v1.ListSourcesRequest
	(*ListSourcesResponse)(nil),      // 10: cas.v1.ListSourcesResponse
	(*CreateConnectionRequest)(nil),  // 11: cas.v1.CreateConnectionRequest
	(*CreateConnectionResponse)(nil), // 12: cas.v1.CreateConnectionResponse
	(*ListConnectionsRequest)(nil),   // 13: cas.v1.ListConnectionsRequest
	(*ListConnectionsResponse)(nil),  // 14: cas.v1.ListConnectionsResponse
	(*GetConnectionRequest)(nil),     // 15: cas.v1.GetConnectionRequest
	(*GetConnectionResponse)(nil),    // 16: cas.v1.GetConnectionResponse
	(*DeleteConnectionRequest)(nil),  // 17: cas.v1.DeleteConnectionRequest
	(*DeleteConnectionResponse)(nil), // 18: cas.v1.DeleteConnectionResponse
	(*TriggerSyncRequest)(nil),       // 19: cas.v1.TriggerSyncRequest
	(*TriggerSyncResponse)(nil),      // 20: cas.v1.TriggerSyncResponse
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
}
var file_cas_v1_connection_service_proto_depIdxs = []int32{
	0,  // 0: cas.v1.Source.kind:type_name -> cas.v1.SourceKind
	1,  // 1: cas.v1.Connection.kind:type_name -> cas.v1.ConnectionKind
	2,  // 2: cas.v1.Connection.status:type_name -> cas.v1.ConnectionStatus
	21, // 3: cas.v1.Connection.created_at:type_name -> google.protobuf.Timestamp
	3,  // 4: cas.v1.StreamHealth.mode:type_name -> cas.v1.StreamMode
	21, // 5: cas.v1.StreamHealth.next_run_at:type_name -> google.protobuf.Timestamp
	21, // 6: cas.v1.StreamHealth.last_success_at:type_name -> google.protobuf.Timestamp
	4,  // 7: cas.v1.ListSourcesResponse.sources:type_name -> cas.v1.Source
	5,  // 8: cas.v1.CreateConnectionRequest.exchange_key:type_name -> cas.v1.ExchangeKey
	6,  // 9: cas.v1.CreateConnectionRequest.wallet:type_name -> cas.v1.Wallet
	7,  // 10: cas.v1.CreateConnectionResponse.connection:type_name -> cas.v1.Connection
	7,  // 11: cas.v1.ListConnectionsResponse.connections:type_name -> cas.v1.Connection
	7,  // 12: cas.v1.GetConnectionResponse.connection:type_name -> cas.v1.Connection
	8,  // 13: cas.v1.GetConnectionResponse.streams:type_name -> cas.v1.StreamHealth
	9,  // 14: cas.v1.ConnectionService.ListSources:input_type -> cas.v1.ListSourcesRequest
	11, // 15: cas.v1.ConnectionService.CreateConnection:input_type -> cas.v1.CreateConnectionRequest
	13, // 16: cas.v1.ConnectionService.ListConnections:input_type -> cas.v1.ListConnectionsRequest
	15, // 17: cas.v1.ConnectionService.GetConnection:input_type -> cas.v1.GetConnectionRequest
	17, // 18: cas.v1.ConnectionService.DeleteConnection:input_type -> cas.v1.DeleteConnectionRequest
	19, // 19: cas.v1.ConnectionService.TriggerSync:input_type -> cas.v1.TriggerSyncRequest
	10, // 20: cas.v1.ConnectionService.ListSources:output_type -> cas.v1.ListSourcesResponse
	12, // 21: cas.v1.ConnectionService.CreateConnection:output_type -> cas.v1.CreateConnectionResponse
	14, // 22: cas.v1.ConnectionService.ListConnections:output_type -> cas.v1.ListConnectionsResponse
	16, // 23: cas.v1.ConnectionService.GetConnection:output_type -> cas.v1.GetConnectionResponse
	18, // 24: cas.v1.ConnectionService.DeleteConnection:output_type -> cas.v1.DeleteConnectionResponse
	20, // 25: cas.v1.ConnectionService.TriggerSync:output_type -> cas.v1.TriggerSyncResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cas_v1_connection_service_proto_init() }
func file_cas_v1_connection_service_proto_init() {
	if File_cas_v1_connection_service_proto != nil {
		return
	}
	file_cas_v1_connection_service_proto_msgTypes[7].OneofWrappers = []any{
		(*CreateConnectionRequest_ExchangeKey)(nil),
		(*CreateConnectionRequest_Wallet)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cas_v1_connection_service_proto_rawDesc), len(file_cas_v1_connection_service_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cas_v1_connection_service_proto_goTypes,
		DependencyIndexes: file_cas_v1_connection_service_proto_depIdxs,
		EnumInfos:         file_cas_v1_connection_service_proto_enumTypes,
		MessageInfos:      file_cas_v1_connection_service_proto_msgTypes,
	}.Build()
	File_cas_v1_connection_service_proto = out.File
	file_cas_v1_connection_service_proto_goTypes = nil
	file_cas_v1_connection_service_proto_depIdxs = nil
}
